<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="it" xml:lang="it"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Corrado Caudek">
<title>29&nbsp; Probabilità condizionata – Psicometria</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/probability/06_bayes_theorem.html" rel="next">
<link href="../../chapters/probability/04_sigma-algebra.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-9ac0fa60fcd2ae55f2ddd9f231fc218f.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-d0edb45afdd5f5fd9663be5d5709df0d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nessun risultato",
    "search-matching-documents-text": "documenti trovati",
    "search-copy-link-title": "Copiare il link nella ricerca",
    "search-hide-matches-text": "Nascondere i risultati aggiuntivi",
    "search-more-match-text": "ci sono altri risultati in questo documento",
    "search-more-matches-text": "ulteriori risultati in questo documento",
    "search-clear-button-title": "Pulire",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancellare",
    "search-submit-button-title": "Inviare",
    "search-label": "Ricerca"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-QT5S3P9D31"></script><script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-QT5S3P9D31', { 'anonymize_ip': true});
</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/probability/introduction_probability.html">Probabilità</a></li><li class="breadcrumb-item"><a href="../../chapters/probability/05_conditional_prob.html"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Probabilità condizionata</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Ricerca" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Psicometria</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ccaudek/psicometria-r/" title="Eseguire il codice" class="quarto-navigation-tool px-1" aria-label="Eseguire il codice"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Attiva/disattiva la modalità lettore">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Ricerca"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Informazioni Generali</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../prefazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefazione</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/key_notions/introduction_key_notions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Fondamenti</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/key_notions/01_key_notions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Concetti chiave</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/key_notions/02_design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Campionamento, metodologia sperimentale e studi osservazionali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/key_notions/03_measurement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">La misurazione in psicologia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/key_notions/04_data_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">La riforma metodologica in psicologia: dalla crisi alla rivoluzione bayesiana</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/key_notions/05_cognitive_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modelli cognitivi</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/R/introduction_r_lang.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/R/01_r_syntax.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data Science e R: un approccio moderno all’analisi dei dati</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/R/02_utility_functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Utility functions in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/R/03_r_programming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Programmazione in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/R/04_r_packages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Pacchetti in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/R/05_dplyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Introduzione a <code>dplyr</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/R/06_quarto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Quarto</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/R/07_environment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">L’ambiente di programmazione in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/R/08_ai.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Utilizzo di strumenti AI per la programmazione</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/eda/introduction_eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">EDA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/01_project_structure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Le fasi del progetto di analisi dei dati</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/02_data_cleaning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Flusso di lavoro per la pulizia dei dati</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/04_exploring_qualitative_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Esplorare i dati qualitativi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/05_exploring_numeric_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Esplorare i dati numerici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/06_data_visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Principi della visualizzazione dei dati</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/07_loc_scale.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Indicatori di tendenza centrale e variabilità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/07a_introduction_normal_distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Introduzione alla distribuzione normale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/08_correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Relazioni tra variabili</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/09_causality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Causalità dai dati osservazionali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/10_estimand.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Estimandi teorici e estimandi empirici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/11_outlier.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Outlier</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/probability/introduction_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Probabilità</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/01_intro_prob.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Interpretazione della probabilità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/02_probability_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Modelli probabilistici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/03_prob_spaces.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">La Probabilità come misura della certezza razionale: un’interpretazione Bayesiana</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/04_sigma-algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Dal Discreto al Continuo: la <span class="math inline">\(\sigma\)</span>-algebra</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/05_conditional_prob.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Probabilità condizionata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/06_bayes_theorem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Il teorema di Bayes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/07_random_var.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Variabili casuali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/08_prob_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Distribuzioni di massa e di densità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/09_expval_var.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Proprietà delle variabili casuali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/10_sampling_distr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Stime, stimatori e parametri</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/11_joint_prob.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Probabilità congiunta</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/11a_intro_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Introduzione alle distribuzioni di probabilità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/12_discr_rv_distr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Distribuzioni di v.c. discrete</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/13_cont_rv_distr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Distribuzioni di v.c. continue</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/14_gauss.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Assunzione di gaussianità e trasformazioni dei dati</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/15_likelihood.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">La verosimiglianza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/16_simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Simulazioni</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Inferenza</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/introduction_bayes_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/01_uncertainty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Abbracciare l’incertezza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/02_intro_bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">La quantificazione dell’incertezza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/03_statistical_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Modelli statistici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/04_bayesian_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Inferenza bayesiana</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/05_subj_prop.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Pensare ad una proporzione in termini soggettivi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/06_grid_gauss.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Calcolo della distribuzione a posteriori gaussiana tramite metodo a griglia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/07_conjugate_families_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Distribuzioni coniugate (1)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/08_conjugate_families_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Distribuzioni coniugate (2)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/09_summary_posterior.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Sintesi a posteriori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/10_balance_prior_post.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">L’influenza della distribuzione a priori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/11_gamma_poisson_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Modello coniugato Gamma-Poisson</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/12_gamma_exponential_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Modello gamma-esponenziale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/13_post_pred_distr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Distribuzione predittiva a posteriori</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">MCMC</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/introduction_mcmc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/01_metropolis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">L’algoritmo di Metropolis-Hastings</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/02_ppl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Linguaggi di programmazione probabilistici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/07_bayesian_workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Flusso di lavoro bayesiano</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Regressione</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/introduction_linear_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/01_reglin_frequentist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">La regressione lineare bivariata: un approccio frequentista</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/02_regr_toward_mean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">La regressione verso la media</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/03_reglin_bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Modello bayesiano di regressione lineare bivariata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/04_synt_sugar.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">Zucchero sintattico</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/05_one_mean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title">Inferenza bayesiana su una media</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/06_prediction_stan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title">Predizione e inferenza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/07_two_means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">64</span>&nbsp; <span class="chapter-title">Confronto tra le medie di due gruppi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/08_sample_size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">65</span>&nbsp; <span class="chapter-title">Disegno della ricerca e potere statistico</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/09_anova_1via.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">66</span>&nbsp; <span class="chapter-title">ANOVA ad una via</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/10_anova_2vie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">67</span>&nbsp; <span class="chapter-title">ANOVA ad due vie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/11_one_proportion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">68</span>&nbsp; <span class="chapter-title">Inferenza sulle proporzioni</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/12_two_proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">69</span>&nbsp; <span class="chapter-title">Confronto tra due proporzioni indipendenti</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/13_poisson_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">70</span>&nbsp; <span class="chapter-title">Modello di Poisson</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Frequentismo</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/introduction_frequentist_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/01_intro_frequentist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">71</span>&nbsp; <span class="chapter-title">Inferenza frequentista</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/01a_stime_parametri.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">72</span>&nbsp; <span class="chapter-title">Stime, stimatori e parametri</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/02_conf_interv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">73</span>&nbsp; <span class="chapter-title">Intervalli di fiducia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/03_sample_size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">74</span>&nbsp; <span class="chapter-title">La grandezza del campione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/04_test_ipotesi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">75</span>&nbsp; <span class="chapter-title">Significatività statistica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/05_two_ind_samples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">76</span>&nbsp; <span class="chapter-title">Test t di Student per campioni indipendenti</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">Crisi</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/introduction_replication_crisis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/01_crisis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">77</span>&nbsp; <span class="chapter-title">La crisi della replicazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/02_limits_stat_freq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">78</span>&nbsp; <span class="chapter-title">Limiti dell’inferenza frequentista</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/03_effect_size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">79</span>&nbsp; <span class="chapter-title">La grandezza dell’effetto</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/04_s_m_errors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">80</span>&nbsp; <span class="chapter-title">Errori di segno e errori di grandezza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/05_p_values.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">81</span>&nbsp; <span class="chapter-title">La fragilità del <em>p</em>-valore</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/06_changes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">82</span>&nbsp; <span class="chapter-title">Riforma</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/07_piranha.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">83</span>&nbsp; <span class="chapter-title">Il Problema del priming: sfide e paradossi nella psicologia sociale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/08_degrees_of_freedom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">84</span>&nbsp; <span class="chapter-title">I gradi di libertà del ricercatore</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/09_integrity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">85</span>&nbsp; <span class="chapter-title">Integrità della ricerca</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">Epilogo</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/epiloque/epiloque.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Considerazioni Conclusive</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendici</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a01_shell.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">La Shell</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a02_math_symbols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Simbologia di base</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a03_latex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Equazioni Matematiche in LaTeX</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a11_numbers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Numeri e intervalli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a12_sum_notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Sommatorie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a13_sets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">Insiemi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a14_combinatorics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">G</span>&nbsp; <span class="chapter-title">Calcolo combinatorio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a15_calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">H</span>&nbsp; <span class="chapter-title">Per liberarvi dai terrori preliminari</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a50_lin_fun.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">I</span>&nbsp; <span class="chapter-title">La funzione lineare</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a71_install_cmdstan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">J</span>&nbsp; <span class="chapter-title">Come installare CmdStan</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Indice</h2>
   
  <ul class="collapse">
<li><a href="#introduzione" id="toc-introduzione" class="nav-link active" data-scroll-target="#introduzione"><span class="header-section-number">29.1</span> Introduzione</a></li>
  <li><a href="#indipendenza-stocastica" id="toc-indipendenza-stocastica" class="nav-link" data-scroll-target="#indipendenza-stocastica"><span class="header-section-number">29.2</span> Indipendenza Stocastica</a></li>
  <li><a href="#probabilit%C3%A0-condizionata" id="toc-probabilità-condizionata" class="nav-link" data-scroll-target="#probabilit%C3%A0-condizionata"><span class="header-section-number">29.3</span> Probabilità Condizionata</a></li>
  <li><a href="#indipendenza-e-probabilit%C3%A0-condizionata" id="toc-indipendenza-e-probabilità-condizionata" class="nav-link" data-scroll-target="#indipendenza-e-probabilit%C3%A0-condizionata"><span class="header-section-number">29.4</span> Indipendenza e Probabilità Condizionata</a></li>
  <li><a href="#teorema-del-prodotto" id="toc-teorema-del-prodotto" class="nav-link" data-scroll-target="#teorema-del-prodotto"><span class="header-section-number">29.5</span> Teorema del Prodotto</a></li>
  <li><a href="#teorema-della-probabilit%C3%A0-totale" id="toc-teorema-della-probabilità-totale" class="nav-link" data-scroll-target="#teorema-della-probabilit%C3%A0-totale"><span class="header-section-number">29.6</span> Teorema della Probabilità Totale</a></li>
  <li><a href="#riflessioni-conclusive" id="toc-riflessioni-conclusive" class="nav-link" data-scroll-target="#riflessioni-conclusive"><span class="header-section-number">29.7</span> Riflessioni Conclusive</a></li>
  <li><a href="#esercizi" id="toc-esercizi" class="nav-link" data-scroll-target="#esercizi"><span class="header-section-number">29.8</span> Esercizi</a></li>
  <li><a href="#informazioni-sullambiente-di-sviluppo" id="toc-informazioni-sullambiente-di-sviluppo" class="nav-link" data-scroll-target="#informazioni-sullambiente-di-sviluppo">Informazioni sull’Ambiente di Sviluppo</a></li>
  <li><a href="#bibliografia" id="toc-bibliografia" class="nav-link" data-scroll-target="#bibliografia">Bibliografia</a></li>
  </ul><div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/ccaudek/psicometria-r/blob/main/chapters/probability/05_conditional_prob.qmd" class="toc-action"><i class="bi bi-github"></i>Mostra il codice</a></li><li><a href="https://github.com/ccaudek/psicometria-r/issues/new" class="toc-action"><i class="bi empty"></i>Segnala un problema</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/probability/introduction_probability.html">Probabilità</a></li><li class="breadcrumb-item"><a href="../../chapters/probability/05_conditional_prob.html"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Probabilità condizionata</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-prob-conditional-prob" class="quarto-section-identifier"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Probabilità condizionata</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
In questo capitolo imparerai a:
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>comprendere e applicare i concetti di probabilità congiunta, marginale e condizionata;</li>
<li>approfondire la comprensione e l’applicazione dei principi di indipendenza e probabilità condizionata;</li>
<li>analizzare e interpretare il paradosso di Simpson;</li>
<li>applicare il teorema del prodotto e della probabilità totale.</li>
</ul>
</div>
</div>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Prerequisiti
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Leggere il capitolo <em>Conditional probability</em> di <strong>Introduction to Probability</strong> <span class="citation" data-cites="blitzstein2019introduction">(<a href="#ref-blitzstein2019introduction" role="doc-biblioref">Blitzstein &amp; Hwang, 2019</a>)</span>.</li>
<li>Leggere il capitolo <em>Conditional Probability</em> <span class="citation" data-cites="schervish2014probability">(<a href="#ref-schervish2014probability" role="doc-biblioref">Schervish &amp; DeGroot, 2014</a>)</span>.</li>
</ul>
</div>
</div>
<div class="callout callout-style-simple callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Preparazione del Notebook
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org//reference/here.html">here</a></span><span class="op">(</span><span class="st">"code"</span>, <span class="st">"_common.R"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<section id="introduzione" class="level2" data-number="29.1"><h2 data-number="29.1" class="anchored" data-anchor-id="introduzione">
<span class="header-section-number">29.1</span> Introduzione</h2>
<p>La probabilità condizionata esprime la probabilità di un evento tenendo conto del verificarsi di un altro evento. Questo concetto è fondamentale perché riflette il modo in cui aggiorniamo le nostre credenze alla luce di nuove informazioni. Ad esempio, la probabilità che piova domani può essere diversa a seconda delle condizioni atmosferiche di oggi: osservare un cielo nuvoloso modifica la nostra valutazione della probabilità di pioggia. In questo senso, ogni nuova informazione può confermare, rafforzare o mettere in discussione le credenze preesistenti.</p>
<p>La probabilità condizionata ha un ruolo centrale non solo nella teoria della probabilità, ma anche nelle applicazioni quotidiane e scientifiche. In molti contesti, le probabilità sono implicitamente condizionate da informazioni preesistenti, anche quando non lo esplicitiamo formalmente. Comprendere e quantificare questo processo di aggiornamento delle credenze ci consente di gestire in modo più efficace l’incertezza, rendendo la probabilità uno strumento dinamico per la decisione e l’inferenza.</p>
</section><section id="indipendenza-stocastica" class="level2" data-number="29.2"><h2 data-number="29.2" class="anchored" data-anchor-id="indipendenza-stocastica">
<span class="header-section-number">29.2</span> Indipendenza Stocastica</h2>
<p>Un caso particolare di aggiornamento delle probabilità si verifica quando due eventi sono indipendenti, ovvero quando il verificarsi di un evento non influisce sulla probabilità dell’altro. L’indipendenza semplifica notevolmente i calcoli relativi alla probabilità congiunta di più eventi.</p>
<section id="indipendenza-di-due-eventi" class="level3" data-number="29.2.1"><h3 data-number="29.2.1" class="anchored" data-anchor-id="indipendenza-di-due-eventi">
<span class="header-section-number">29.2.1</span> Indipendenza di Due Eventi</h3>
<p>Due eventi, <span class="math inline">\(A\)</span> e <span class="math inline">\(B\)</span>, sono considerati <strong>indipendenti</strong> se la probabilità che entrambi si verifichino è uguale al prodotto delle loro probabilità individuali:</p>
<p><span id="eq-join-prob-independence"><span class="math display">\[
P(A \cap B) = P(A) P(B).
\tag{29.1}\]</span></span></p>
<p>Questa relazione implica che la conoscenza dell’occorrere di uno degli eventi non modifica la probabilità dell’altro. Quando questa condizione è soddisfatta, si scrive <span class="math inline">\(A \perp B\)</span>, indicando l’indipendenza tra i due eventi.</p>
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Esempio 29.1</strong></span> Supponiamo di lanciare due monete distinte e di considerare i seguenti eventi:</p>
<ul>
<li>
<span class="math inline">\(A\)</span> = “La prima moneta mostra Testa”</li>
<li>
<span class="math inline">\(B\)</span> = “La seconda moneta mostra Testa”</li>
</ul>
<p>Poiché il risultato della prima moneta non influisce sul risultato della seconda, i due eventi sono indipendenti. La probabilità di ottenere Testa su una moneta è: <span class="math display">\[
P(A) = P(B) = \frac{1}{2}
\]</span> La probabilità che entrambe le monete mostrino Testa (ossia che si verifichino entrambi gli eventi <span class="math inline">\(A\)</span> e <span class="math inline">\(B\)</span>) è: <span class="math display">\[
P(A \cap B) = P(A) P(B) = \frac{1}{2} \times \frac{1}{2} = \frac{1}{4}
\]</span> Poiché questa relazione è verificata, possiamo concludere che gli eventi <strong>A e B sono indipendenti</strong>.</p>
</div>
</section><section id="indipendenza-di-un-insieme-di-eventi" class="level3" data-number="29.2.2"><h3 data-number="29.2.2" class="anchored" data-anchor-id="indipendenza-di-un-insieme-di-eventi">
<span class="header-section-number">29.2.2</span> Indipendenza di un Insieme di Eventi</h3>
<p>Il concetto di indipendenza può essere esteso a più eventi. Un insieme di eventi <span class="math inline">\(\{ A_i : i \in I \}\)</span> è <strong>indipendente</strong> se per ogni sottoinsieme finito <span class="math inline">\(J \subseteq I\)</span> la probabilità dell’intersezione di questi eventi è uguale al prodotto delle loro probabilità individuali:</p>
<p><span id="eq-join-prob-independence-set"><span class="math display">\[
P \left( \bigcap_{i \in J} A_i \right) = \prod_{i \in J} P(A_i).
\tag{29.2}\]</span></span></p>
<p>Ciò significa che ogni combinazione di eventi in <span class="math inline">\(J\)</span> si comporta indipendentemente dalle altre. L’indipendenza può essere un’<strong>assunzione</strong> utile in alcuni modelli per semplificare i calcoli, oppure può emergere dai dati attraverso l’analisi empirica.</p>
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Esempio 29.2</strong></span> Per chiarire il concetto di <strong>indipendenza di un insieme di eventi</strong>, consideriamo una sequenza di tre lanci di una moneta equilibrata e definiamo i seguenti eventi:</p>
<ul>
<li>
<span class="math inline">\(A_1\)</span> = “Il primo lancio mostra Testa”</li>
<li>
<span class="math inline">\(A_2\)</span> = “Il secondo lancio mostra Testa”</li>
<li>
<span class="math inline">\(A_3\)</span> = “Il terzo lancio mostra Testa”</li>
</ul>
<p>Poiché ogni lancio di moneta è indipendente dagli altri, la probabilità che un singolo lancio dia Testa è: <span class="math display">\[
P(A_1) = P(A_2) = P(A_3) = \frac{1}{2}
\]</span></p>
<p>L’indipendenza di questi eventi significa che la probabilità che si verifichino <strong>tutti insieme</strong> è data dal prodotto delle loro probabilità individuali: <span class="math display">\[
P(A_1 \cap A_2 \cap A_3) = P(A_1) P(A_2) P(A_3) = \frac{1}{2} \times \frac{1}{2} \times \frac{1}{2} = \frac{1}{8}
\]</span></p>
<p>In modo analogo, possiamo calcolare la probabilità che <strong>qualunque combinazione di Testa e Croce</strong> si verifichi in tre lanci. Ad esempio, la probabilità di ottenere Testa al primo e al terzo lancio, ma Croce al secondo, è: <span class="math display">\[
P(A_1 \cap \neg A_2 \cap A_3) = P(A_1) P(\neg A_2) P(A_3) = \frac{1}{2} \times \frac{1}{2} \times \frac{1}{2} = \frac{1}{8}
\]</span></p>
<p>Poiché questa regola vale per <strong>qualsiasi combinazione di eventi nei tre lanci</strong>, possiamo dire che l’insieme <span class="math inline">\(\{ A_1, A_2, A_3 \}\)</span> è indipendente: la probabilità dell’intersezione di qualsiasi sottoinsieme di eventi è sempre uguale al prodotto delle probabilità individuali.</p>
<p>Questo esempio mostra come l’indipendenza in una sequenza di lanci di moneta implichi che il risultato di un lancio non fornisce alcuna informazione sui risultati degli altri lanci.</p>
</div>
</section><section id="differenza-tra-indipendenza-ed-eventi-disgiunti" class="level3" data-number="29.2.3"><h3 data-number="29.2.3" class="anchored" data-anchor-id="differenza-tra-indipendenza-ed-eventi-disgiunti">
<span class="header-section-number">29.2.3</span> Differenza tra Indipendenza ed Eventi Disgiunti</h3>
<p>Un errore comune è confondere l’indipendenza con la disgiunzione degli eventi. Due eventi sono <strong>disgiunti</strong> (o mutuamente esclusivi) se non possono verificarsi contemporaneamente, ovvero:</p>
<p><span class="math display">\[P(A \cap B) = 0.\]</span></p>
<p>Se due eventi disgiunti hanno probabilità positiva, allora non possono essere indipendenti. Infatti, se <span class="math inline">\(P(A) &gt; 0\)</span> e <span class="math inline">\(P(B) &gt; 0\)</span>, la condizione di indipendenza richiederebbe che <span class="math inline">\(P(A \cap B) = P(A) P(B)\)</span>, ma poiché <span class="math inline">\(P(A \cap B) = 0\)</span>, ciò non può essere vero. Dunque, eventi mutuamente esclusivi e indipendenti rappresentano due concetti distinti: la disgiunzione implica che uno esclude l’altro, mentre l’indipendenza indica che il verificarsi di un evento non fornisce informazioni sull’altro.</p>
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Esempio 29.3</strong></span> Consideriamo un semplice esempio basato sul lancio di un dado a sei facce.</p>
<p>Definiamo i seguenti eventi:</p>
<ul>
<li>
<strong><span class="math inline">\(C\)</span></strong> = “Esce un numero pari” → <span class="math inline">\(\{2, 4, 6\}\)</span><br>
</li>
<li>
<strong><span class="math inline">\(D\)</span></strong> = “Esce un numero dispari” → <span class="math inline">\(\{1, 3, 5\}\)</span>
</li>
</ul>
<p>Poiché un numero non può essere contemporaneamente pari e dispari, i due eventi <strong>non possono verificarsi insieme</strong>. Questo significa che la loro intersezione è vuota:<br><span class="math display">\[
P(C \cap D) = 0
\]</span><br>
e, per definizione, <span class="math inline">\(C\)</span> e <span class="math inline">\(D\)</span> sono <strong>eventi disgiunti</strong>.</p>
<p>Tuttavia, gli eventi <strong>C e D non sono indipendenti</strong>, poiché l’indipendenza richiederebbe che:<br><span class="math display">\[
P(C \cap D) = P(C) P(D)
\]</span><br>
ma in questo caso abbiamo:<br><span class="math display">\[
0 \neq \frac{1}{2} \times \frac{1}{2}
\]</span><br>
Dunque, la disgiunzione e l’indipendenza sono concetti distinti: eventi disgiunti <strong>non possono mai essere indipendenti</strong> se entrambi hanno probabilità positiva.</p>
</div>
</section></section><section id="probabilità-condizionata" class="level2" data-number="29.3"><h2 data-number="29.3" class="anchored" data-anchor-id="probabilità-condizionata">
<span class="header-section-number">29.3</span> Probabilità Condizionata</h2>
<p>La <strong>probabilità condizionata</strong> esprime la probabilità di un evento <span class="math inline">\(A\)</span> assumendo che un altro evento <span class="math inline">\(B\)</span> sia già avvenuto. Si definisce come:</p>
<p><span id="eq-prob-cond-definition"><span class="math display">\[
P(A \mid B) = \frac{P(A \cap B)}{P(B)}, \quad \text{con } P(B) &gt; 0.
\tag{29.3}\]</span></span></p>
<p>Questa formula si ottiene ricalibrando lo spazio delle possibilità: invece di considerare l’intero spazio campionario, ci si limita al sottoinsieme in cui <span class="math inline">\(B\)</span> si è verificato.</p>
<section id="interpretazione-della-probabilità-condizionata" class="level3" data-number="29.3.1"><h3 data-number="29.3.1" class="anchored" data-anchor-id="interpretazione-della-probabilità-condizionata">
<span class="header-section-number">29.3.1</span> Interpretazione della Probabilità Condizionata</h3>
<p>La probabilità condizionata può essere vista come un meccanismo di aggiornamento delle credenze. Se inizialmente si conosce solo <span class="math inline">\(P(A)\)</span>, l’informazione aggiuntiva su <span class="math inline">\(B\)</span> può modificare questa stima. Ad esempio, se si sa che una persona ha la febbre (<span class="math inline">\(B\)</span>), la probabilità che abbia l’influenza (<span class="math inline">\(A\)</span>) può aumentare rispetto alla probabilità iniziale <span class="math inline">\(P(A)\)</span>.</p>
<p>Questa proprietà rende la probabilità condizionata un concetto centrale nelle inferenze statistiche, nella teoria dell’apprendimento e nella modellizzazione delle dipendenze tra eventi.</p>
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Esempio 29.4</strong></span> Lanciamo due dadi equilibrati consecutivamente.<br>
Dato che la somma dei dadi è 10, qual è la probabilità che uno dei due dadi mostri un 6?</p>
<p>Definiamo:</p>
<ul>
<li>
<strong>B</strong> come l’evento che la somma sia 10:<br><span class="math display">\[ B = \{(4, 6), (5, 5), (6, 4)\}. \]</span><br>
</li>
<li>
<strong>A</strong> come l’evento che uno dei due dadi mostri un 6:<br><span class="math display">\[ A = \{(1, 6), \dots, (5, 6), (6, 1), \dots, (6, 5)\}. \]</span>
</li>
</ul>
<p>L’intersezione tra <strong>A</strong> e <strong>B</strong> è:<br><span class="math display">\[ A \cap B = \{(4, 6), (6, 4)\}. \]</span></p>
<p>Poiché in questo esperimento tutti gli eventi elementari sono equiprobabili, la probabilità condizionata <span class="math inline">\(P(A | B)\)</span> è data da:<br><span class="math display">\[
P(A | B) = \frac{P(A \cap B)}{P(B)} = \frac{\frac{2}{36}}{\frac{3}{36}} = \frac{2}{3}.
\]</span></p>
<p>Quindi, la probabilità che uno dei due dadi mostri un 6, sapendo che la somma è 10, è <span class="math inline">\(\frac{2}{3}\)</span>.</p>
</div>
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Esempio 29.5</strong></span> Lanciamo due dadi equilibrati e vogliamo calcolare la probabilità che la somma dei punteggi ottenuti sia minore di 8.</p>
<p>Inizialmente, quando non abbiamo ulteriori informazioni, possiamo calcolare la probabilità in modo tradizionale. Ci sono 21 risultati possibili con somma minore di 8. Poiché ci sono 36 possibili combinazioni di lancio dei due dadi, la probabilità di ottenere una somma minore di 8 è 21/36, che equivale a circa 0.58.</p>
<p>Supponiamo ora di sapere che la somma del lancio di due dadi ha prodotto un risultato dispari. In questo caso, ci sono solo 18 possibili combinazioni di lancio dei due dadi (dato che abbiamo escluso i risultati pari). Tra essi, vi sono 12 risultati che soddisfano la condizione per cui la somma è minore di 8. Quindi, la probabilità di ottenere una somma minore di 8 cambia da circa 0.58 a 12/18, ovvero 0.67 quando consideriamo l’informazione aggiuntiva del risultato dispari.</p>
<p>Svolgiamo il problema in R:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">r</span> <span class="op">&lt;-</span> <span class="fl">1</span><span class="op">:</span><span class="fl">6</span></span>
<span><span class="va">sample</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/expand.grid.html">expand.grid</a></span><span class="op">(</span>i <span class="op">=</span> <span class="va">r</span>, j <span class="op">=</span> <span class="va">r</span><span class="op">)</span></span>
<span><span class="va">sample</span></span>
<span><span class="co">#&gt;    i j</span></span>
<span><span class="co">#&gt; 1  1 1</span></span>
<span><span class="co">#&gt; 2  2 1</span></span>
<span><span class="co">#&gt; 3  3 1</span></span>
<span><span class="co">#&gt; 4  4 1</span></span>
<span><span class="co">#&gt; 5  5 1</span></span>
<span><span class="co">#&gt; 6  6 1</span></span>
<span><span class="co">#&gt; 7  1 2</span></span>
<span><span class="co">#&gt; 8  2 2</span></span>
<span><span class="co">#&gt; 9  3 2</span></span>
<span><span class="co">#&gt; 10 4 2</span></span>
<span><span class="co">#&gt; 11 5 2</span></span>
<span><span class="co">#&gt; 12 6 2</span></span>
<span><span class="co">#&gt; 13 1 3</span></span>
<span><span class="co">#&gt; 14 2 3</span></span>
<span><span class="co">#&gt; 15 3 3</span></span>
<span><span class="co">#&gt; 16 4 3</span></span>
<span><span class="co">#&gt; 17 5 3</span></span>
<span><span class="co">#&gt; 18 6 3</span></span>
<span><span class="co">#&gt; 19 1 4</span></span>
<span><span class="co">#&gt; 20 2 4</span></span>
<span><span class="co">#&gt; 21 3 4</span></span>
<span><span class="co">#&gt; 22 4 4</span></span>
<span><span class="co">#&gt; 23 5 4</span></span>
<span><span class="co">#&gt; 24 6 4</span></span>
<span><span class="co">#&gt; 25 1 5</span></span>
<span><span class="co">#&gt; 26 2 5</span></span>
<span><span class="co">#&gt; 27 3 5</span></span>
<span><span class="co">#&gt; 28 4 5</span></span>
<span><span class="co">#&gt; 29 5 5</span></span>
<span><span class="co">#&gt; 30 6 5</span></span>
<span><span class="co">#&gt; 31 1 6</span></span>
<span><span class="co">#&gt; 32 2 6</span></span>
<span><span class="co">#&gt; 33 3 6</span></span>
<span><span class="co">#&gt; 34 4 6</span></span>
<span><span class="co">#&gt; 35 5 6</span></span>
<span><span class="co">#&gt; 36 6 6</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">event</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">sample</span>, <span class="va">i</span> <span class="op">+</span> <span class="va">j</span> <span class="op">&lt;</span> <span class="fl">8</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">event</span><span class="op">)</span>, <span class="st">"/"</span>, <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">sample</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; 21 / 36</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sample_odd</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">sample</span>, <span class="op">(</span><span class="va">i</span> <span class="op">+</span> <span class="va">j</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/r/base/Arithmetic.html">%%</a></span> <span class="fl">2</span> <span class="op">!=</span> <span class="fl">0</span><span class="op">)</span></span>
<span><span class="va">sample_odd</span></span>
<span><span class="co">#&gt;    i j</span></span>
<span><span class="co">#&gt; 2  2 1</span></span>
<span><span class="co">#&gt; 4  4 1</span></span>
<span><span class="co">#&gt; 6  6 1</span></span>
<span><span class="co">#&gt; 7  1 2</span></span>
<span><span class="co">#&gt; 9  3 2</span></span>
<span><span class="co">#&gt; 11 5 2</span></span>
<span><span class="co">#&gt; 14 2 3</span></span>
<span><span class="co">#&gt; 16 4 3</span></span>
<span><span class="co">#&gt; 18 6 3</span></span>
<span><span class="co">#&gt; 19 1 4</span></span>
<span><span class="co">#&gt; 21 3 4</span></span>
<span><span class="co">#&gt; 23 5 4</span></span>
<span><span class="co">#&gt; 26 2 5</span></span>
<span><span class="co">#&gt; 28 4 5</span></span>
<span><span class="co">#&gt; 30 6 5</span></span>
<span><span class="co">#&gt; 31 1 6</span></span>
<span><span class="co">#&gt; 33 3 6</span></span>
<span><span class="co">#&gt; 35 5 6</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">event</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">sample_odd</span>, <span class="va">i</span> <span class="op">+</span> <span class="va">j</span> <span class="op">&lt;</span> <span class="fl">8</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">event</span><span class="op">)</span>, <span class="st">"/"</span>, <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">sample_odd</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; 12 / 18</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Se applichiamo l’<a href="#eq-prob-cond-definition" class="quarto-xref">Equazione&nbsp;<span>29.3</span></a>, abbiamo: <span class="math inline">\(P(A \cap B)\)</span> = 12/36, <span class="math inline">\(P(B)\)</span> = 18/36 e</p>
<p><span class="math display">\[
P(A \mid B) = \frac{12}{18}.
\]</span></p>
<p>Questo esempio illustra come la probabilità di un evento possa variare in base alle informazioni aggiuntive di cui disponiamo. Nel secondo caso, avendo l’informazione che la somma è dispari, la probabilità di ottenere una somma minore di 8 aumenta notevolmente rispetto al caso iniziale in cui non avevamo questa informazione.</p>
</div>
<div class="callout callout-style-simple callout-tip callout-titled" title="Screening per la diagnosi precoce del tumore mammario">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Screening per la diagnosi precoce del tumore mammario
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Consideriamo uno screening per la diagnosi precoce del tumore mammario utilizzando un test con determinate caratteristiche:</p>
<ul>
<li>Sensibilità del test: 90%. Questo significa che il test classifica correttamente come positivo il 90% delle donne colpite dal cancro al seno.</li>
<li>Specificità del test: 90%. Ciò indica che il test classifica correttamente come negativo il 90% delle donne che non hanno il cancro al seno.</li>
<li>Prevalenza del cancro al seno nella popolazione sottoposta allo screening: 1% (0.01). Questo è il 1% delle donne che ha effettivamente il cancro al seno, mentre il restante 99% (0.99) non ne è affetto.</li>
</ul>
<p>Ora cerchiamo di rispondere alle seguenti domande:</p>
<ul>
<li><p>Qual è la probabilità che una donna scelta a caso ottenga una mammografia positiva? Poiché il 1% delle donne ha il cancro al seno, la probabilità di ottenere una mammografia positiva (test positivo) è pari alla sensibilità del test, ovvero 0.90 (cioè 90%).</p></li>
<li><p>Se la mammografia è positiva, qual è la probabilità che vi sia effettivamente un tumore al seno?</p></li>
</ul>
<p>Per risolvere questo problema, consideriamo un campione di 1000 donne sottoposte al test di screening per il tumore al seno. Di queste 1000 donne:</p>
<ul>
<li>10 donne (1% del campione) hanno effettivamente il cancro al seno. Per queste 10 donne con il cancro, il test darà un risultato positivo (vera positività) in 9 casi (90%).</li>
<li>Per le restanti 990 donne (99% del campione) che non hanno il cancro al seno, il test darà un risultato positivo (falsa positività) in 99 casi (10%).</li>
</ul>
<p>Questa situazione può essere rappresentata graficamente nel seguente modo:</p>
<div id="fig-mammography" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-mammography-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../figures/mammografia.png" class="img-fluid figure-img" style="width:64.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mammography-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;29.1: Esiti della mammografia per 1000 donne.
</figcaption></figure>
</div>
<p>Combinando i due risultati precedenti, vediamo che il test dà un risultato positivo per 9 donne che hanno effettivamente il cancro al seno e per 99 donne che non lo hanno, per un totale di 108 risultati positivi su 1000. Pertanto, la probabilità di ottenere un risultato positivo al test è <span class="math inline">\(\frac{108}{1000}\)</span> = 0.108.</p>
<p>Tuttavia, tra le 108 donne che hanno ottenuto un risultato positivo al test, solo 9 hanno effettivamente il cancro al seno. Quindi, la probabilità di avere il cancro al seno, dato un risultato positivo al test, è pari a <span class="math inline">\(\frac{9}{108}\)</span> = 0.083, corrispondente all’8.3%.</p>
<p>In questo esempio, la probabilità dell’evento “ottenere un risultato positivo al test” è una probabilità non condizionata, poiché calcoliamo semplicemente la proporzione di risultati positivi nel campione totale. D’altra parte, la probabilità dell’evento “avere il cancro al seno, dato che il test ha prodotto un risultato positivo” è una probabilità condizionata, poiché calcoliamo la proporzione delle donne con il cancro al seno tra quelle che hanno ottenuto un risultato positivo al test.</p>
<p>Questo esempio illustra come la conoscenza di ulteriori informazioni (il risultato positivo al test) può influenzare la probabilità di un evento (avere il cancro al seno), mostrando chiaramente la differenza tra probabilità condizionate e non condizionate.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-tip callout-titled" title="Il Problema di Monty Hall">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Il Problema di Monty Hall
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Il <strong>problema di Monty Hall</strong> è un famoso quesito di teoria della probabilità che illustra in modo efficace il concetto di probabilità condizionata. Questo problema è diventato celebre grazie a una rubrica tenuta da Marilyn vos Savant nella rivista <em>Parade</em>, in cui rispose a una lettera pubblicata il 9 settembre 1990:</p>
<blockquote class="blockquote">
<p>“Supponiamo di partecipare a un quiz televisivo e di dover scegliere tra tre porte. Dietro una di esse c’è un’auto, mentre dietro le altre due ci sono delle capre. Scegli una porta, ad esempio la numero 1, e il conduttore, che sa cosa c’è dietro ogni porta, ne apre un’altra, diciamo la numero 3, rivelando una capra. A questo punto, ti chiede se vuoi cambiare la tua scelta e passare alla porta numero 2. È vantaggioso cambiare porta?” Craig. F. Whitaker, Columbia, MD</p>
</blockquote>
<p>La situazione descritta ricorda quella del popolare quiz televisivo degli anni ’70 <em>Let’s Make a Deal</em>, condotto da Monty Hall e Carol Merrill. Marilyn vos Savant rispose che il concorrente dovrebbe cambiare porta, poiché la probabilità di vincere l’auto raddoppia passando da 1/3 a 2/3. Tuttavia, la sua risposta suscitò un acceso dibattito, con molte persone, inclusi alcuni matematici, che sostenevano che cambiare porta non avrebbe offerto alcun vantaggio. Questo episodio ha reso il problema di Monty Hall uno dei più famosi esempi di come l’intuizione possa portare a conclusioni errate in ambito probabilistico.</p>
<p><strong>Chiarire il Problema.</strong></p>
<p>La lettera originale di Craig Whitaker è piuttosto vaga, quindi per analizzare il problema in modo rigoroso è necessario fare alcune ipotesi:</p>
<ol type="1">
<li>
<strong>Posizione dell’auto</strong>: L’auto è nascosta in modo casuale ed equiprobabile dietro una delle tre porte.</li>
<li>
<strong>Scelta iniziale del giocatore</strong>: Il giocatore sceglie una porta in modo casuale, indipendentemente dalla posizione dell’auto.</li>
<li>
<strong>Azione del conduttore</strong>: Dopo la scelta del giocatore, il conduttore apre una delle due porte rimanenti, rivelando una capra, e offre al giocatore la possibilità di cambiare porta.</li>
<li>
<strong>Scelta del conduttore</strong>: Se il conduttore ha la possibilità di scegliere tra due porte (entrambe con capre), ne apre una in modo casuale.</li>
</ol>
<p>Con queste assunzioni, possiamo rispondere alla domanda: <strong>Qual è la probabilità che il giocatore vinca l’auto se decide di cambiare porta?</strong></p>
<p>Di seguito, esploreremo tre metodi per risolvere il problema di Monty Hall: il diagramma ad albero, l’analisi delle probabilità e una simulazione.</p>
<p><strong>Metodo 1: diagramma ad albero.</strong></p>
<p>Il diagramma ad albero è uno strumento utile per visualizzare tutti i possibili esiti di un esperimento probabilistico. Nel caso del problema di Monty Hall, possiamo suddividere il processo in tre fasi:</p>
<ol type="1">
<li>
<strong>Posizione dell’auto</strong>: L’auto può trovarsi dietro una delle tre porte (A, B o C), ciascuna con probabilità 1/3.</li>
<li>
<strong>Scelta del giocatore</strong>: Il giocatore sceglie una porta in modo casuale, indipendentemente dalla posizione dell’auto.</li>
<li>
<strong>Azione del conduttore</strong>: Il conduttore apre una delle due porte rimanenti, rivelando una capra.</li>
</ol>
<p>Il diagramma ad albero mostra tutte le possibili combinazioni di questi eventi. Ad esempio, se l’auto è dietro la porta A e il giocatore sceglie la porta B, il conduttore aprirà la porta C (l’unica porta rimanente con una capra).</p>
<p><strong>Passo 1: Identificare lo spazio campionario</strong><br>
Lo spazio campionario è composto da 12 esiti possibili, rappresentati dalle combinazioni di:</p>
<ul>
<li>Posizione dell’auto (A, B, C).</li>
<li>Scelta iniziale del giocatore (A, B, C).</li>
<li>Porta aperta dal conduttore (una delle due rimanenti con una capra).</li>
</ul>
<p>Ecco un diagramma ad albero che rappresenta questa situazione:</p>
<div id="fig-monthy-hall-tree" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-monthy-hall-tree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../figures/monthy-hall-tree.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-monthy-hall-tree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;29.2: Il diagramma ad albero per il Problema di Monty Hall mostra le probabilità associate a ogni possibile esito. I pesi sugli archi rappresentano la probabilità di seguire quel particolare percorso, dato che ci troviamo nel nodo padre. Ad esempio, se l’auto si trova dietro la porta A, la probabilità che il giocatore scelga inizialmente la porta B è pari a 1/3. La colonna più a destra del diagramma mostra la probabilità di ciascun esito finale. Ogni probabilità di esito è calcolata moltiplicando le probabilità lungo il percorso che parte dalla radice (auto dietro una certa porta) e termina alla foglia (esito finale) (Figura tratta da Lehman, Leighton e Meyer, 2018).
</figcaption></figure>
</div>
<p><strong>Passo 2: Definire l’evento di interesse</strong><br>
L’evento di interesse è “il giocatore vince cambiando porta”. Questo si verifica quando la porta inizialmente scelta dal giocatore non nasconde l’auto, e il giocatore decide di cambiare porta.</p>
<p>Gli esiti che soddisfano questa condizione sono:</p>
<ul>
<li><code>(Auto A, Scelta B, Apertura C)</code></li>
<li><code>(Auto A, Scelta C, Apertura B)</code></li>
<li><code>(Auto B, Scelta A, Apertura C)</code></li>
<li><code>(Auto B, Scelta C, Apertura A)</code></li>
<li><code>(Auto C, Scelta A, Apertura B)</code></li>
<li><code>(Auto C, Scelta B, Apertura A)</code></li>
</ul>
<p>Questi esiti sono in totale 6.</p>
<p><strong>Passo 3: Calcolare le probabilità degli esiti</strong><br>
Ogni esito ha una probabilità specifica, calcolata moltiplicando le probabilità lungo il percorso nel diagramma ad albero.</p>
<p>Esempio di calcolo per l’esito <code>(Auto A, Scelta B, Apertura C)</code>:</p>
<ul>
<li>La probabilità che l’auto sia dietro la porta A è <span class="math inline">\(\frac{1}{3}\)</span>.</li>
<li>La probabilità che il giocatore scelga la porta B è <span class="math inline">\(\frac{1}{3}\)</span>.</li>
<li>La probabilità che il conduttore apra la porta C (che contiene una capra) è <span class="math inline">\(1\)</span> (poiché il conduttore deve aprire una porta con una capra, e la porta C è l’unica possibile).</li>
</ul>
<p>La probabilità totale per questo esito è:</p>
<p><span class="math display">\[
P(\text{Auto A, Scelta B, Apertura C}) = \frac{1}{3} \times \frac{1}{3} \times 1 = \frac{1}{9}.
\]</span></p>
<p>Procedendo in modo simile per tutti gli altri esiti, otteniamo le probabilità per tutti i 12 esiti.</p>
<p><strong>Passo 4: Calcolare la probabilità dell’evento</strong><br>
La probabilità di vincere cambiando porta è la somma delle probabilità degli esiti favorevoli.</p>
<p><span class="math display">\[
\begin{aligned}
P&amp;(\text{vincere cambiando porta}) = \notag \\
&amp;\quad P(\text{Auto A, Scelta B, Apertura C}) + P(\text{Auto A, Scelta C, Apertura B}) + \notag\\  
&amp;\quad P(\text{Auto B, Scelta A, Apertura C}) + \dots \notag
\end{aligned}
\]</span></p>
<p><span class="math display">\[
= \frac{1}{9} + \frac{1}{9} + \frac{1}{9} + \frac{1}{9} + \frac{1}{9} + \frac{1}{9} = \frac{6}{9} = \frac{2}{3}.
\]</span></p>
<p>La probabilità di vincere mantenendo la scelta originale è il complemento:</p>
<p><span class="math display">\[
P(\text{vincere mantenendo la scelta}) = 1 - P(\text{vincere cambiando porta}) = 1 - \frac{2}{3} = \frac{1}{3}.
\]</span></p>
<p>La conclusione è che il giocatore ha una probabilità di vincere pari a <span class="math inline">\(\frac{2}{3}\)</span> se cambia porta, contro una probabilità di <span class="math inline">\(\frac{1}{3}\)</span> se mantiene la sua scelta iniziale. Cambiare porta è quindi la strategia vincente.</p>
<p><strong>Metodo 2: analisi delle probabilità.</strong></p>
<p>Il problema di Monty Hall può essere chiarito analizzando i tre scenari possibili, immaginando di essere osservatori esterni che sanno cosa si nasconde dietro ogni porta:</p>
<ol type="1">
<li>
<p><strong>Primo scenario</strong>:</p>
<ul>
<li>Il giocatore sceglie inizialmente la porta con una capra (chiamiamola “capra 1”).<br>
</li>
<li>Il conduttore apre l’altra porta con la “capra 2”.<br>
</li>
<li>Se il giocatore cambia porta, vince l’automobile.</li>
</ul>
</li>
<li>
<p><strong>Secondo scenario</strong>:</p>
<ul>
<li>Il giocatore sceglie inizialmente la porta con l’altra capra (“capra 2”).<br>
</li>
<li>Il conduttore apre la porta con la “capra 1”.<br>
</li>
<li>Se il giocatore cambia porta, vince l’automobile.</li>
</ul>
</li>
<li>
<p><strong>Terzo scenario</strong>:</p>
<ul>
<li>Il giocatore sceglie inizialmente la porta con l’automobile.<br>
</li>
<li>Il conduttore apre una delle due porte con una capra (non importa quale).<br>
</li>
<li>Se il giocatore cambia porta, perde l’automobile.</li>
</ul>
</li>
</ol>
<p>All’inizio del gioco, il giocatore ha:</p>
<ul>
<li>
<strong>1/3 di probabilità</strong> di scegliere l’automobile.<br>
</li>
<li>
<strong>2/3 di probabilità</strong> di scegliere una capra.</li>
</ul>
<p>Dopo la scelta iniziale, il conduttore apre una porta con una capra, ma questa azione non altera le probabilità iniziali. Il giocatore si trova quindi con due porte chiuse: quella scelta inizialmente e una rimanente.</p>
<ul>
<li>Se il giocatore ha scelto l’automobile inizialmente (1/3 di probabilità), cambiando porta perde.<br>
</li>
<li>Se il giocatore ha scelto una capra inizialmente (2/3 di probabilità), cambiando porta vince l’automobile.</li>
</ul>
<p>In sintesi, cambiando porta, il giocatore ha <strong>2/3 di probabilità</strong> di vincere l’automobile, mentre mantenendo la scelta iniziale ha solo <strong>1/3 di probabilità</strong>. Pertanto, la strategia migliore è cambiare porta per massimizzare le possibilità di vittoria.</p>
<p><strong>Metodo 3: simulazione.</strong></p>
<p>Per confermare il risultato, possiamo eseguire una simulazione. Ripetendo il gioco migliaia di volte, possiamo confrontare la frequenza con cui il giocatore vince cambiando porta rispetto a quando mantiene la scelta iniziale.</p>
<p>Ecco un esempio di codice in R per la simulazione:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">B</span> <span class="op">&lt;-</span> <span class="fl">10000</span></span>
<span><span class="va">monty_hall</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">strategy</span><span class="op">)</span><span class="op">{</span></span>
<span>  <span class="va">doors</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/character.html">as.character</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">3</span><span class="op">)</span></span>
<span>  <span class="va">prize</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"car"</span>, <span class="st">"goat"</span>, <span class="st">"goat"</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="va">prize_door</span> <span class="op">&lt;-</span> <span class="va">doors</span><span class="op">[</span><span class="va">prize</span> <span class="op">==</span> <span class="st">"car"</span><span class="op">]</span></span>
<span>  <span class="va">my_pick</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="va">doors</span>, <span class="fl">1</span><span class="op">)</span></span>
<span>  <span class="va">show</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="va">doors</span><span class="op">[</span><span class="op">!</span><span class="va">doors</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">my_pick</span>, <span class="va">prize_door</span><span class="op">)</span><span class="op">]</span>,<span class="fl">1</span><span class="op">)</span></span>
<span>  <span class="va">stick</span> <span class="op">&lt;-</span> <span class="va">my_pick</span></span>
<span>  <span class="va">stick</span> <span class="op">==</span> <span class="va">prize_door</span></span>
<span>  <span class="va">switch</span> <span class="op">&lt;-</span> <span class="va">doors</span><span class="op">[</span><span class="op">!</span><span class="va">doors</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">my_pick</span>, <span class="va">show</span><span class="op">)</span><span class="op">]</span></span>
<span>  <span class="va">choice</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">strategy</span> <span class="op">==</span> <span class="st">"stick"</span>, <span class="va">stick</span>, <span class="va">switch</span><span class="op">)</span></span>
<span>  <span class="va">choice</span> <span class="op">==</span> <span class="va">prize_door</span></span>
<span><span class="op">}</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">stick</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">replicate</a></span><span class="op">(</span><span class="va">B</span>, <span class="fu">monty_hall</span><span class="op">(</span><span class="st">"stick"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">stick</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 0.3278</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">switch</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">replicate</a></span><span class="op">(</span><span class="va">B</span>, <span class="fu">monty_hall</span><span class="op">(</span><span class="st">"switch"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">switch</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 0.6678</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Spiegazione del codice.</p>
<ol type="1">
<li>
<p><strong>Funzione <code>monty_hall</code></strong>:</p>
<ul>
<li>
<code>doors &lt;- as.character(1:3)</code>: Definisce le tre porte.</li>
<li>
<code>prize &lt;- sample(c("car", "goat", "goat"))</code>: Assegna casualmente l’auto e le capre alle porte.</li>
<li>
<code>prize_door &lt;- doors[prize == "car"]</code>: Identifica la porta con l’auto.</li>
<li>
<code>my_pick &lt;- sample(doors, 1)</code>: Il giocatore sceglie una porta a caso.</li>
<li>
<code>show &lt;- sample(doors[!doors %in% c(my_pick, prize_door)],1)</code>: Il conduttore apre una porta con una capra.</li>
<li>
<code>stick &lt;- my_pick</code>: Mantiene la scelta iniziale.</li>
<li>
<code>switch &lt;- doors[!doors %in% c(my_pick, show)]</code>: Cambia porta.</li>
<li>
<code>choice &lt;- ifelse(strategy == "stick", stick, switch)</code>: Decide se mantenere o cambiare porta in base alla strategia.</li>
<li>
<code>choice == prize_door</code>: Verifica se la scelta finale è la porta con l’auto.</li>
</ul>
</li>
<li>
<p><strong>Simulazione per Mantenere la Scelta Iniziale</strong>:</p>
<ul>
<li>
<code>stick &lt;- replicate(B, monty_hall("stick"))</code>: Ripete il gioco 10.000 volte mantenendo la scelta iniziale.</li>
<li>
<code>mean(stick)</code>: Calcola la frequenza di vittoria.</li>
</ul>
</li>
<li>
<p><strong>Simulazione per Cambiare Porta</strong>:</p>
<ul>
<li>
<code>switch &lt;- replicate(B, monty_hall("switch"))</code>: Ripete il gioco 10.000 volte cambiando porta.</li>
<li>
<code>mean(switch)</code>: Calcola la frequenza di vittoria.</li>
</ul>
</li>
</ol>
<p>Risultati attesi:</p>
<ul>
<li>
<strong>Mantenere la Scelta Iniziale</strong>: La frequenza di vittoria dovrebbe essere circa 1/3 (33.3%).</li>
<li>
<strong>Cambiare Porta</strong>: La frequenza di vittoria dovrebbe essere circa 2/3 (66.6%).</li>
</ul>
<p>La simulazione conferma che cambiare porta aumenta la probabilità di vincere da 1/3 a 2/3, dimostrando che la strategia ottimale nel problema di Monty Hall è quella di cambiare porta dopo che il conduttore ha rivelato una capra.</p>
<p>In sintesi, il problema di Monty Hall mette in luce come l’intuizione possa trarci in inganno quando ci confrontiamo con scenari probabilistici. Attraverso l’uso del diagramma ad albero, un’analisi delle probabilità e l’esecuzione di simulazioni, abbiamo dimostrato che cambiare porta raddoppia le possibilità di vincita, facendole passare da 1/3 a 2/3. Questo risultato, in apparente contrasto con ciò che potrebbe sembrare intuitivo, costituisce un esempio emblematico dell’importanza di adottare un approccio formale nella valutazione delle probabilità, anziché affidarsi esclusivamente a impressioni iniziali che spesso si rivelano fuorvianti.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-tip callout-titled" title="Il paradosso di Simpson">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Il paradosso di Simpson
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Nel contesto della <strong>probabilità condizionata</strong>, un fenomeno particolarmente interessante e, al tempo stesso, controintuitivo è il <strong>paradosso di Simpson</strong>. Questo paradosso si verifica quando una tendenza osservata in diversi gruppi di dati separati scompare o addirittura si inverte una volta che i gruppi vengono combinati.</p>
<p>Il paradosso di Simpson evidenzia l’importanza di considerare le <strong>variabili confondenti</strong> e di analizzare i dati con grande attenzione per evitare di trarre conclusioni errate o fuorvianti. È un esempio emblematico di come l’interpretazione dei dati statistici richieda non solo strumenti matematici, ma anche una profonda comprensione del contesto e delle relazioni tra le variabili coinvolte.</p>
<p>Un caso storico di paradosso di Simpson riguarda l’applicazione della <strong>pena di morte</strong> negli Stati Uniti <span class="citation" data-cites="RadeletPierce1991">(<a href="#ref-RadeletPierce1991" role="doc-biblioref">Radelet &amp; Pierce, 1991</a>)</span>. Questo studio analizza 674 processi per omicidio in Florida tra il 1976 e il 1987, esaminando l’influenza della razza dell’imputato e della vittima sulla probabilità di ricevere la pena di morte. I dati riportano il numero di condannati alla pena di morte in base alla razza dell’imputato e della vittima:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 22%">
<col style="width: 15%">
<col style="width: 19%">
<col style="width: 18%">
</colgroup>
<thead><tr class="header">
<th>Razza dell’imputato</th>
<th>Razza della vittima</th>
<th>Pena di morte</th>
<th>No pena di morte</th>
<th>Tasso di condanna</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Bianco</td>
<td>Bianco</td>
<td>19</td>
<td>132</td>
<td>19 / 151 ≈ 12.6%</td>
</tr>
<tr class="even">
<td>Bianco</td>
<td>Nero</td>
<td>11</td>
<td>52</td>
<td>11 / 63 ≈ 17.5%</td>
</tr>
<tr class="odd">
<td>Nero</td>
<td>Bianco</td>
<td>6</td>
<td>37</td>
<td>6 / 43 ≈ 14.0%</td>
</tr>
<tr class="even">
<td>Nero</td>
<td>Nero</td>
<td>1</td>
<td>9</td>
<td>1 / 10 = 10.0%</td>
</tr>
</tbody>
</table>
<p>Se analizziamo i dati separatamente per la razza della vittima, emerge che la probabilità di ricevere la pena di morte è più alta per gli imputati <strong>bianchi</strong> rispetto agli imputati <strong>neri</strong>, sia nei casi in cui la vittima era bianca (12.6% vs 14.0%) sia nei casi in cui la vittima era nera (17.5% vs 10.0%).</p>
<p>Tuttavia, quando i dati vengono aggregati senza tenere conto della razza della vittima, si osserva una tendenza opposta:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 20%">
<col style="width: 25%">
<col style="width: 23%">
</colgroup>
<thead><tr class="header">
<th>Razza dell’imputato</th>
<th>Pena di morte</th>
<th>No pena di morte</th>
<th>Tasso di condanna</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Bianco</td>
<td>30</td>
<td>184</td>
<td>30 / 214 ≈ 14.0%</td>
</tr>
<tr class="even">
<td>Nero</td>
<td>7</td>
<td>46</td>
<td>7 / 53 ≈ 13.2%</td>
</tr>
</tbody>
</table>
<p>Aggregando i dati, sembra che gli <strong>imputati neri abbiano meno probabilità di ricevere la pena di morte rispetto agli imputati bianchi</strong> (13.2% vs 14.0%).</p>
<p>Questa apparente contraddizione è il risultato del paradosso di Simpson. La variabile confondente in questo caso è la <strong>razza della vittima</strong>: gli omicidi con vittime bianche avevano una probabilità molto più alta di portare alla pena di morte rispetto agli omicidi con vittime nere. Poiché gli imputati bianchi erano più spesso accusati di aver ucciso vittime bianche (per cui la probabilità di pena di morte era maggiore), il loro tasso di condanna complessivo risultava più alto. Viceversa, gli imputati neri erano più spesso accusati di aver ucciso vittime nere (per cui la probabilità di pena di morte era inferiore), abbassando il loro tasso di condanna complessivo.</p>
<p>Questo caso dimostra come l’aggregazione dei dati senza considerare una variabile confondente (in questo caso, la razza della vittima) possa portare a una conclusione errata e fuorviante. È essenziale analizzare i dati in modo stratificato per evitare interpretazioni distorte e per comprendere i reali meccanismi sottostanti un fenomeno.</p>
</div>
</div>
</div>
</section></section><section id="indipendenza-e-probabilità-condizionata" class="level2" data-number="29.4"><h2 data-number="29.4" class="anchored" data-anchor-id="indipendenza-e-probabilità-condizionata">
<span class="header-section-number">29.4</span> Indipendenza e Probabilità Condizionata</h2>
<p>L’indipendenza tra due eventi <span class="math inline">\(A\)</span> e <span class="math inline">\(B\)</span> può essere interpretata intuitivamente attraverso la probabilità condizionata. Due eventi sono indipendenti se il verificarsi di uno non influenza la probabilità di verificarsi dell’altro. In altre parole, conoscere che <span class="math inline">\(B\)</span> è accaduto non modifica la probabilità di <span class="math inline">\(A\)</span>, e viceversa.</p>
<p>Questa relazione può essere formalizzata con le seguenti equazioni:</p>
<p><span class="math display">\[
P(A \mid B) = \frac{P(A \cap B)}{P(B)} = P(A),
\]</span></p>
<p><span class="math display">\[
P(B \mid A) = \frac{P(A \cap B)}{P(A)} = P(B).
\]</span></p>
<p>Pertanto, <span class="math inline">\(A\)</span> e <span class="math inline">\(B\)</span> sono indipendenti se e solo se:</p>
<p><span class="math display">\[
P(A \mid B) = P(A),
\]</span></p>
<p><span class="math display">\[
P(B \mid A) = P(B).
\]</span></p>
<p>Queste condizioni significano che la probabilità di <span class="math inline">\(A\)</span> non cambia, indipendentemente dal fatto che <span class="math inline">\(B\)</span> sia accaduto, e lo stesso vale per <span class="math inline">\(B\)</span>.</p>
<section id="indipendenza-di-tre-eventi" class="level3" data-number="29.4.1"><h3 data-number="29.4.1" class="anchored" data-anchor-id="indipendenza-di-tre-eventi">
<span class="header-section-number">29.4.1</span> Indipendenza di Tre Eventi</h3>
<p>La definizione di indipendenza si estende naturalmente a tre eventi <span class="math inline">\(A\)</span>, <span class="math inline">\(B\)</span>, e <span class="math inline">\(C\)</span>, ma con condizioni aggiuntive. Tre eventi sono <strong>indipendenti</strong> se:</p>
<ol type="1">
<li>
<p>Ogni coppia di eventi è indipendente:</p>
<p><span class="math display">\[
\begin{align}
P(A \cap B) &amp;= P(A) P(B), \\
P(A \cap C) &amp;= P(A) P(C), \\
P(B \cap C) &amp;= P(B) P(C).
\end{align}
\]</span></p>
</li>
<li>
<p>La probabilità congiunta di tutti e tre gli eventi è uguale al prodotto delle loro probabilità individuali:</p>
<p><span class="math display">\[
P(A \cap B \cap C) = P(A) P(B) P(C).
\]</span></p>
</li>
</ol>
<p>Le prime tre condizioni verificano l’indipendenza a coppie (indipendenza a due a due), mentre l’ultima condizione garantisce che i tre eventi siano <strong>completamente indipendenti</strong>. È importante notare che l’indipendenza a due a due non implica necessariamente l’indipendenza completa: per essere indipendenti nel senso completo, tutte e quattro le condizioni devono essere soddisfatte.</p>
<p>In sintesi, l’indipendenza tra eventi implica che il verificarsi di uno di essi non fornisce alcuna informazione sulla probabilità del verificarsi degli altri. Nel caso di due eventi, questa proprietà si traduce nell’invarianza della probabilità condizionata. Per tre o più eventi, l’indipendenza richiede sia l’indipendenza a coppie sia la condizione più forte sull’intersezione di tutti gli eventi.</p>
<p>Questi concetti sono fondamentali nella probabilità e nella statistica, poiché semplificano molti calcoli e forniscono una base per modelli più complessi.</p>
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Esempio 29.6</strong></span> Consideriamo un esempio utilizzando un mazzo di 52 carte. Ogni seme contiene 13 carte e ci sono 4 regine in totale. Definiamo i seguenti eventi:</p>
<ul>
<li>Evento A: pescare una carta di picche,</li>
<li>Evento B: pescare una regina.</li>
</ul>
<p><strong>Probabilità con un mazzo completo</strong></p>
<p>In un mazzo completo, la probabilità di pescare una carta di picche (<span class="math inline">\(P(A)\)</span>) è <span class="math inline">\(\frac{13}{52} = \frac{1}{4}\)</span>, poiché ci sono 13 picche su 52 carte totali. La probabilità di pescare una regina (<span class="math inline">\(P(B)\)</span>) è <span class="math inline">\(\frac{4}{52} = \frac{1}{13}\)</span>, poiché ci sono 4 regine su 52 carte.</p>
<p>Ora consideriamo la probabilità congiunta di pescare la regina di picche (<span class="math inline">\(P(AB)\)</span>). Poiché esiste solo una regina di picche nel mazzo, la probabilità di pescare questa specifica carta è <span class="math inline">\(\frac{1}{52}\)</span>.</p>
<p>Secondo la definizione di indipendenza, se gli eventi <span class="math inline">\(A\)</span> e <span class="math inline">\(B\)</span> sono indipendenti, allora:</p>
<p><span class="math display">\[ P(AB) = P(A)P(B) \]</span></p>
<p>Calcoliamo <span class="math inline">\(P(A)P(B)\)</span>:</p>
<p><span class="math display">\[ P(A)P(B) = \left( \frac{1}{4} \right) \left( \frac{1}{13} \right) = \frac{1}{52} \]</span></p>
<p>Poiché <span class="math inline">\(P(AB) = \frac{1}{52}\)</span> è uguale a <span class="math inline">\(P(A)P(B)\)</span>, possiamo affermare che gli eventi <span class="math inline">\(A\)</span> e <span class="math inline">\(B\)</span> sono indipendenti con un mazzo completo di 52 carte.</p>
<p><strong>Probabilità dopo la rimozione di una carta</strong></p>
<p>Consideriamo ora un mazzo con una carta in meno, ad esempio il due di quadri, riducendo il numero totale di carte a 51. Ricalcoliamo le probabilità con questo mazzo ridotto:</p>
<p>La probabilità di pescare la regina di picche (<span class="math inline">\(P(AB)\)</span>) è ora <span class="math inline">\(\frac{1}{51}\)</span>, poiché ci sono 51 carte nel mazzo.</p>
<p>Ricalcoliamo anche <span class="math inline">\(P(A)\)</span> e <span class="math inline">\(P(B)\)</span>:</p>
<ul>
<li>
<span class="math inline">\(P(A)\)</span> diventa <span class="math inline">\(\frac{13}{51}\)</span>, poiché ci sono ancora 13 picche, ma su 51 carte.</li>
<li>
<span class="math inline">\(P(B)\)</span> diventa <span class="math inline">\(\frac{4}{51}\)</span>, poiché ci sono ancora 4 regine, ma su 51 carte.</li>
</ul>
<p>Ora calcoliamo il prodotto <span class="math inline">\(P(A)P(B)\)</span> con queste nuove probabilità:</p>
<p><span class="math display">\[ P(A)P(B) = \left( \frac{13}{51} \right) \left( \frac{4}{51} \right) = \frac{52}{2601} \]</span></p>
<p>Confrontiamo <span class="math inline">\(P(AB)\)</span> e <span class="math inline">\(P(A)P(B)\)</span>:</p>
<p><span class="math display">\[ \frac{1}{51} \neq \frac{52}{2601} \]</span></p>
<p>Poiché <span class="math inline">\(\frac{1}{51} \neq \frac{52}{2601}\)</span>, gli eventi <span class="math inline">\(A\)</span> e <span class="math inline">\(B\)</span> non sono più indipendenti dopo la rimozione del due di quadri.</p>
<p>Questo esempio mostra come l’indipendenza tra due eventi dipenda dal contesto. Con un mazzo completo, i due eventi sono indipendenti. Tuttavia, rimuovendo una carta dal mazzo, le probabilità cambiano e gli eventi non sono più indipendenti. Questo evidenzia l’importanza di considerare la composizione e le condizioni iniziali quando si analizzano probabilità e indipendenza. Modifiche nella composizione del mazzo possono alterare le probabilità, influenzando le relazioni di indipendenza tra eventi specifici.</p>
</div>
</section></section><section id="teorema-del-prodotto" class="level2" data-number="29.5"><h2 data-number="29.5" class="anchored" data-anchor-id="teorema-del-prodotto">
<span class="header-section-number">29.5</span> Teorema del Prodotto</h2>
<p>Dalla definizione di probabilità condizionata, deriva il <strong>Teorema del Prodotto</strong> (o <em>teorema della probabilità composta</em>, <em>regola moltiplicativa</em>, <em>regola della catena</em>). Questo teorema permette di calcolare la probabilità congiunta di due o più eventi come prodotto di probabilità condizionate.</p>
<section id="caso-di-due-eventi" class="level3" data-number="29.5.1"><h3 data-number="29.5.1" class="anchored" data-anchor-id="caso-di-due-eventi">
<span class="header-section-number">29.5.1</span> Caso di due eventi</h3>
<p>Per due eventi <span class="math inline">\(A\)</span> e <span class="math inline">\(B\)</span>, il teorema si esprime come:</p>
<p><span id="eq-probcondinv"><span class="math display">\[
P(A \cap B) = P(B) \cdot P(A \mid B) = P(A) \cdot P(B \mid A).
\tag{29.4}\]</span></span></p>
<p>La formula indica che la probabilità che entrambi gli eventi si verifichino è pari:</p>
<ul>
<li>Alla probabilità di <span class="math inline">\(B\)</span> moltiplicata per la probabilità di <span class="math inline">\(A\)</span> <strong>dato</strong> <span class="math inline">\(B\)</span>;<br>
</li>
<li>Oppure alla probabilità di <span class="math inline">\(A\)</span> moltiplicata per la probabilità di <span class="math inline">\(B\)</span> <strong>dato</strong> <span class="math inline">\(A\)</span>.</li>
</ul>
<p>L’ordine degli eventi può essere scelto in base alla comodità di calcolo, purché si rispetti la condizionalità.</p>
</section><section id="generalizzazione-a-n-eventi" class="level3" data-number="29.5.2"><h3 data-number="29.5.2" class="anchored" data-anchor-id="generalizzazione-a-n-eventi">
<span class="header-section-number">29.5.2</span> Generalizzazione a <span class="math inline">\(n\)</span> eventi</h3>
<p>Per <span class="math inline">\(n\)</span> eventi <span class="math inline">\(A_1, A_2, \dots, A_n\)</span>, con <span class="math inline">\(P(A_1 \cap A_2 \cap \cdots \cap A_{n-1}) &gt; 0\)</span>, la probabilità congiunta è:</p>
<p><span id="eq-probcomposte"><span class="math display">\[
\begin{split}
P(A_1 \cap A_2 \cap \cdots \cap A_n) &amp;= P(A_1) \cdot P(A_2 \mid A_1) \cdot P(A_3 \mid A_1 \cap A_2) \cdots \\
&amp;\quad \cdots \cdot P(A_n \mid A_1 \cap A_2 \cap \cdots \cap A_{n-1}).
\end{split}
\tag{29.5}\]</span></span></p>
<section id="procedura-di-calcolo" class="level4" data-number="29.5.2.1"><h4 data-number="29.5.2.1" class="anchored" data-anchor-id="procedura-di-calcolo">
<span class="header-section-number">29.5.2.1</span> Procedura di calcolo</h4>
<p>Per applicare la regola:</p>
<ol type="1">
<li>
<strong>Parti dal primo evento</strong>: usa la probabilità incondizionata <span class="math inline">\(P(A_1)\)</span>.<br>
</li>
<li>
<strong>Condiziona progressivamente</strong>: moltiplica per <span class="math inline">\(P(A_2 \mid A_1)\)</span>, poi per <span class="math inline">\(P(A_3 \mid A_1 \cap A_2)\)</span>, e così via.<br>
</li>
<li>
<strong>Termina con l’ultimo evento</strong>: includi <span class="math inline">\(P(A_n \mid A_1 \cap \cdots \cap A_{n-1})\)</span>.</li>
</ol></section></section><section id="osservazioni" class="level3" data-number="29.5.3"><h3 data-number="29.5.3" class="anchored" data-anchor-id="osservazioni">
<span class="header-section-number">29.5.3</span> Osservazioni</h3>
<ul>
<li>
<strong>Ordine degli eventi</strong>: La regola può essere applicata in qualsiasi ordine, adattando le condizionate (es.: <span class="math inline">\(P(B) \cdot P(A \mid B) \cdot P(C \mid A \cap B)\)</span>).<br>
</li>
<li>
<strong>Applicazioni</strong>: Fondamentale in catene di Markov, reti Bayesiane e processi stocastici, dove le dipendenze tra eventi sono sequenziali.<br>
</li>
<li>
<strong>Importanza della condizione</strong>: Le probabilità condizionate richiedono <span class="math inline">\(P(\text{eventi precedenti}) &gt; 0\)</span>.</li>
</ul>
<p><strong>In sintesi</strong>, il teorema trasforma una probabilità congiunta complessa in un prodotto di termini più semplici, sfruttando le relazioni condizionali tra gli eventi.</p>
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Esempio 29.7</strong></span> <strong>Esempio.</strong><br>
Consideriamo quattro eventi <span class="math inline">\(A_1, A_2, A_3, A_4\)</span>. La probabilità congiunta si esprime come:</p>
<p><span class="math display">\[
P(A_1 \cap A_2 \cap A_3 \cap A_4) = P(A_1) \cdot P(A_2 \mid A_1) \cdot P(A_3 \mid A_1 \cap A_2) \cdot P(A_4 \mid A_1 \cap A_2 \cap A_3).
\]</span></p>
<p>In questa espressione:</p>
<ul>
<li>
<span class="math inline">\(P(A_1)\)</span> rappresenta la probabilità incondizionata del primo evento.</li>
<li>
<span class="math inline">\(P(A_2 \mid A_1)\)</span> è la probabilità del secondo evento dato il verificarsi del primo.</li>
<li>
<span class="math inline">\(P(A_3 \mid A_1 \cap A_2)\)</span> è la probabilità del terzo evento, condizionata al verificarsi sia del primo che del secondo.</li>
<li>
<span class="math inline">\(P(A_4 \mid A_1 \cap A_2 \cap A_3)\)</span> è la probabilità del quarto evento, condizionata al verificarsi dei tre eventi precedenti.</li>
</ul>
</div>
<p>Il Teorema del Prodotto rappresenta uno dei fondamenti teorici più importanti della probabilità e trova applicazioni in numerosi contesti, quali:</p>
<ul>
<li>La modellazione di processi sequenziali o temporali.</li>
<li>La scomposizione di problemi complessi in calcoli più semplici e gestibili.</li>
<li>La teoria delle reti bayesiane e l’analisi della probabilità condizionata.</li>
</ul>
<p>Grazie a questo teorema, è possibile affrontare problemi complessi suddividendoli in passaggi progressivi, in cui ogni probabilità condizionata contribuisce alla costruzione della soluzione complessiva in maniera sistematica.</p>
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Esempio 29.8</strong></span> Da un’urna contenente 6 palline bianche e 4 nere si estrae una pallina per volta, senza reintrodurla nell’urna. Indichiamo con <span class="math inline">\(B_i\)</span> l’evento: “esce una pallina bianca alla <span class="math inline">\(i\)</span>-esima estrazione” e con <span class="math inline">\(N_i\)</span> l’estrazione di una pallina nera. L’evento: “escono due palline bianche nelle prime due estrazioni” è rappresentato dalla intersezione <span class="math inline">\(\{B_1 \cap B_2\}\)</span> e, per l’<a href="#eq-probcondinv" class="quarto-xref">Equazione&nbsp;<span>29.4</span></a>, la sua probabilità vale</p>
<p><span class="math display">\[
P(B_1 \cap B_2) = P(B_1)P(B_2 \mid B_1).
\]</span></p>
<p><span class="math inline">\(P(B_1)\)</span> vale 6/10, perché nella prima estrazione <span class="math inline">\(\Omega\)</span> è costituito da 10 elementi: 6 palline bianche e 4 nere. La probabilità condizionata <span class="math inline">\(P(B_2 \mid B_1)\)</span> vale 5/9, perché nella seconda estrazione, se è verificato l’evento <span class="math inline">\(B_1\)</span>, lo spazio campionario consiste di 5 palline bianche e 4 nere. Si ricava pertanto:</p>
<p><span class="math display">\[
P(B_1 \cap B_2) = \frac{6}{10} \cdot \frac{5}{9} = \frac{1}{3}.
\]</span></p>
<p>In modo analogo si ha che</p>
<p><span class="math display">\[
P(N_1 \cap N_2) = P(N_1)P(N_2 \mid N_1) = \frac{4}{10} \cdot \frac{3}{9} = \frac{4}{30}.
\]</span></p>
<p>Se l’esperimento consiste nell’estrazione successiva di 3 palline, la probabilità che queste siano tutte bianche, per l’<a href="#eq-probcomposte" class="quarto-xref">Equazione&nbsp;<span>29.5</span></a>, vale</p>
<p><span class="math display">\[
\begin{aligned}
P(B_1 \cap B_2 \cap B_3) &amp;=P(B_1)P(B_2 \mid B_1)P(B_3 \mid B_1 \cap B_2) \notag\\
&amp;=\frac{6}{10}\cdot\frac{5}{9} \cdot\frac{4}{8} \notag\\
&amp;= \frac{1}{6}.
\end{aligned}
\]</span></p>
<p>La probabilità dell’estrazione di tre palline nere è invece:</p>
<p><span class="math display">\[
\begin{aligned}
P(N_1 \cap N_2 \cap N_3) &amp;= P(N_1)P(N_2 \mid N_1)P(N_3 \mid N_1 \cap N_2)\notag\\
&amp;= \frac{4}{10} \cdot \frac{3}{9} \cdot \frac{2}{8} \notag\\
&amp;= \frac{1}{30}.\notag
\end{aligned}
\]</span></p>
</div>
</section></section><section id="teorema-della-probabilità-totale" class="level2" data-number="29.6"><h2 data-number="29.6" class="anchored" data-anchor-id="teorema-della-probabilità-totale">
<span class="header-section-number">29.6</span> Teorema della Probabilità Totale</h2>
<p>Il <strong>teorema della probabilità totale</strong> (o <em>legge della probabilità totale</em>) consente di calcolare la probabilità di un evento <span class="math inline">\(A\)</span> scomponendolo rispetto a una partizione dello spazio campionario. Questo strumento è essenziale per semplificare problemi complessi in contesti con più scenari o categorie.</p>
<section id="enunciato-generale" class="level3" data-number="29.6.1"><h3 data-number="29.6.1" class="anchored" data-anchor-id="enunciato-generale">
<span class="header-section-number">29.6.1</span> Enunciato Generale</h3>
<p>Sia <span class="math inline">\(\Omega\)</span> uno spazio campionario suddiviso in una <strong>partizione</strong> di eventi <span class="math inline">\(B_1, B_2, \dots, B_n\)</span>, ovvero:</p>
<ul>
<li>
<strong>Mutua esclusività</strong>: <span class="math inline">\(B_i \cap B_j = \varnothing\)</span> per <span class="math inline">\(i \neq j\)</span>.<br>
</li>
<li>
<strong>Copertura totale</strong>: <span class="math inline">\(\bigcup_{i=1}^n B_i = \Omega\)</span>.</li>
</ul>
<p>Allora, la probabilità di un evento <span class="math inline">\(A \subseteq \Omega\)</span> è data da:<br><span id="eq-prob-teorem-total-prob"><span class="math display">\[
P(A) = \sum_{i=1}^n P(A \cap B_i) = \sum_{i=1}^n P(A \mid B_i) \cdot P(B_i).
\tag{29.6}\]</span></span></p>
<p>In pratica, <span class="math inline">\(P(A)\)</span> è una <strong>media pesata</strong> delle probabilità condizionate <span class="math inline">\(P(A \mid B_i)\)</span>, con pesi <span class="math inline">\(P(B_i)\)</span>.</p>
</section><section id="caso-di-due-partizioni" class="level3" data-number="29.6.2"><h3 data-number="29.6.2" class="anchored" data-anchor-id="caso-di-due-partizioni">
<span class="header-section-number">29.6.2</span> Caso di Due Partizioni</h3>
<p>Se lo spazio è diviso in due soli eventi <span class="math inline">\(B\)</span> e <span class="math inline">\(B^c\)</span>, il teorema assume la forma:<br><span id="eq-prob-teorem-total-prob-two-part"><span class="math display">\[
\begin{align}
P(A) &amp;= P(A \cap B) + P(A \cap B^c) \notag\\
&amp; = P(A \mid B) \cdot P(B) + P(A \mid B^c) \cdot P(B^c).
\end{align}
\tag{29.7}\]</span></span></p>
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Esempio 29.9</strong></span> &nbsp;</p>
<ul>
<li>
<span class="math inline">\(B\)</span>: “Una persona è malata”.<br>
</li>
<li>
<span class="math inline">\(B^c\)</span>: “Una persona è sana”.<br>
</li>
<li>
<span class="math inline">\(A\)</span>: “Test medico positivo”.</li>
</ul>
<p>La probabilità di un test positivo è:<br><span class="math display">\[
P(A) = P(\text{Positivo} \mid \text{Malato}) \cdot P(\text{Malato}) + P(\text{Positivo} \mid \text{Sano}) \cdot P(\text{Sano}).
\]</span></p>
</div>
</section><section id="applicazioni" class="level3" data-number="29.6.3"><h3 data-number="29.6.3" class="anchored" data-anchor-id="applicazioni">
<span class="header-section-number">29.6.3</span> Applicazioni</h3>
<ol type="1">
<li>
<strong>Analisi per Categorie</strong><br>
Suddividendo una popolazione in gruppi <span class="math inline">\(B_1, \dots, B_n\)</span> (es.: fasce d’età, regioni), <span class="math inline">\(P(A)\)</span> si calcola come:<br><span class="math display">\[
P(A) = \sum_{i=1}^n P(A \mid B_i) \cdot P(B_i).
\]</span>
</li>
</ol>
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Esempio 29.10</strong></span> In un test psicologico somministrato a tre gruppi di studenti con differenti livelli di ansia (<strong>basso</strong>, <strong>medio</strong>, <strong>alto</strong>), la distribuzione degli studenti è del <strong>50%</strong>, <strong>30%</strong> e <strong>20%</strong>, rispettivamente. La probabilità che uno studente risponda impulsivamente a una domanda è data da:<br><span class="math display">\[
  P(\text{Impulsiva}) = \sum_{i=1}^3 P(\text{Impulsiva} \mid \text{Ansia livello } i) \cdot P(\text{Ansia livello } i).
  \]</span></p>
</div>
<ol start="2" type="1">
<li>
<strong>Teorema di Bayes</strong><br>
La probabilità totale compare al denominatore della formula di Bayes per calcolare <span class="math inline">\(P(E)\)</span>, la probabilità dei dati osservati:<br><span class="math display">\[
P(H_i \mid E) = \frac{P(E \mid H_i) \cdot P(H_i)}{\sum_{j=1}^n P(E \mid H_j) \cdot P(H_j)}.
\]</span><br>
Qui, <span class="math inline">\(H_1, \dots, H_n\)</span> formano una partizione di ipotesi.</li>
</ol>
<p>In sintesi, il teorema della probabilità totale trasforma un problema globale in una somma di problemi locali, condizionati a scenari specifici.</p>
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Esempio 29.11</strong></span> Un team di psicologi desidera stimare la probabilità complessiva di soffrire di depressione nella popolazione generale, distinguendo tre fasce d’età: giovani (18–30 anni), adulti (31–50 anni) e anziani (51+ anni).</p>
<p>I dati raccolti mostrano che:</p>
<ul>
<li><p>Il 30% della popolazione è giovane, il 40% è adulta e il 30% è anziana.<br></p></li>
<li>
<p>Le probabilità <em>condizionate</em> di soffrire di depressione nelle tre fasce sono:</p>
<p><span class="math display">\[
P(D \mid G) = 0.10, \quad
P(D \mid A) = 0.20, \quad
P(D \mid Z) = 0.35.
\]</span></p>
</li>
</ul>
<p>Per ottenere la probabilità totale di soffrire di depressione (<span class="math inline">\(P(D)\)</span>) nella popolazione, si applica la legge della probabilità totale:</p>
<p><span class="math display">\[
P(D) = P(D \mid G)\,P(G) + P(D \mid A)\,P(A) + P(D \mid Z)\,P(Z).
\]</span></p>
<p>Di seguito il codice R per effettuare il calcolo:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Probabilità di ciascuna fascia d'età</span></span>
<span><span class="va">P_G</span> <span class="op">&lt;-</span> <span class="fl">0.30</span></span>
<span><span class="va">P_A</span> <span class="op">&lt;-</span> <span class="fl">0.40</span></span>
<span><span class="va">P_Z</span> <span class="op">&lt;-</span> <span class="fl">0.30</span></span>
<span></span>
<span><span class="co"># Probabilità condizionate di depressione</span></span>
<span><span class="va">P_D_given_G</span> <span class="op">&lt;-</span> <span class="fl">0.10</span></span>
<span><span class="va">P_D_given_A</span> <span class="op">&lt;-</span> <span class="fl">0.20</span></span>
<span><span class="va">P_D_given_Z</span> <span class="op">&lt;-</span> <span class="fl">0.35</span></span>
<span></span>
<span><span class="co"># Calcolo della probabilità totale</span></span>
<span><span class="va">P_D</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">P_D_given_G</span> <span class="op">*</span> <span class="va">P_G</span><span class="op">)</span> <span class="op">+</span> <span class="op">(</span><span class="va">P_D_given_A</span> <span class="op">*</span> <span class="va">P_A</span><span class="op">)</span> <span class="op">+</span> <span class="op">(</span><span class="va">P_D_given_Z</span> <span class="op">*</span> <span class="va">P_Z</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"La probabilità totale di soffrire di depressione è:"</span>, <span class="va">P_D</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; La probabilità totale di soffrire di depressione è: 0.215</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Interpretazione</strong><br>
Dal risultato, circa il 21.5% della popolazione soffre di depressione. Questo calcolo è particolarmente utile quando i dati derivano da sottopopolazioni distinte, in quanto fornisce una stima complessiva combinando i contributi di ciascun gruppo.</p>
</div>
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Esempio 29.12</strong></span> Abbiamo tre urne, ciascuna delle quali contiene 100 palline:</p>
<ul>
<li>Urna 1: 75 palline rosse e 25 palline blu,</li>
<li>Urna 2: 60 palline rosse e 40 palline blu,</li>
<li>Urna 3: 45 palline rosse e 55 palline blu.</li>
</ul>
<p>Una pallina viene estratta a caso da un’urna anch’essa scelta a caso. Qual è la probabilità che la pallina estratta sia di colore rosso?</p>
<p>Sia <span class="math inline">\(R\)</span> l’evento “la pallina estratta è rossa” e sia <span class="math inline">\(U_i\)</span> l’evento che corrisponde alla scelta dell’<span class="math inline">\(i\)</span>-esima urna. Sappiamo che</p>
<p><span class="math display">\[
P(R \mid U_1) = 0.75, \quad P(R \mid U_2) = 0.60, \quad P(R \mid U_3) = 0.45.
\]</span></p>
<p>Gli eventi <span class="math inline">\(U_1\)</span>, <span class="math inline">\(U_2\)</span> e <span class="math inline">\(U_3\)</span> costituiscono una partizione dello spazio campione in quanto <span class="math inline">\(U_1\)</span>, <span class="math inline">\(U_2\)</span> e <span class="math inline">\(U_3\)</span> sono eventi mutualmente esclusivi ed esaustivi, ovvero <span class="math inline">\(P(U_1 \cup U_2 \cup U_3) = 1.0\)</span>. In base al teorema della probabilità totale, la probabilità di estrarre una pallina rossa è dunque</p>
<p><span class="math display">\[
\begin{split}
P(R) &amp;= P(R \mid U_1)P(U_1) + P(R \mid U_2)P(U_2) + P(R \mid U_3)P(U_3) \\
&amp;= 0.75 \cdot \frac{1}{3}+0.60 \cdot \frac{1}{3}+0.45 \cdot \frac{1}{3} \\
&amp;=0.60.
\end{split}
\]</span></p>
</div>
</section></section><section id="riflessioni-conclusive" class="level2" data-number="29.7"><h2 data-number="29.7" class="anchored" data-anchor-id="riflessioni-conclusive">
<span class="header-section-number">29.7</span> Riflessioni Conclusive</h2>
<p>La probabilità condizionata è uno dei concetti fondamentali della statistica, poiché fornisce il quadro teorico necessario per comprendere l’indipendenza statistica e molte altre relazioni tra eventi e variabili.</p>
<p>Un punto chiave è che l’indipendenza implica l’assenza di una <strong>associazione</strong> tra due variabili. Nei capitoli successivi esploreremo strumenti per misurare la correlazione correlazione, ovvero la presenza e l’intensità di una relazione <strong>lineare</strong> tra di esse.</p>
<p>La probabilità condizionata ha inoltre permesso di riformulare la legge della probabilità totale, che consente di scomporre probabilità complesse utilizzando partizioni dello spazio campionario. Questa legge si rivela cruciale per il teorema di Bayes, uno degli strumenti cardine dell’inferenza statistica.</p>
<p>In particolare, nel contesto dell’inferenza bayesiana, il condizionamento assume un ruolo fondamentale. Grazie a questo principio, è possibile aggiornare continuamente le credenze o le incertezze riguardo a ipotesi, integrando nuove informazioni man mano che diventano disponibili. Questa capacità di adattamento rende l’inferenza bayesiana uno strumento estremamente flessibile e potente, capace di modellare situazioni complesse e dinamiche.</p>
<p>In sintesi, la probabilità condizionata non solo è essenziale per comprendere l’indipendenza statistica, ma costituisce anche la base di metodi inferenziali avanzati, come l’inferenza bayesiana. Attraverso di essa, possiamo costruire modelli che evolvono e migliorano con l’aggiunta di nuove informazioni, rendendo l’analisi statistica uno strumento dinamico e versatile per interpretare il mondo reale.</p>
</section><section id="esercizi" class="level2" data-number="29.8"><h2 data-number="29.8" class="anchored" data-anchor-id="esercizi">
<span class="header-section-number">29.8</span> Esercizi</h2>
<div class="callout callout-style-simple callout-tip callout-titled" title="Esercizio">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Esercizio
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Esercizio 1: Soddisfazione con la Vita e Stress Accademico</strong></p>
<p>Un gruppo di studenti ha compilato la <strong>Satisfaction with Life Scale (SWLS)</strong> e un questionario sullo stress accademico. Dai dati raccolti emerge che:</p>
<ul>
<li>Il 40% degli studenti ha riportato un alto livello di stress accademico.</li>
<li>Il 60% degli studenti ha riportato un basso livello di stress accademico.</li>
<li>Tra gli studenti con alto stress, il 30% ha riportato una soddisfazione con la vita elevata.</li>
<li>Tra gli studenti con basso stress, il 70% ha riportato una soddisfazione con la vita elevata.</li>
</ul>
<p>Calcola la probabilità che uno studente scelto a caso abbia:</p>
<ol type="1">
<li>Un alto livello di stress e una soddisfazione elevata.</li>
<li>Una soddisfazione elevata.</li>
<li>Un alto livello di stress, dato che ha una soddisfazione elevata.</li>
</ol>
<p><strong>Esercizio 2: Studio del Paradosso di Simpson</strong></p>
<p>Un’università vuole valutare la relazione tra la frequenza di partecipazione alle lezioni e il successo negli esami finali. I dati raccolti mostrano che:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 39%">
<col style="width: 23%">
<col style="width: 25%">
</colgroup>
<thead><tr class="header">
<th>Gruppo</th>
<th>Studenti con alta frequenza</th>
<th>Superano l’esame</th>
<th>Non superano l’esame</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>40</td>
<td>30</td>
<td>10</td>
</tr>
<tr class="even">
<td>B</td>
<td>60</td>
<td>20</td>
<td>40</td>
</tr>
</tbody>
</table>
<ol type="1">
<li>Calcola la probabilità di superare l’esame per ciascun gruppo separatamente.</li>
<li>Calcola la probabilità totale di superare l’esame.</li>
<li>Spiega se il Paradosso di Simpson si manifesta in questi dati.</li>
</ol>
<p><strong>Esercizio 3: Il Problema di Monty Hall</strong></p>
<p>In un quiz televisivo, un concorrente deve scegliere tra tre porte: dietro una c’è un’auto e dietro le altre due ci sono capre. Dopo la scelta iniziale, il conduttore, che sa cosa c’è dietro ogni porta, apre una delle due porte rimanenti rivelando una capra. Il concorrente ha ora la possibilità di cambiare la sua scelta.</p>
<ol type="1">
<li>Qual è la probabilità di vincere l’auto se il concorrente <strong>non cambia</strong> la sua scelta?</li>
<li>Qual è la probabilità di vincere l’auto se il concorrente <strong>cambia</strong> la sua scelta?</li>
<li>Spiega perché cambiare porta è la strategia migliore.</li>
</ol>
<p><strong>Esercizio 4: Teorema della Probabilità Totale</strong></p>
<p>Un’università ha tre dipartimenti: Psicologia, Economia e Ingegneria. Le proporzioni di studenti iscritti sono:</p>
<ul>
<li>Psicologia: 40%</li>
<li>Economia: 35%</li>
<li>Ingegneria: 25%</li>
</ul>
<p>La probabilità di laurearsi in tempo varia per ogni dipartimento:</p>
<ul>
<li>Psicologia: 70%</li>
<li>Economia: 60%</li>
<li>Ingegneria: 80%</li>
</ul>
<p>Calcola la probabilità che uno studente scelto a caso si laurei in tempo.</p>
<p><strong>Esercizio 5: Urne e Palline</strong></p>
<p>Un’urna contiene 5 palline rosse e 7 blu. Si estrae una pallina, si osserva il colore e poi la pallina viene rimessa nell’urna. Quindi si estrae una seconda pallina.</p>
<ol type="1">
<li>Qual è la probabilità di estrarre due palline rosse?</li>
<li>Qual è la probabilità di estrarre almeno una pallina blu?</li>
<li>Qual è la probabilità di estrarre una pallina rossa alla seconda estrazione, dato che la prima estratta era blu?</li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-tip callout-titled" title="Soluzioni">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Soluzioni
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Esercizio 1: Soddisfazione con la Vita e Stress Accademico</strong></p>
<ol type="1">
<li>
<p>La probabilità che uno studente abbia <strong>alto stress</strong> e <strong>soddisfazione elevata</strong> si calcola moltiplicando la probabilità condizionata di avere soddisfazione elevata dato l’alto stress per la probabilità di avere alto stress:</p>
<p><span class="math display">\[
P(S \cap V) = P(V | S) P(S) = 0.30 \times 0.40 = 0.12.
\]</span></p>
</li>
<li>
<p>La probabilità che uno studente abbia una <strong>soddisfazione elevata</strong>, indipendentemente dal livello di stress, si ottiene applicando la legge della probabilità totale:</p>
<p><span class="math display">\[
P(V) = P(V | S) P(S) + P(V | \neg S) P(\neg S)
\]</span></p>
<p><span class="math display">\[
= (0.30 \times 0.40) + (0.70 \times 0.60) = 0.12 + 0.42 = 0.54.
\]</span></p>
</li>
<li>
<p>La probabilità che uno studente abbia <strong>alto stress</strong> sapendo che ha una soddisfazione elevata si calcola utilizzando la formula della probabilità condizionata:</p>
<p><span class="math display">\[
P(S | V) = \frac{P(S \cap V)}{P(V)} = \frac{0.12}{0.54} \approx 0.22.
\]</span></p>
</li>
</ol>
<p><strong>Esercizio 2: Studio del Paradosso di Simpson</strong></p>
<ol type="1">
<li>
<span class="math inline">\(P(E | A) = \frac{30}{40} = 0.75\)</span>, <span class="math inline">\(P(E | B) = \frac{20}{60} = 0.33\)</span>
</li>
<li><span class="math inline">\(P(E) = P(E | A) P(A) + P(E | B) P(B) = (0.75 \times 0.40) + (0.33 \times 0.60) = 0.30 + 0.198 = 0.498\)</span></li>
<li>Se i tassi di successo aggregati mostrano una relazione invertita, il Paradosso di Simpson si manifesta.</li>
</ol>
<p><strong>Esercizio 3: Il Problema di Monty Hall</strong></p>
<ol type="1">
<li><span class="math inline">\(P(V | S) = \frac{1}{3}\)</span></li>
<li><span class="math inline">\(P(V | C) = \frac{2}{3}\)</span></li>
<li>Cambiare porta aumenta le probabilità di vincita da <span class="math inline">\(1/3\)</span> a <span class="math inline">\(2/3\)</span>, quindi conviene sempre cambiare.</li>
</ol>
<p><strong>Esercizio 4: Teorema della Probabilità Totale</strong></p>
<p><span class="math inline">\(P(L) = (0.70 \times 0.40) + (0.60 \times 0.35) + (0.80 \times 0.25) = 0.28 + 0.21 + 0.20 = 0.69\)</span></p>
<p><strong>Esercizio 5: Urne e Palline</strong></p>
<ol type="1">
<li><span class="math inline">\(P(R_1 \cap R_2) = (5/12) \times (5/12) = 25/144\)</span></li>
<li><span class="math inline">\(1 - P(R_1 \cap R_2) = 1 - 25/144 = 119/144\)</span></li>
<li><span class="math inline">\(P(R_2 | B_1) = 5/12\)</span></li>
</ol>
</div>
</div>
</div>
</section><section id="informazioni-sullambiente-di-sviluppo" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="informazioni-sullambiente-di-sviluppo">Informazioni sull’Ambiente di Sviluppo</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; R version 4.4.2 (2024-10-31)</span></span>
<span><span class="co">#&gt; Platform: aarch64-apple-darwin20</span></span>
<span><span class="co">#&gt; Running under: macOS Sequoia 15.3.1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Matrix products: default</span></span>
<span><span class="co">#&gt; BLAS:   /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRblas.0.dylib </span></span>
<span><span class="co">#&gt; LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; locale:</span></span>
<span><span class="co">#&gt; [1] C/UTF-8/C/C/C/C</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; time zone: Europe/Rome</span></span>
<span><span class="co">#&gt; tzcode source: internal</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; attached base packages:</span></span>
<span><span class="co">#&gt; [1] stats     graphics  grDevices utils     datasets  methods   base     </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; other attached packages:</span></span>
<span><span class="co">#&gt;  [1] thematic_0.1.6   MetBrewer_0.2.0  ggokabeito_0.1.0 see_0.10.0      </span></span>
<span><span class="co">#&gt;  [5] gridExtra_2.3    patchwork_1.3.0  bayesplot_1.11.1 psych_2.4.12    </span></span>
<span><span class="co">#&gt;  [9] scales_1.3.0     markdown_1.13    knitr_1.49       lubridate_1.9.4 </span></span>
<span><span class="co">#&gt; [13] forcats_1.0.0    stringr_1.5.1    dplyr_1.1.4      purrr_1.0.4     </span></span>
<span><span class="co">#&gt; [17] readr_2.1.5      tidyr_1.3.1      tibble_3.2.1     ggplot2_3.5.1   </span></span>
<span><span class="co">#&gt; [21] tidyverse_2.0.0  rio_1.2.3        here_1.0.1      </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; loaded via a namespace (and not attached):</span></span>
<span><span class="co">#&gt;  [1] generics_0.1.3    stringi_1.8.4     lattice_0.22-6    hms_1.1.3        </span></span>
<span><span class="co">#&gt;  [5] digest_0.6.37     magrittr_2.0.3    evaluate_1.0.3    grid_4.4.2       </span></span>
<span><span class="co">#&gt;  [9] timechange_0.3.0  fastmap_1.2.0     rprojroot_2.0.4   jsonlite_1.9.1   </span></span>
<span><span class="co">#&gt; [13] mnormt_2.1.1      cli_3.6.4         rlang_1.1.5       munsell_0.5.1    </span></span>
<span><span class="co">#&gt; [17] withr_3.0.2       tools_4.4.2       parallel_4.4.2    tzdb_0.4.0       </span></span>
<span><span class="co">#&gt; [21] colorspace_2.1-1  pacman_0.5.1      vctrs_0.6.5       R6_2.6.1         </span></span>
<span><span class="co">#&gt; [25] lifecycle_1.0.4   htmlwidgets_1.6.4 pkgconfig_2.0.3   pillar_1.10.1    </span></span>
<span><span class="co">#&gt; [29] gtable_0.3.6      glue_1.8.0        xfun_0.51         tidyselect_1.2.1 </span></span>
<span><span class="co">#&gt; [33] rstudioapi_0.17.1 farver_2.1.2      htmltools_0.5.8.1 nlme_3.1-167     </span></span>
<span><span class="co">#&gt; [37] rmarkdown_2.29    compiler_4.4.2</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="bibliografia" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="bibliografia">Bibliografia</h2>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-blitzstein2019introduction" class="csl-entry" role="listitem">
Blitzstein, J. K., &amp; Hwang, J. (2019). <em>Introduction to probability</em>. CRC Press.
</div>
<div id="ref-RadeletPierce1991" class="csl-entry" role="listitem">
Radelet, M. L., &amp; Pierce, G. L. (1991). Choosing Those Who Will Die: Race and the Death Penalty in Florida. <em>Florida Law Review</em>, <em>43</em>(1), 1–34.
</div>
<div id="ref-schervish2014probability" class="csl-entry" role="listitem">
Schervish, M. J., &amp; DeGroot, M. H. (2014). <em>Probability and statistics</em> (Vol. 563). Pearson Education London, UK:
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiato!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiato!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/ccaudek\.github\.io\/psicometria-r\/intro\.html");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
          // default icon
          link.classList.add("external");
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../../chapters/probability/04_sigma-algebra.html" class="pagination-link" aria-label="Dal Discreto al Continuo: la $\sigma$-algebra">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Dal Discreto al Continuo: la <span class="math inline">\(\sigma\)</span>-algebra</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/probability/06_bayes_theorem.html" class="pagination-link" aria-label="Il teorema di Bayes">
        <span class="nav-page-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Il teorema di Bayes</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>Psicometria</strong> è una risorsa didattica creata per il corso di Scienze e Tecniche Psicologiche dell’Università degli Studi di Firenze.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ccaudek/psicometria-r/blob/main/chapters/probability/05_conditional_prob.qmd" class="toc-action"><i class="bi bi-github"></i>Mostra il codice</a></li><li><a href="https://github.com/ccaudek/psicometria-r/issues/new" class="toc-action"><i class="bi empty"></i>Segnala un problema</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Realizzato con <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>


</body></html>