# Introduzione {.unnumbered}

Questa sezione della dispensa introduce la teoria della probabilità, una componente essenziale per la ricerca scientifica. Nell'ambito della scienza, l'inferenza induttiva è di fondamentale importanza, e la probabilità svolge un ruolo cruciale in questo processo. Sebbene non possiamo ottenere una certezza assoluta riguardo alla veridicità di un'ipotesi o teoria, possiamo assegnare loro un grado di certezza probabilistica. L'approccio bayesiano utilizza la probabilità per quantificare il grado di fiducia che possiamo attribuire a una determinata proposizione.

L'inferenza statistica bayesiana mira a quantificare la fiducia nell'ipotesi $H$ dopo aver osservato un dato di evidenza $O$. Per affrontare adeguatamente l'inferenza statistica bayesiana, è quindi essenziale avere una solida comprensione della teoria delle probabilità, almeno nei suoi concetti fondamentali.

In questa sezione esamineremo le definizioni di probabilità, la probabilità condizionale e il teorema di Bayes. Approfondiremo inoltre le proprietà delle variabili casuali e le principali distribuzioni di massa e densità di probabilità. Concluderemo presentando la funzione di verosimiglianza, un concetto fondamentale sia nell'inferenza bayesiana sia nell'inferenza frequentista.
