# Introduzione {.unnumbered}

In questa sezione della dispensa, esamineremo l'inferenza bayesiana applicata a modelli statistici in cui si stima un unico parametro scalare, ovvero quando l'estimando $\theta$ è unidimensionale.  

In particolare, considereremo quattro modelli fondamentali e ampiamente utilizzati: il modello binomiale, il modello normale, il modello di Poisson e il modello esponenziale. Approfondiremo il processo di aggiornamento bayesiano analizzando due approcci principali per derivare la distribuzione a posteriori: l'approssimazione numerica tramite il metodo a griglia e l'impiego delle distribuzioni coniugate, in cui una specifica combinazione tra distribuzione a priori e verosimiglianza consente di ottenere la distribuzione a posteriori in forma analitica. Inoltre, esploreremo l'influenza della scelta della distribuzione a priori sulla distribuzione a posteriori e discuteremo le tecniche per sintetizzarla e interpretarla in modo efficace.  

Un aspetto cruciale dell'inferenza bayesiana, particolarmente rilevante nel contesto della crisi della replicabilità in psicologia, è la possibilità di formulare inferenze sulla distribuzione a posteriori dei parametri di interesse teorico senza dover ricorrere a decisioni binarie come "significativo" o "non significativo". Questo approccio promuove una modalità di analisi più sfumata e rigorosa, con l'obiettivo di stabilire un nuovo standard per la presentazione e l'interpretazione dei risultati, favorendo affermazioni più ponderate nelle ricerche empiriche [@McElreath_rethinking; @gelman1995bayesian].  

## Bibliografia {.unnumbered}

