project:
  type: book
  output-dir: docs

book:
  title: "Psicometria"
  subtitle: "Anno Accademico 2024/2025"
  reader-mode: true

  author: "Corrado Caudek"
  date: "last-modified"
  search: true
  repo-url: https://github.com/ccaudek/psicometria-r/
  repo-actions: [edit]
  site-url: https://ccaudek.github.io/psicometria-r/intro.html
  page-footer:
    left: |
      **Psicometria** è una risorsa didattica creata per il corso di Scienze e Tecniche Psicologiche dell'Università di Firenze.
    right: |
      Realizzato con <a href="https://quarto.org/">Quarto</a>.
  sidebar:
    collapse-level: 1
    pinned: true

  chapters:
    - index.qmd
    - prefazione.qmd

    - part: "Programmazione"
      chapters:
        - programmazione2024.qmd

    - part: "Fondamenti"
      chapters:
        - chapters/key_notions/introduction_key_notions.qmd
        - chapters/key_notions/00_uncertainty.qmd
        - chapters/key_notions/01_key_notions.qmd
        - chapters/key_notions/02_measurement.qmd
        - chapters/key_notions/03_data_analysis.qmd

    - part: "R"
      chapters:
        - chapters/R/introduction_r_lang.qmd
        - chapters/R/01_r_syntax.qmd
        - chapters/R/02_r_programming.qmd
        - chapters/R/03_r_packages.qmd
        - chapters/R/04_quarto.qmd
        - chapters/R/05_environment.qmd
        - chapters/R/06_ai.qmd

    - part: "EDA"
      chapters:
        - chapters/eda/introduction_eda.qmd
        - chapters/eda/01_project_structure.qmd
        - chapters/eda/02_data_cleaning.qmd
        - chapters/eda/03_dplyr.qmd
        - chapters/eda/04_exploring_qualitative_data.qmd
        - chapters/eda/05_exploring_numeric_data.qmd
        - chapters/eda/06_data_visualization.qmd
        - chapters/eda/07_loc_scale.qmd
        - chapters/eda/08_correlation.qmd
        - chapters/eda/09_causality.qmd
        - chapters/eda/10_estimand.qmd
        - chapters/eda/11_pixi.qmd

    - part: "Probabilità"
      chapters:
        - chapters/probability/introduction_probability.qmd
        - chapters/probability/01_intro_prob.qmd
        - chapters/probability/02_prob_spaces.qmd
        - chapters/probability/03_prob_on_general_spaces.qmd
        - chapters/probability/04_conditional_prob.qmd
        - chapters/probability/05_random_var.qmd
        - chapters/probability/06_expval_var.qmd
        - chapters/probability/07_bayes_theorem.qmd
        - chapters/probability/08_sampling_distr.qmd
        - chapters/probability/09_joint_prob.qmd
        - chapters/probability/10_density_func.qmd
        - chapters/probability/11_discr_rv_distr.qmd
        - chapters/probability/12_cont_rv_distr.qmd
        - chapters/probability/13_qq_plot.qmd
        - chapters/probability/14_likelihood.qmd
        - chapters/probability/15_simulation.qmd

    - part: "Inferenza"
      chapters:
        - chapters/bayesian_inference/introduction_bayes_inference.qmd
        - chapters/bayesian_inference/01_intro_bayes.qmd
        - chapters/bayesian_inference/02_bayesian_inference.qmd
        - chapters/bayesian_inference/03_subj_prop.qmd
        - chapters/bayesian_inference/04_grid_gauss.qmd
        - chapters/bayesian_inference/05_conjugate_families_1.qmd
        - chapters/bayesian_inference/06_conjugate_families_2.qmd
        - chapters/bayesian_inference/07_summary_posterior.qmd
        - chapters/bayesian_inference/08_balance_prior_post.qmd
        - chapters/bayesian_inference/09_gamma_poisson_model.qmd
        - chapters/bayesian_inference/10_gamma_exponential_model.qmd
        - chapters/bayesian_inference/11_post_pred_distr.qmd

    - part: "MCMC"
      chapters:
        - chapters/mcmc/introduction_mcmc.qmd
        - chapters/mcmc/01_metropolis.qmd
        - chapters/mcmc/02_ppl.qmd
        - chapters/mcmc/03_stan_language.qmd
        - chapters/mcmc/04_stan_summary_posterior.qmd
        # - chapters/mcmc/05_stan_diagnostics.ipynb
        # - chapters/mcmc/06_stan_prediction.ipynb
        # - chapters/mcmc/07_bayesian_workflow.ipynb
        - chapters/mcmc/08_stan_odds_ratio.qmd
        # - chapters/mcmc/09_stan_normal_normal.ipynb
        # - chapters/mcmc/10_stan_two_groups.ipynb
        - chapters/mcmc/11_stan_poisson_model_1.qmd
        # - chapters/mcmc/12_stan_poisson_model_2.ipynb
        # - chapters/mcmc/13_stan_exponential_model.ipynb
        # - chapters/mcmc/14_stan_gaussian_mixture.ipynb
        # - chapters/mcmc/15_stan_nuisance_parameters.ipynb
        # - chapters/mcmc/16_stan_hier_beta_binom.ipynb
        # - chapters/mcmc/17_stan_categorical.ipynb
        - chapters/mcmc/18_cmdstanr_intro.qmd
        # - chapters/mcmc/19_approximations.ipynb

    - part: "Regressione"
      chapters:
        - chapters/linear_models/introduction_linear_models.qmd
        # - chapters/linear_models/01_reglin_bayesian.ipynb
        # - chapters/linear_models/02_non_centered_param.ipynb
        # - chapters/linear_models/03_beauty_sex_power.ipynb
        # - chapters/linear_models/04_synt_sugar.ipynb
        # - chapters/linear_models/05_two_means.ipynb
        # - chapters/linear_models/06_prediction.ipynb
        # - chapters/linear_models/07_design.ipynb
        # - chapters/linear_models/08_linear_algebra.ipynb
        # - chapters/linear_models/09_stan_multreg.ipynb
        # - chapters/linear_models/10_hier_regr.ipynb
        # - chapters/linear_models/11_stan_mixed_models.ipynb
        # - chapters/linear_models/12_specification_error.ipynb
        # - chapters/linear_models/14_interactions.ipynb
        # - chapters/linear_models/16_missing.ipynb

    - part: "Causalità"
      chapters:
        - chapters/causal_inference/01_rct.ipynb
        # - chapters/causal_inference/02_ate_att_atu.ipynb
        # - chapters/causal_inference/03_endogenous_treatments.ipynb
        # - chapters/causal_inference/04_mult_reg_causal_inference.ipynb
        # - chapters/causal_inference/05_collider_bias.ipynb

    - part: "GLM"
      chapters:
        - chapters/glm/introduction_glm.qmd
        # - chapters/glm/01_robust_regr.ipynb
        # - chapters/glm/02_stan_binomial_regr.ipynb
        # - chapters/glm/03_stan_logistic_regr.ipynb
        # - chapters/glm/04_stan_poisson_regr.ipynb
        # - chapters/glm/05_simchon_2023.ipynb
        # - chapters/glm/06_stan_rct.ipynb
        # - chapters/glm/07_stan_mediation.ipynb
        # - chapters/glm/08_uses_and_abuses.ipynb

    - part: "Entropia"
      chapters:
        - chapters/entropy/introduction_entropy.qmd
        - chapters/entropy/01_entropy.qmd
        # - chapters/entropy/02_kl.ipynb
        # - chapters/entropy/03_model_comparison.ipynb
        # - chapters/entropy/04_loo.ipynb
        # - chapters/entropy/05_regularization.ipynb
        # - chapters/entropy/06_cognitive_modeling.ipynb
        # - chapters/entropy/07_inductive_inference.ipynb

    - part: "Dinamiche"
      chapters:
        - chapters/dynamic_models/introduction_dynamic_models.qmd
        # - chapters/dynamic_models/01_canoeing.ipynb
        # - chapters/dynamic_models/02_change_across_time.ipynb
        # - chapters/dynamic_models/03_rescorla_wagner.ipynb
        # - chapters/dynamic_models/04_affect.ipynb
        # - chapters/dynamic_models/05_sequential_learning.ipynb
        # - chapters/dynamic_models/07_bipolar_disorder.ipynb
        # - chapters/dynamic_models/08_haslbeck.ipynb

    - part: "Modelli cognitivi"
      chapters:
        - chapters/cognitive_models/introduction_cognitive_models.qmd
        # - chapters/cognitive_models/01_ddm.ipynb

    - part: "Frequentismo"
      chapters:
        - chapters/frequentist_inference/introduction_frequentist_inference.qmd
        - chapters/frequentist_inference/01_intro_frequentist.qmd
        - chapters/frequentist_inference/02_conf_interv.qmd
        - chapters/frequentist_inference/03_sample_size.qmd
        # - chapters/frequentist_inference/04_test_ipotesi.ipynb
        # - chapters/frequentist_inference/05_two_ind_samples.ipynb

    - part: "Crisi"
      chapters:
        - chapters/replication_crisis/introduction_replication_crisis.qmd
        - chapters/replication_crisis/01_crisis.qmd
        - chapters/replication_crisis/02_limits_stat_freq.qmd
        # - chapters/replication_crisis/03_effect_size.ipynb
        # - chapters/replication_crisis/04_s_m_errors.ipynb
        # - chapters/replication_crisis/05_p_values.ipynb
        - chapters/replication_crisis/06_changes.qmd
        - chapters/replication_crisis/07_integrity.qmd

    - part: "Epilogo"
      chapters:
        - chapters/epiloque/epiloque.qmd

    - part: "Appendice"
      chapters:
        - chapters/appendix/a02_shell.qmd
        - chapters/appendix/a10_math_symbols.qmd
        - chapters/appendix/a11_numbers.qmd
        - chapters/appendix/a12_sum_notation.qmd
        - chapters/appendix/a44_montecarlo.qmd

crossref:
  appendix-title: "Appendice"

title-prefix: ""
toc: true
toc-depth: 3

bibliography: ./references.bib
biblio-style: apalike
csl: apa.csl
link-citations: true

lang: it

format:
  html:
    theme:
      # light: [cosmo, theming/theme.scss]
      # dark: [cosmo, theming/theme-dark.scss]
      light: [zephyr, css/custom.scss]
      dark: [zephyr, css/dark.scss, css/custom.scss]
    syntax-definitions:
      - theming/stan.xml
    highlight-style:
      # light: theming/tango.theme
      # dark: theming/nord.theme
      a11y
    code-copy: true
    code-overflow: wrap
    # css: theming/quarto_styles.css
    toc: true
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

# format:
#   pdf:
#     latex-tinytex: false
#     block-headings: false
#     pdf-engine: "pdflatex"
#     latex-engine: "pdflatex"
#     latex-auto-install: true
#     documentclass: book
#     toc-title: "Table of Contents"
#     syntax-definitions:
#       - ./theming/stan.xml
#     highlight-style: tango
#     keep-tex: false
#     colorlinks: true

editor: source

website:
  cookie-consent:
    type: express
    style: headline
  google-analytics:
    tracking-id: "G-TP2WLBPMS6"
    anonymize-ip: true

execute: 
  freeze: auto
