project:
  type: book
  output-dir: docs

book:
  title: "Psicometria"
  subtitle: "Anno Accademico 2024/2025"
  reader-mode: true

  author: "Corrado Caudek"
  date: "last-modified"
  search: true
  repo-url: https://github.com/ccaudek/psicometria-r/
  repo-actions: [edit]
  site-url: https://ccaudek.github.io/psicometria-r/intro.html
  page-footer:
    left: |
      **Psicometria** è una risorsa didattica creata per il corso di Scienze e Tecniche Psicologiche dell'Università di Firenze.
    right: |
      Realizzato con <a href="https://quarto.org/">Quarto</a>.
  sidebar:
    collapse-level: 1
    pinned: true

  chapters:
    - index.qmd
    - prefazione.qmd

    - part: "Programmazione"
      chapters:
      - programmazione2024.qmd  

    - part: "Fondamenti"
      chapters:
        - chapters/key_notions/introduction_key_notions.md
        - chapters/key_notions/00_uncertainty.qmd
        - chapters/key_notions/01_key_notions.qmd
        - chapters/key_notions/02_measurement.qmd
        - chapters/key_notions/03_data_analysis.qmd

    - part: "EDA"
      chapters:
        - chapters/eda/introduction_eda.md
        - chapters/eda/01_project_structure.qmd
        - chapters/eda/02_data_cleaning.qmd
        # - chapters/eda/03_dplyr.qmd
        # - chapters/eda/04_exploring_qualitative_data.ipynb
        # - chapters/eda/05_exploring_numeric_data.ipynb
        # - chapters/eda/06_data_visualization.ipynb
        # - chapters/eda/07_loc_scale.ipynb
        # - chapters/eda/08_correlation.ipynb
        # - chapters/eda/09_causality.ipynb
        # - chapters/eda/10_estimand.ipynb

crossref:
  appendix-title: "Appendice"

toc: true
toc-depth: 5

bibliography: ./references.bib
biblio-style: apalike
csl: apa.csl
link-citations: true

lang: it

format:
  html:
    theme:
      - cosmo
      - r4ds.scss
    code-link: true
    table-class: table table-striped table-hover table-bordered

    author-meta: "Corrado Caudek"
    callout-appearance: simple
    # highlight-style: github

editor: source

website:
  cookie-consent:
    type: express
    style: headline
  google-analytics:
    tracking-id: "G-TP2WLBPMS6"
    anonymize-ip: true
