project:
  type: book
  output-dir: docs

book:
  title: "Psicometria"
  subtitle: "Anno Accademico 2024/2025"
  reader-mode: true

  author: "Corrado Caudek"
  date: "last-modified"
  search: true
  repo-url: https://github.com/ccaudek/psicometria-r/
  repo-actions: [edit]
  site-url: https://ccaudek.github.io/psicometria-r/intro.html
  page-footer:
    left: |
      **Psicometria** è una risorsa didattica creata per il corso di Scienze e Tecniche Psicologiche dell'Università di Firenze.
    right: |
      Realizzato con <a href="https://quarto.org/">Quarto</a>.
  sidebar:
    collapse-level: 1
    pinned: true

  chapters:
    - index.qmd
    - prefazione.qmd

    - part: "Programmazione"
      chapters:
      - programmazione2024.qmd  

    - part: "Fondamenti"
      chapters:
        - chapters/key_notions/introduction_key_notions.md
        - chapters/key_notions/00_uncertainty.qmd
        - chapters/key_notions/01_key_notions.qmd
        - chapters/key_notions/02_measurement.qmd
        - chapters/key_notions/03_data_analysis.qmd

    - part: "EDA"
      chapters:
        - chapters/eda/introduction_eda.md
        - chapters/eda/00_introduction_r.qmd
        - chapters/eda/01_project_structure.qmd
        - chapters/eda/02_data_cleaning.qmd
        - chapters/eda/03_dplyr.qmd
        - chapters/eda/04_exploring_qualitative_data.qmd
        - chapters/eda/05_exploring_numeric_data.qmd
        - chapters/eda/06_data_visualization.qmd
        - chapters/eda/07_loc_scale.qmd
        - chapters/eda/08_correlation.qmd
        - chapters/eda/09_causality.qmd
        - chapters/eda/10_estimand.qmd
        - chapters/eda/11_pixi.qmd

    - part: "MCMC"
      chapters:
        - chapters/mcmc/introduction_mcmc.md
        # - chapters/mcmc/01_metropolis.ipynb
        # - chapters/mcmc/02_ppl.ipynb
        # - chapters/mcmc/03_stan_language.ipynb
        - chapters/mcmc/04_stan_summary_posterior.qmd
        # - chapters/mcmc/05_stan_diagnostics.ipynb
        # - chapters/mcmc/06_stan_prediction.ipynb
        # - chapters/mcmc/07_bayesian_workflow.ipynb
        - chapters/mcmc/08_stan_odds_ratio.qmd
        # - chapters/mcmc/09_stan_normal_normal.ipynb
        # - chapters/mcmc/10_stan_two_groups.ipynb
        # - chapters/mcmc/11_stan_poisson_model_1.ipynb
        # - chapters/mcmc/12_stan_poisson_model_2.ipynb
        # - chapters/mcmc/13_stan_exponential_model.ipynb
        # - chapters/mcmc/14_stan_gaussian_mixture.ipynb
        # - chapters/mcmc/15_stan_nuisance_parameters.ipynb
        # - chapters/mcmc/16_stan_hier_beta_binom.ipynb
        # - chapters/mcmc/17_stan_categorical.ipynb
        # - chapters/mcmc/18_cmdstanr_intro.qmd
        # - chapters/mcmc/19_approximations.ipynb

crossref:
  appendix-title: "Appendice"

toc: true
toc-depth: 5

bibliography: ./references.bib
biblio-style: apalike
csl: apa.csl
link-citations: true

lang: it

format:
  html:
    theme:
      - cosmo
      - r4ds.scss
    code-link: true
    table-class: table table-striped table-hover table-bordered

    author-meta: "Corrado Caudek"
    callout-appearance: simple
    highlight-style: github

editor: source

website:
  cookie-consent:
    type: express
    style: headline
  google-analytics:
    tracking-id: "G-TP2WLBPMS6"
    anonymize-ip: true
