project:
  type: book
  output-dir: docs

book:
  title: "Psicometria"
  subtitle: "Anno Accademico 2024/2025"
  reader-mode: true
  google-analytics: G-QT5S3P9D31

  author: "Corrado Caudek"
  date: "last-modified"
  search: true
  repo-url: https://github.com/ccaudek/psicometria-r/
  repo-actions: [source, issue]
  site-url: https://ccaudek.github.io/psicometria-r/intro.html
  page-footer:
    left: |
      **Psicometria** è una risorsa didattica creata per il corso di Scienze e Tecniche Psicologiche dell'Università degli Studi di Firenze.
    right: |
      Realizzato con <a href="https://quarto.org/">Quarto</a>.
  sidebar:
    collapse-level: 1

  chapters:
    - index.qmd
    - prefazione.qmd

    - part: "Calendario"
      chapters:
        - programmazione2024.qmd

    - part: chapters/key_notions/introduction_key_notions.qmd
      chapters:
        # -------------- unit 1
        - chapters/key_notions/02_key_notions.qmd
        - chapters/key_notions/03_design.qmd # homework
        # -------------- unit 2
        - chapters/key_notions/04_measurement.qmd
        - chapters/key_notions/05_data_analysis.qmd

    - part: chapters/R/introduction_r_lang.qmd
      chapters:
        # -------------- unit 3
        - chapters/R/01_r_syntax.qmd
        - chapters/R/02_utility_functions.qmd
        - chapters/R/03_r_programming.qmd
        - chapters/R/04_r_packages.qmd
        # -------------- unit 4
        - chapters/R/05_dplyr.qmd
        - chapters/R/06_quarto.qmd
        - chapters/R/07_environment.qmd
        - chapters/R/08_ai.qmd

    - part: chapters/eda/introduction_eda.qmd
      chapters:
        - chapters/eda/01_project_structure.qmd
        - chapters/eda/02_data_cleaning.qmd
        # -------------- unit 5
        - chapters/eda/04_exploring_qualitative_data.qmd
        - chapters/eda/05_exploring_numeric_data.qmd
        - chapters/eda/06_data_visualization.qmd
        # -------------- unit 6
        - chapters/eda/07_loc_scale.qmd
        - chapters/eda/07a_introduction_normal_distribution.qmd
        # -------------- unit 7
        - chapters/eda/08_correlation.qmd
        - chapters/eda/09_causality.qmd
        - chapters/eda/10_estimand.qmd
        - chapters/eda/11_outlier.qmd

    - part: chapters/probability/introduction_probability.qmd
      chapters:
        # -------------- unit 8
        - chapters/probability/01_intro_prob.qmd
        - chapters/probability/02_probability_models.qmd
        - chapters/probability/03_prob_spaces.qmd
        - chapters/probability/04_sigma-algebra.qmd
        # -------------- unit 9
        - chapters/probability/05_conditional_prob.qmd
        # -------------- unit 10
        - chapters/probability/06_bayes_theorem.qmd
        # -------------- unit 11
        - chapters/probability/07_random_var.qmd
        - chapters/probability/08_prob_distributions.qmd
        - chapters/probability/09_expval_var.qmd
        # -------------- unit 12
        - chapters/probability/10_sampling_distr.qmd
        # -------------- unit 13
        - chapters/probability/11_joint_prob.qmd
        # -------------- unit 14
        - chapters/probability/12_discr_rv_distr.qmd
        # -------------- unit 15
        - chapters/probability/13_cont_rv_distr.qmd
        - chapters/probability/14_gauss.qmd
        # -------------- unit 16
        - chapters/probability/15_likelihood.qmd
        - chapters/probability/16_simulation.qmd

    - part: "Inferenza"
      chapters:
        # -------------- unit 17
        - chapters/bayesian_inference/introduction_bayes_inference.qmd
        - chapters/bayesian_inference/01_uncertainty.qmd # homework
        - chapters/bayesian_inference/01_intro_bayes.qmd
        - chapters/bayesian_inference/02_statistical_models.qmd
        - chapters/bayesian_inference/03_bayesian_inference.qmd
        - chapters/bayesian_inference/04_subj_prop.qmd
        # -------------- unit 18
        - chapters/bayesian_inference/05_grid_gauss.qmd
        # -------------- unit 19
        - chapters/bayesian_inference/06_conjugate_families_1.qmd
        - chapters/bayesian_inference/07_conjugate_families_2.qmd
        # -------------- unit 20
        - chapters/bayesian_inference/08_summary_posterior.qmd
        - chapters/bayesian_inference/09_balance_prior_post.qmd
        - chapters/bayesian_inference/10_gamma_poisson_model.qmd
        - chapters/bayesian_inference/11_gamma_exponential_model.qmd
        - chapters/bayesian_inference/12_post_pred_distr.qmd

    - part: "MCMC"
      chapters:
        # -------------- unit 21
        - chapters/mcmc/introduction_mcmc.qmd
        - chapters/mcmc/01_metropolis.qmd
        - chapters/mcmc/02_ppl.qmd
        # - chapters/mcmc/03_stan_language.qmd # opzionale
        # - chapters/mcmc/04_stan_summary_posterior.qmd # opzionale
        # - chapters/mcmc/06_mcmc_prediction.qmd # opzionale
        - chapters/mcmc/07_bayesian_workflow.qmd
        # - chapters/mcmc/18_cmdstanr_intro.qmd # opzionale

    - part: "Regressione"
      chapters:
        # -------------- unit 22
        - chapters/linear_models/introduction_linear_models.qmd
        - chapters/linear_models/01_reglin_frequentist.qmd
        - chapters/linear_models/02_regr_toward_mean.qmd
          # -------------- unit 23
        - chapters/linear_models/03_reglin_bayes.qmd
        - chapters/linear_models/04_synt_sugar.qmd
        # -------------- unit 24
        - chapters/linear_models/05_one_mean.qmd
        - chapters/linear_models/06_prediction_stan.qmd 
        - chapters/linear_models/07_two_means.qmd

        # -------------- unit 25
        - chapters/linear_models/08_sample_size.qmd 
        - chapters/linear_models/09_anova_1via.qmd
        - chapters/linear_models/10_anova_2vie.qmd
        - chapters/linear_models/11_one_proportion.qmd
        - chapters/linear_models/12_two_proportions.qmd


    # - part: "Entropia"
      # chapters:
        # - chapters/entropy/introduction_entropy.qmd # opzionale
        # - chapters/entropy/01_entropy.qmd # opzionale
        # - chapters/entropy/02_kl.ipynb # opzionale
        # - chapters/entropy/03_model_comparison.ipynb # opzionale
        # - chapters/entropy/04_loo.ipynb # opzionale

    - part: "Frequentismo"
      chapters:
        # -------------- unit 26
        - chapters/frequentist_inference/introduction_frequentist_inference.qmd
        - chapters/frequentist_inference/01_intro_frequentist.qmd
        - chapters/frequentist_inference/02_conf_interv.qmd
        # -------------- unit 27
        - chapters/frequentist_inference/03_sample_size.qmd
        - chapters/frequentist_inference/04_test_ipotesi.qmd
        # -------------- unit 28
        - chapters/frequentist_inference/05_two_ind_samples.qmd

    - part: "Crisi"
      chapters:
        - chapters/replication_crisis/introduction_replication_crisis.qmd
        - chapters/replication_crisis/01_crisis.qmd
        - chapters/replication_crisis/02_limits_stat_freq.qmd
          # -------------- unit 29
        - chapters/replication_crisis/03_effect_size.qmd
        - chapters/replication_crisis/04_s_m_errors.qmd
        - chapters/replication_crisis/05_p_values.qmd
        - chapters/replication_crisis/06_changes.qmd
        - chapters/replication_crisis/07_piranha.qmd
        - chapters/replication_crisis/08_integrity.qmd

    - part: "Epilogo"
      chapters:
        - chapters/epiloque/epiloque.qmd

    - part: "Appendice"
      chapters:
        - chapters/appendix/a02_shell.qmd
        - chapters/appendix/a10_math_symbols.qmd
        - chapters/appendix/a11_numbers.qmd
        - chapters/appendix/a12_sum_notation.qmd
        - chapters/appendix/a13_sets.qmd
        - chapters/appendix/a14_combinatorics.qmd
        - chapters/appendix/a15_calculus.qmd
        - chapters/appendix/a50_lin_fun.qmd
        - chapters/appendix/a71_install_cmdstan.qmd

crossref:
  appendix-title: "Appendice"

title-prefix: ""
toc: true
toc-depth: 3

bibliography: ./references.bib
biblio-style: apalike
csl: apa.csl
link-citations: true

lang: it

format:
  html:
    theme: 
      light: [cosmo, style/custom.scss]
      dark: [darkly, style/custom.scss]

    reader-mode: true
    fig-align: center
    toc-location: right
    code-fold: false
    code-link: true
    engine: knitr
    author-meta: Corrado Caudek
    callout-appearance: simple

execute:
  freeze: auto  # Skip re-executing unchanged code chunks
  echo: true  # Display code in the output document
  warning: false  # Suppress warnings in output
  message: false  # Suppress messages in output
  fig.width: 6  # Set figure width (in inches)
  fig.asp: 0.618  # Set figure aspect ratio (golden ratio for aesthetics)
  fig.retina: 2  # High resolution for retina displays
  fig.align: "center"  # Center-align all figures
  fig.show: "hold"  # Group multiple figures from a chunk

website:
  cookie-consent:
    type: express
    style: headline
    anonymize-ip: true
