<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="it" xml:lang="it"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Corrado Caudek">
<title>71&nbsp; Confronto tra due proporzioni indipendenti – Psicometria</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/linear_models/13_poisson_model.html" rel="next">
<link href="../../chapters/linear_models/11_one_proportion.html" rel="prev">
<link href="../../style/gauss.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-51e9ba6732aa6bc0134376f05742e55b.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-520e231445e9edbb3e5f59e93d436564.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nessun risultato",
    "search-matching-documents-text": "documenti trovati",
    "search-copy-link-title": "Copiare il link nella ricerca",
    "search-hide-matches-text": "Nascondere i risultati aggiuntivi",
    "search-more-match-text": "ci sono altri risultati in questo documento",
    "search-more-matches-text": "ulteriori risultati in questo documento",
    "search-clear-button-title": "Pulire",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancellare",
    "search-submit-button-title": "Inviare",
    "search-label": "Ricerca"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-QT5S3P9D31"></script><script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-QT5S3P9D31', { 'anonymize_ip': true});
</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/linear_models/introduction_linear_models.html">Regressione</a></li><li class="breadcrumb-item"><a href="../../chapters/linear_models/12_two_proportions.html"><span class="chapter-number">71</span>&nbsp; <span class="chapter-title">Confronto tra due proporzioni indipendenti</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Ricerca" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Psicometria</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ccaudek/psicometria-r/" title="Eseguire il codice" class="quarto-navigation-tool px-1" aria-label="Eseguire il codice"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Attiva/disattiva la modalità lettore">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Ricerca"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Informazioni Generali</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../prefazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefazione</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/key_notions/introduction_key_notions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Fondamenti</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/key_notions/01_key_notions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Concetti chiave</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/key_notions/02_design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Campionamento, metodologia sperimentale e studi osservazionali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/key_notions/03_measurement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">La misurazione in psicologia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/key_notions/04_data_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">La riforma metodologica in psicologia: dalla crisi alla rivoluzione bayesiana</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/key_notions/05_cognitive_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modelli cognitivi</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/R/introduction_r_lang.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/R/01_r_syntax.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Un approccio moderno all’analisi dei dati</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/R/02_utility_functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Utility functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/R/03_r_programming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Programmazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/R/04_r_packages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Pacchetti</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/R/05_dplyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Introduzione a <code>dplyr</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/R/06_quarto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Quarto</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/R/07_environment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">L’ambiente di programmazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/R/08_ai.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Utilizzo di strumenti AI</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/eda/introduction_eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">EDA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/01_project_structure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Le fasi del progetto di analisi dei dati</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/02_data_cleaning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Flusso di lavoro per la pulizia dei dati</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/04_exploring_qualitative_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Esplorare i dati qualitativi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/05_exploring_numeric_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Esplorare i dati numerici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/06_data_visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Principi della visualizzazione dei dati</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/07_loc_scale.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Indicatori di tendenza centrale e variabilità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/07a_introduction_normal_distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Introduzione alla distribuzione normale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/08_correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Relazioni tra variabili</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/09_causality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Causalità dai dati osservazionali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/10_estimand.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Estimandi teorici e estimandi empirici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/11_outlier.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Outlier</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/probability/introduction_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Probabilità</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/01_intro_prob.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Interpretazione della probabilità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/02_probability_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Modelli probabilistici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/03_prob_spaces.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">La Probabilità come misura della certezza razionale: un’interpretazione Bayesiana</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/04_sigma-algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Dal Discreto al Continuo: la <span class="math inline">\(\sigma\)</span>-algebra</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/05_conditional_prob.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Probabilità condizionata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/06_bayes_theorem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Il teorema di Bayes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/07_random_var.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Variabili casuali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/08_prob_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Distribuzioni di massa e di densità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/09_expval_var.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Proprietà delle variabili casuali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/10_sampling_distr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Stime, stimatori e parametri</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/11a_joint_prob.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Probabilità congiunta</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/11b_cov_cor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Covarianza e correlazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/11c_joint_prob_cont.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Caso continuo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/12a_intro_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Introduzione alle distribuzioni di probabilità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/12_discr_rv_distr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Distribuzioni di v.c. discrete</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/13_cont_rv_distr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Distribuzioni di v.c. continue</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/14_gauss.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Assunzione di gaussianità e trasformazioni dei dati</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/15_likelihood.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">La verosimiglianza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/16_likelihood_gauss.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">La verosimiglianza gaussiana</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/17_likelihood_ratio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Il rapporto di verosimiglianze</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Inferenza</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/introduction_bayes_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/01_uncertainty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Abbracciare l’incertezza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/02_intro_bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">La quantificazione dell’incertezza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/03_statistical_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Modelli statistici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/04_bayesian_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Inferenza bayesiana</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/05_subj_prop.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Aggiornare le credenze su un parametro: dal prior alla posterior</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/07_conjugate_families_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Distribuzioni coniugate (1)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/08_conjugate_families_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Distribuzioni coniugate (2)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/09_summary_posterior.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Sintesi a posteriori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/10_balance_prior_post.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">L’influenza della distribuzione a priori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/11_gamma_poisson_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Modello coniugato Gamma-Poisson</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/12_gamma_exponential_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Modello gamma-esponenziale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/13_post_pred_distr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Distribuzione predittiva a posteriori</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">MCMC</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/introduction_mcmc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/01_metropolis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">L’algoritmo di Metropolis-Hastings</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/02_ppl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">Linguaggi di programmazione probabilistici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/07_bayesian_workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">Flusso di lavoro bayesiano</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Regressione</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/introduction_linear_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/01_reglin_frequentist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">La regressione lineare bivariata: un approccio frequentista</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/02_regr_toward_mean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">La regressione verso la media</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/03_reglin_bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title">Modello bayesiano di regressione lineare bivariata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/04_synt_sugar.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title">Zucchero sintattico</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/05_one_mean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">64</span>&nbsp; <span class="chapter-title">Inferenza bayesiana su una media</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/07_two_means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">65</span>&nbsp; <span class="chapter-title">Confronto tra le medie di due gruppi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/07a_effect_size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">66</span>&nbsp; <span class="chapter-title">Stima bayesiana della grandezza dell’effetto</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/08_sample_size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">67</span>&nbsp; <span class="chapter-title">Pianificazione della dimensione campionaria</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/09_anova_1via.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">68</span>&nbsp; <span class="chapter-title">ANOVA ad una via</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/10_anova_2vie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">69</span>&nbsp; <span class="chapter-title">ANOVA ad due vie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/11_one_proportion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">70</span>&nbsp; <span class="chapter-title">Inferenza sulle proporzioni</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/12_two_proportions.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">71</span>&nbsp; <span class="chapter-title">Confronto tra due proporzioni indipendenti</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/13_poisson_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">72</span>&nbsp; <span class="chapter-title">Modello di Poisson</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Frequentismo</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/introduction_frequentist_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/01_intro_frequentist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">73</span>&nbsp; <span class="chapter-title">Inferenza frequentista</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/01a_stime_parametri.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">74</span>&nbsp; <span class="chapter-title">Stime, stimatori e parametri</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/02_conf_interv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">75</span>&nbsp; <span class="chapter-title">Intervalli di fiducia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/03_sample_size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">76</span>&nbsp; <span class="chapter-title">La grandezza del campione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/04_test_ipotesi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">77</span>&nbsp; <span class="chapter-title">Significatività statistica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/05_two_ind_samples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">78</span>&nbsp; <span class="chapter-title">Test t di Student per campioni indipendenti</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">Crisi</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/introduction_replication_crisis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/01_crisis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">79</span>&nbsp; <span class="chapter-title">La crisi della replicazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/02_limits_stat_freq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">80</span>&nbsp; <span class="chapter-title">Limiti dell’inferenza frequentista</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/03_effect_size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">81</span>&nbsp; <span class="chapter-title">La grandezza dell’effetto</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/04_s_m_errors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">82</span>&nbsp; <span class="chapter-title">Errori di segno e errori di grandezza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/05_p_values.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">83</span>&nbsp; <span class="chapter-title">La fragilità del <em>p</em>-valore</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/06_changes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">84</span>&nbsp; <span class="chapter-title">Riforma</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/07_piranha.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">85</span>&nbsp; <span class="chapter-title">Il Problema del priming: sfide e paradossi nella psicologia sociale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/08_degrees_of_freedom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">86</span>&nbsp; <span class="chapter-title">I gradi di libertà del ricercatore</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/09_integrity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">87</span>&nbsp; <span class="chapter-title">Integrità della ricerca</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">Epilogo</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/epiloque/epiloque.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Considerazioni Conclusive</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendici</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a01_shell.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">La Shell</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a01a_files.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Cartelle e documenti</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a02_math_symbols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Simbologia di base</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a03_latex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Equazioni Matematiche in LaTeX</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a11_numbers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Numeri e intervalli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a12_sum_notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">Sommatorie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a13_sets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">G</span>&nbsp; <span class="chapter-title">Insiemi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a14_combinatorics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">H</span>&nbsp; <span class="chapter-title">Calcolo combinatorio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a15_calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">I</span>&nbsp; <span class="chapter-title">Per liberarvi dai terrori preliminari</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a47_first_order_markov.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">J</span>&nbsp; <span class="chapter-title">Catene di Markov</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a50_lin_fun.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">K</span>&nbsp; <span class="chapter-title">La funzione lineare</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a71_install_cmdstan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">L</span>&nbsp; <span class="chapter-title">Come installare CmdStan</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Indice</h2>
   
  <ul class="collapse">
<li><a href="#introduzione" id="toc-introduzione" class="nav-link active" data-scroll-target="#introduzione"><span class="header-section-number">71.1</span> Introduzione</a></li>
  <li><a href="#la-struttura-dei-dati" id="toc-la-struttura-dei-dati" class="nav-link" data-scroll-target="#la-struttura-dei-dati"><span class="header-section-number">71.2</span> La struttura dei dati</a></li>
  <li><a href="#un-modello-statistico-per-dati-binari" id="toc-un-modello-statistico-per-dati-binari" class="nav-link" data-scroll-target="#un-modello-statistico-per-dati-binari"><span class="header-section-number">71.3</span> Un modello statistico per dati binari</a></li>
  <li><a href="#il-modello-di-regressione-logistica" id="toc-il-modello-di-regressione-logistica" class="nav-link" data-scroll-target="#il-modello-di-regressione-logistica"><span class="header-section-number">71.4</span> Il modello di regressione logistica</a></li>
  <li><a href="#inferenza-sulle-proporzioni" id="toc-inferenza-sulle-proporzioni" class="nav-link" data-scroll-target="#inferenza-sulle-proporzioni"><span class="header-section-number">71.5</span> Inferenza sulle proporzioni</a></li>
  <li><a href="#approccio-frequentista" id="toc-approccio-frequentista" class="nav-link" data-scroll-target="#approccio-frequentista"><span class="header-section-number">71.6</span> Approccio Frequentista</a></li>
  <li><a href="#un-esempio-illustrativo" id="toc-un-esempio-illustrativo" class="nav-link" data-scroll-target="#un-esempio-illustrativo"><span class="header-section-number">71.7</span> Un esempio Illustrativo</a></li>
  <li><a href="#approccio-bayesiano" id="toc-approccio-bayesiano" class="nav-link" data-scroll-target="#approccio-bayesiano"><span class="header-section-number">71.8</span> Approccio Bayesiano</a></li>
  <li><a href="#riflessioni-conclusive" id="toc-riflessioni-conclusive" class="nav-link" data-scroll-target="#riflessioni-conclusive"><span class="header-section-number">71.9</span> Riflessioni Conclusive</a></li>
  <li><a href="#informazioni-sullambiente-di-sviluppo" id="toc-informazioni-sullambiente-di-sviluppo" class="nav-link" data-scroll-target="#informazioni-sullambiente-di-sviluppo">Informazioni sull’Ambiente di Sviluppo</a></li>
  <li><a href="#bibliografia" id="toc-bibliografia" class="nav-link" data-scroll-target="#bibliografia">Bibliografia</a></li>
  </ul><div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/ccaudek/psicometria-r/blob/main/chapters/linear_models/12_two_proportions.qmd" class="toc-action"><i class="bi bi-github"></i>Mostra il codice</a></li><li><a href="https://github.com/ccaudek/psicometria-r/issues/new" class="toc-action"><i class="bi empty"></i>Segnala un problema</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/linear_models/introduction_linear_models.html">Regressione</a></li><li class="breadcrumb-item"><a href="../../chapters/linear_models/12_two_proportions.html"><span class="chapter-number">71</span>&nbsp; <span class="chapter-title">Confronto tra due proporzioni indipendenti</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-linear-models-two-proportions" class="quarto-section-identifier"><span class="chapter-number">71</span>&nbsp; <span class="chapter-title">Confronto tra due proporzioni indipendenti</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
In questo capitolo imparerai a
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>condurre un confronto bayesiano tra le proporzioni di due gruppi indipendenti utilizzando la funzione <code>brm()</code> del pacchetto <strong>brms</strong>.</li>
</ul>
</div>
</div>
<div class="callout callout-style-simple callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Prerequisiti
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Leggere l’articolo “Children’s arithmetic skills do not transfer between applied and academic mathematics” <span class="citation" data-cites="banerjee2025children">(<a href="#ref-banerjee2025children" role="doc-biblioref">Banerjee et al., 2025</a>)</span>.</li>
</ul>
</div>
</div>
<div class="callout callout-style-simple callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Preparazione del Notebook
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org/reference/here.html">here</a></span><span class="op">(</span><span class="st">"code"</span>, <span class="st">"_common.R"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Load packages</span></span>
<span><span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/ns-load.html">requireNamespace</a></span><span class="op">(</span><span class="st">"pacman"</span><span class="op">)</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"pacman"</span><span class="op">)</span></span>
<span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">brms</span>, <span class="va">cmdstanr</span>, <span class="va">posterior</span>, <span class="va">brms</span>, <span class="va">bayestestR</span>, <span class="va">insight</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<section id="introduzione" class="level2" data-number="71.1"><h2 data-number="71.1" class="anchored" data-anchor-id="introduzione">
<span class="header-section-number">71.1</span> Introduzione</h2>
<p>Supponiamo di voler capire se <strong>due gruppi di persone hanno la stessa probabilità di “successo”</strong> in una certa attività. Per esempio, vogliamo sapere se due trattamenti diversi portano alla stessa percentuale di guarigione, oppure se studenti che seguono due metodi di studio differenti superano un esame con la stessa frequenza.</p>
<p>Quando il risultato per ogni persona è un <strong>valore binario</strong> — successo o insuccesso, sì o no, guarito o non guarito — possiamo usare un modello statistico chiamato <strong>regressione logistica</strong>.</p>
<p>In particolare, se i due gruppi sono indipendenti e distinti (cioè ogni persona appartiene a uno solo dei due gruppi), possiamo usare una versione semplice della regressione logistica con <strong>una sola variabile esplicativa binaria</strong> (una “dummy”).</p>
<p>Adottando un approccio <strong>bayesiano</strong>, possiamo:</p>
<ol type="1">
<li>
<strong>rendere esplicita l’incertezza</strong> sulle nostre ipotesi iniziali tramite le <em>distribuzioni a priori</em>;</li>
<li>
<strong>descrivere l’intera gamma di risultati plausibili</strong>, ottenendo una <em>distribuzione a posteriori</em> dei parametri invece di un singolo valore “stimato”.</li>
</ol></section><section id="la-struttura-dei-dati" class="level2" data-number="71.2"><h2 data-number="71.2" class="anchored" data-anchor-id="la-struttura-dei-dati">
<span class="header-section-number">71.2</span> La struttura dei dati</h2>
<p>Consideriamo i dati che raccogliamo:</p>
<ul>
<li><p>ogni partecipante è identificato da un indice <span class="math inline">\(i = 1, 2, \dots, N\)</span>;</p></li>
<li>
<p>per ciascuno osserviamo un esito binario:</p>
<p><span class="math display">\[
y_i =
  \begin{cases}
    1 &amp; \text{se c’è un successo},\\
    0 &amp; \text{se c’è un insuccesso}.
  \end{cases}
\]</span></p>
</li>
<li><p>ogni partecipante appartiene a <strong>uno e un solo gruppo</strong>. Chiamiamo <em>gruppo 0</em> il primo gruppo (ad esempio, il gruppo di controllo) e <em>gruppo 1</em> il secondo gruppo (ad esempio, il gruppo che riceve un trattamento sperimentale).</p></li>
</ul>
<p>Per rappresentare questa appartenenza al gruppo, definiamo una <strong>variabile indicatrice</strong>:</p>
<p><span class="math display">\[
D_i =
  \begin{cases}
    0 &amp; \text{se il partecipante è nel gruppo 0},\\
    1 &amp; \text{se il partecipante è nel gruppo 1}.
  \end{cases}
\]</span></p>
<p>Questa variabile ci permette di costruire un modello che distingue i due gruppi.</p>
</section><section id="un-modello-statistico-per-dati-binari" class="level2" data-number="71.3"><h2 data-number="71.3" class="anchored" data-anchor-id="un-modello-statistico-per-dati-binari">
<span class="header-section-number">71.3</span> Un modello statistico per dati binari</h2>
<p>Poiché il risultato <span class="math inline">\(y\_i\)</span> può essere solo 0 o 1, possiamo descriverlo con una <strong>distribuzione di Bernoulli</strong>, che rappresenta proprio questo tipo di variabili:</p>
<p><span class="math display">\[
y_i \sim \text{Bernoulli}(p_i),
\]</span></p>
<p>dove <span class="math inline">\(p\_i\)</span> è la probabilità che il partecipante <span class="math inline">\(i\)</span> ottenga un successo (cioè che <span class="math inline">\(y_i = 1\)</span>).</p>
<p>A questo punto potremmo pensare di modellare direttamente <span class="math inline">\(p_i\)</span> come una funzione di <span class="math inline">\(D_i\)</span>. Ma c’è un problema tecnico importante.</p>
<section id="perché-non-modelliamo-direttamente-la-probabilità-p_i" class="level3" data-number="71.3.1"><h3 data-number="71.3.1" class="anchored" data-anchor-id="perché-non-modelliamo-direttamente-la-probabilità-p_i">
<span class="header-section-number">71.3.1</span> Perché non modelliamo direttamente la probabilità <span class="math inline">\(p_i\)</span>?</h3>
<p>Le probabilità devono sempre stare tra 0 e 1. Ma se usassimo un <strong>modello lineare classico</strong> (come <span class="math inline">\(p\_i = \alpha + \gamma D_i\)</span>), potremmo ottenere dei valori fuori da questo intervallo — ad esempio, una “probabilità” negativa o maggiore di 1, che non ha senso.</p>
<p>Per evitare questo, si usa una <strong>trasformazione matematica</strong> chiamata <strong>logit</strong>, che ha due proprietà molto utili:</p>
<ul>
<li>accetta in ingresso solo valori tra 0 e 1 (cioè le probabilità),</li>
<li>restituisce un numero reale qualsiasi, da <span class="math inline">\(-\infty\)</span> a <span class="math inline">\(+\infty\)</span>.</li>
</ul>
<p>La trasformazione logit è definita così:</p>
<p><span class="math display">\[
\text{logit}(p_i) = \log\left(\frac{p_i}{1 - p_i}\right) .
\]</span></p>
<p>Questa quantità si chiama <strong>log-odds</strong> e rappresenta il logaritmo del rapporto tra la probabilità di successo e quella di insuccesso.</p>
<p>Esempio:</p>
<ul>
<li>se <span class="math inline">\(p_i = 0.5\)</span>, allora <span class="math inline">\(\text{logit}(p_i) = \log(1) = 0\)</span>;</li>
<li>se <span class="math inline">\(p_i = 0.8\)</span>, allora <span class="math inline">\(\text{logit}(p_i) = \log(4) \approx 1.39\)</span>;</li>
<li>se <span class="math inline">\(p_i = 0.2\)</span>, allora <span class="math inline">\(\text{logit}(p_i) = \log(0.25) \approx -1.39\)</span>.</li>
</ul>
<p>Grazie a questa trasformazione, possiamo costruire un modello lineare senza rischiare di ottenere valori fuori dall’intervallo [0,1].</p>
</section></section><section id="il-modello-di-regressione-logistica" class="level2" data-number="71.4"><h2 data-number="71.4" class="anchored" data-anchor-id="il-modello-di-regressione-logistica">
<span class="header-section-number">71.4</span> Il modello di regressione logistica</h2>
<p>Mettiamo insieme tutti i pezzi. Il nostro modello diventa:</p>
<p><span class="math display">\[
\begin{aligned}
y_i &amp;\sim \text{Bernoulli}(p_i), \\
\text{logit}(p_i) &amp;= \alpha + \gamma D_i.
\end{aligned}
\]</span></p>
<p>Vediamo cosa significano i due parametri del modello:</p>
<ul>
<li>
<p><strong><span class="math inline">\(\alpha\)</span></strong> è il log-odds di successo per il <em>gruppo 0</em> (quando <span class="math inline">\(D_i = 0\)</span>).</p>
<ul>
<li>
<p>La probabilità di successo corrispondente si ottiene con la funzione logistica:</p>
<p><span class="math display">\[
p_0 = \frac{e^{\alpha}}{1 + e^{\alpha}} = \text{logistic}(\alpha) .
\]</span></p>
</li>
</ul>
</li>
<li>
<p><strong><span class="math inline">\(\gamma\)</span></strong> rappresenta la <em>differenza</em> nei log-odds tra il gruppo 1 e il gruppo 0.</p>
<ul>
<li>
<p>Il log-odds nel gruppo 1 è quindi $+ $, e la probabilità è:</p>
<p><span class="math display">\[
p_1 = \frac{e^{\alpha + \gamma}}{1 + e^{\alpha + \gamma}} = \text{logistic}(\alpha + \gamma) .
\]</span></p>
</li>
</ul>
</li>
</ul>
<section id="interpretazione-pratica" class="level3" data-number="71.4.1"><h3 data-number="71.4.1" class="anchored" data-anchor-id="interpretazione-pratica">
<span class="header-section-number">71.4.1</span> Interpretazione pratica</h3>
<ul>
<li>Se <strong><span class="math inline">\(\gamma &gt; 0\)</span></strong>, il gruppo 1 ha una probabilità di successo <strong>più alta</strong> rispetto al gruppo 0.</li>
<li>Se <strong><span class="math inline">\(\gamma &lt; 0\)</span></strong>, il gruppo 1 ha una probabilità <strong>più bassa</strong>.</li>
<li>Se <strong><span class="math inline">\(\gamma = 0\)</span></strong>, i due gruppi hanno <strong>la stessa probabilità</strong> di successo.</li>
</ul></section><section id="vantaggi-dellapproccio-bayesiano" class="level3" data-number="71.4.2"><h3 data-number="71.4.2" class="anchored" data-anchor-id="vantaggi-dellapproccio-bayesiano">
<span class="header-section-number">71.4.2</span> Vantaggi dell’approccio bayesiano</h3>
<p>In un’analisi bayesiana, non ci limitiamo a stimare un singolo valore per <span class="math inline">\(\gamma\)</span>. Invece, otteniamo <strong>una distribuzione completa</strong> che rappresenta tutte le ipotesi plausibili sui valori di <span class="math inline">\(\gamma\)</span>, tenendo conto:</p>
<ul>
<li>della variabilità nei dati,</li>
<li>delle nostre ipotesi iniziali (le distribuzioni a priori),</li>
<li>e delle informazioni che emergono dai dati osservati.</li>
</ul>
<p>Questo ci permette di rispondere a domande come:</p>
<ul>
<li><em>Quanto è probabile che <span class="math inline">\(\gamma\)</span> sia maggiore di 0?</em></li>
<li><em>Qual è l’intervallo più credibile in cui può trovarsi <span class="math inline">\(\gamma\)</span> con il 95% di probabilità?</em></li>
<li><em>Qual è la probabilità che la differenza tra i gruppi sia sostanziale, non solo presente?</em></li>
</ul></section><section id="dai-logit-alle-probabilità" class="level3" data-number="71.4.3"><h3 data-number="71.4.3" class="anchored" data-anchor-id="dai-logit-alle-probabilità">
<span class="header-section-number">71.4.3</span> Dai Logit alle Probabilità</h3>
<p>Una volta stimati i coefficienti del modello di regressione logistica — in particolare, l’intercetta <span class="math inline">\(\beta\_0\)</span> e uno o più coefficienti <span class="math inline">\(\beta_j\)</span> associati ai predittori — questi si trovano sulla <strong>scala dei log-odds</strong> (cioè su scala logit). Per ottenere le <strong>probabilità previste</strong> per ciascuna combinazione di valori dei predittori, è sufficiente applicare la <strong>funzione logistica inversa</strong>, definita come:</p>
<p><span class="math display">\[
p = \text{logistic}(\eta) = \frac{1}{1 + e^{-\eta}},
\]</span></p>
<p>dove <span class="math inline">\(\eta = \beta_0 + \beta_1 x_1 + \dots + \beta_k x_k\)</span> è il valore del predittore lineare per una certa combinazione dei predittori. Ad esempio, se si ha solo una variabile binaria <span class="math inline">\(x\)</span> che vale 0 (gruppo di riferimento) o 1 (gruppo trattato), allora le probabilità nei due gruppi sono:</p>
<ul>
<li>gruppo di riferimento: <span class="math inline">\(p_0 = \frac{1}{1 + e^{-\beta_0}}\)</span>
</li>
<li>gruppo trattamento:    <span class="math inline">\(p_1 = \frac{1}{1 + e^{-(\beta\_0 + \beta_1)}}\)</span>
</li>
</ul>
<p>In questo modo, si può interpretare il modello non solo in termini di log-odds, ma anche come <strong>probabilità di successo</strong>, rendendo più intuitivo il significato pratico dei risultati.</p>
</section><section id="inferenza-bayesiana" class="level3" data-number="71.4.4"><h3 data-number="71.4.4" class="anchored" data-anchor-id="inferenza-bayesiana">
<span class="header-section-number">71.4.4</span> Inferenza bayesiana</h3>
<ol type="1">
<li>
<p><strong>Scelta delle prior</strong></p>
<ul>
<li>Un’opzione comune è usare prior debolmente informative, ad esempio <span class="math inline">\(\alpha\sim\mathcal N(0,\,2.5)\)</span> e <span class="math inline">\(\gamma\sim\mathcal N(0,\,2.5)\)</span>. Queste varianze larghe lasciano che i dati “parlino”, ma impediscono che le probabilità si avvicinino troppo a 0 o 1 senza evidenza.</li>
</ul>
</li>
<li>
<p><strong>Calcolo della distribuzione a posteriori</strong></p>
<ul>
<li>Si usa normalmente l’algoritmo MCMC (per es. No‑U‑Turn Sampler di Stan).</li>
<li>Otteniamo campioni <span class="math inline">\(\{\alpha^{(s)},\gamma^{(s)}\}_{s=1}^S\)</span>.</li>
</ul>
</li>
<li>
<p><strong>Quantità derivate di interesse</strong></p>
<ul>
<li>Probabilità nei due gruppi: <span class="math inline">\(p_0^{(s)}=\operatorname{logistic}(\alpha^{(s)})\)</span>, <span class="math inline">\(p_1^{(s)}=\operatorname{logistic}(\alpha^{(s)}+\gamma^{(s)})\)</span>.</li>
<li>
<strong>Differenza di probabilità</strong>: <span class="math inline">\(\Delta^{(s)} = p_1^{(s)}-p_0^{(s)}\)</span>. Mostra quanto, in media, il gruppo 1 supera (o non supera) il gruppo 0 in termini di proporzione.</li>
<li>
<strong>Rapporto di odds</strong>: <span class="math inline">\(\text{OR}^{(s)} = e^{\gamma^{(s)}}\)</span>. Se <span class="math inline">\(\text{OR}=2\)</span> significa che gli odds di successo nel gruppo 1 sono il doppio di quelli nel gruppo 0.</li>
</ul>
</li>
<li>
<p><strong>Sintesi dei risultati</strong></p>
<ul>
<li>Media (o mediana) a posteriori per <span class="math inline">\(p_0, p_1, \Delta, \text{OR}\)</span>.</li>
<li>Intervalli di credibilità al 95 %: tagliamo il 2.5 % di campioni in ciascuna coda.</li>
<li>Probabilità che <span class="math inline">\(\Delta&gt;0\)</span> o che <span class="math inline">\(\text{OR}&gt;1\)</span>: basta contare la frazione di campioni corrispondenti.</li>
</ul>
</li>
</ol></section><section id="perché-tutto-questo-funziona" class="level3" data-number="71.4.5"><h3 data-number="71.4.5" class="anchored" data-anchor-id="perché-tutto-questo-funziona">
<span class="header-section-number">71.4.5</span> Perché tutto questo funziona?</h3>
<ul>
<li><p><strong>Il logit “apre” l’intervallo (0, 1)</strong> rendendo possibile usare un modello lineare.</p></li>
<li>
<p><strong>La regressione logistica</strong> con una dummy è l’esatto equivalente, in termini di parametri, al test bayesiano sulle due proporzioni, ma:</p>
<ul>
<li>consente estensioni (più covariate, effetti casuali, interazioni);</li>
<li>permette di riportare risultati direttamente interpretabili (differenza di probabilità, OR, predicted probabilities).</li>
</ul>
</li>
<li><p><strong>L’approccio bayesiano</strong> produce output che si leggono come “date le nostre ipotesi preliminari e i dati, la plausibilità che la vera differenza di probabilità stia in questo intervallo è 95 %”, concetto spesso più intuitivo del valore‑p.</p></li>
</ul></section></section><section id="inferenza-sulle-proporzioni" class="level2" data-number="71.5"><h2 data-number="71.5" class="anchored" data-anchor-id="inferenza-sulle-proporzioni">
<span class="header-section-number">71.5</span> Inferenza sulle proporzioni</h2>
<p>Il confronto tra le proporzioni di due gruppi indipendenti può essere affrontato sia con un approccio frequentista, basato sulla distribuzione campionaria, sia con un approccio bayesiano. Vediamo i due approcci in dettaglio.</p>
</section><section id="approccio-frequentista" class="level2" data-number="71.6"><h2 data-number="71.6" class="anchored" data-anchor-id="approccio-frequentista">
<span class="header-section-number">71.6</span> Approccio Frequentista</h2>
<p>Quando vogliamo confrontare le probabilità di successo in due gruppi distinti, possiamo analizzare la <strong>differenza tra le proporzioni di successo osservate</strong>. L’approccio frequentista affronta il problema studiando la <strong>distribuzione campionaria</strong> di questa differenza.</p>
<section id="modello-di-riferimento" class="level3" data-number="71.6.1"><h3 data-number="71.6.1" class="anchored" data-anchor-id="modello-di-riferimento">
<span class="header-section-number">71.6.1</span> Modello di riferimento</h3>
<p>Supponiamo di avere due gruppi indipendenti. In ciascun gruppo osserviamo esiti binari, come “successo” (1) o “insuccesso” (0), per ogni partecipante. Formalmente:</p>
<p><span class="math display">\[
Y_1 \sim \text{Bernoulli}(p_1), \quad Y_2 \sim \text{Bernoulli}(p_2),
\]</span></p>
<p>dove <span class="math inline">\(p_1\)</span> e <span class="math inline">\(p_2\)</span> sono le probabilità di successo nella popolazione del primo e del secondo gruppo, rispettivamente.</p>
</section><section id="obiettivo-dellinferenza" class="level3" data-number="71.6.2"><h3 data-number="71.6.2" class="anchored" data-anchor-id="obiettivo-dellinferenza">
<span class="header-section-number">71.6.2</span> Obiettivo dell’inferenza</h3>
<p>Siamo interessati a stimare e fare inferenza sulla <strong>differenza tra le due proporzioni</strong>:</p>
<p><span class="math display">\[
\Delta = p_1 - p_2.
\]</span></p>
<p>Poiché non conosciamo <span class="math inline">\(p_1\)</span> e <span class="math inline">\(p_2\)</span>, li stimiamo usando le proporzioni campionarie:</p>
<p><span class="math display">\[
\hat{p}_1 = \frac{X_1}{n_1}, \quad \hat{p}_2 = \frac{X_2}{n_2}, \quad \text{e dunque} \quad \hat{\Delta} = \hat{p}_1 - \hat{p}_2.
\]</span></p>
</section><section id="proprietà-della-distribuzione-campionaria" class="level3" data-number="71.6.3"><h3 data-number="71.6.3" class="anchored" data-anchor-id="proprietà-della-distribuzione-campionaria">
<span class="header-section-number">71.6.3</span> Proprietà della distribuzione campionaria</h3>
<p>Per capire se la differenza osservata tra <span class="math inline">\(\hat{p}_1\)</span> e <span class="math inline">\(\hat{p}_2\)</span> è attribuibile al caso oppure riflette una differenza reale tra i gruppi, analizziamo la distribuzione campionaria di <span class="math inline">\(\hat{\Delta}\)</span>.</p>
<section id="valore-atteso" class="level4" data-number="71.6.3.1"><h4 data-number="71.6.3.1" class="anchored" data-anchor-id="valore-atteso">
<span class="header-section-number">71.6.3.1</span> Valore atteso</h4>
<p>Il valore atteso della differenza stimata è:</p>
<p><span class="math display">\[
E(\hat{p}_1 - \hat{p}_2) = p_1 - p_2,
\]</span></p>
<p>cioè, in media, la stima è corretta (è uno stimatore non distorto).</p>
<div class="callout callout-style-simple callout-important no-icon callout-titled" title="Dimostrazione">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Dimostrazione
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Supponiamo di voler confrontare le proporzioni di successo in due popolazioni distinte. Sia:</p>
<ul>
<li>
<span class="math inline">\(X_1\)</span> il numero di successi osservati in un campione di dimensione <span class="math inline">\(n_1\)</span> estratto dalla <strong>prima popolazione</strong>, in cui la proporzione di successo è <span class="math inline">\(p_1\)</span>;</li>
<li>
<span class="math inline">\(X_2\)</span> il numero di successi osservati in un campione di dimensione <span class="math inline">\(n_2\)</span> estratto dalla <strong>seconda popolazione</strong>, con proporzione di successo <span class="math inline">\(p_2\)</span>.</li>
</ul>
<p>Assumiamo che i due campioni siano <strong>indipendenti</strong>.</p>
<p>Le proporzioni campionarie, che stimano rispettivamente <span class="math inline">\(p_1\)</span> e <span class="math inline">\(p_2\)</span>, sono definite come:</p>
<p><span class="math display">\[
\hat{p}_1 = \frac{X_1}{n_1}, \quad \hat{p}_2 = \frac{X_2}{n_2}.
\]</span></p>
<p>Poiché <span class="math inline">\(X_1 \sim \text{Binomiale}(n_1, p_1)\)</span> e <span class="math inline">\(X_2 \sim \text{Binomiale}(n_2, p_2)\)</span>, possiamo determinare i valori attesi di <span class="math inline">\(X_1\)</span> e <span class="math inline">\(X_2\)</span> ricordando che per una variabile binomiale <span class="math inline">\(X \sim \text{Bin}(n, p)\)</span>, il valore atteso è:</p>
<p><span class="math display">\[
\mathbb{E}(X) = n p.
\]</span></p>
<p>Una variabile binomiale può essere vista come la somma di <span class="math inline">\(n\)</span> variabili di Bernoulli indipendenti:</p>
<p><span class="math display">\[
X = X_1 + X_2 + \dots + X_n, \quad \text{con } X_i \sim \text{Bernoulli}(p).
\]</span></p>
<p>Per la <strong>linearità del valore atteso</strong>:</p>
<p><span class="math display">\[
\mathbb{E}(X) = \sum_{i=1}^n \mathbb{E}(X_i) = \sum_{i=1}^n p = n p.
\]</span></p>
<p>Applicando questa proprietà ai nostri due campioni:</p>
<p><span class="math display">\[
\mathbb{E}(X_1) = n_1 p_1, \quad \mathbb{E}(X_2) = n_2 p_2.
\]</span></p>
<p>Per la prima proporzione campionaria:</p>
<p><span class="math display">\[
\mathbb{E}(\hat{p}_1) = \mathbb{E}\left( \frac{X_1}{n_1} \right) = \frac{1}{n_1} \mathbb{E}(X_1) = \frac{n_1 p_1}{n_1} = p_1.
\]</span></p>
<p>Analogamente, per la seconda:</p>
<p><span class="math display">\[
\mathbb{E}(\hat{p}_2) = \mathbb{E}\left( \frac{X_2}{n_2} \right) = \frac{1}{n_2} \mathbb{E}(X_2) = \frac{n_2 p_2}{n_2} = p_2.
\]</span></p>
<p>Dunque, sia <span class="math inline">\(\hat{p}_1\)</span> che <span class="math inline">\(\hat{p}_2\)</span> sono <strong>stimatori non distorti</strong> delle rispettive proporzioni della popolazione.</p>
<p>Infine, calcoliamo il valore atteso della differenza tra le due proporzioni campionarie:</p>
<p><span class="math display">\[
\mathbb{E}(\hat{p}_1 - \hat{p}_2) = \mathbb{E}(\hat{p}_1) - \mathbb{E}(\hat{p}_2) = p_1 - p_2.
\]</span></p>
<p>In conclusione, la differenza tra le proporzioni campionarie, <span class="math inline">\(\hat{p}_1 - \hat{p}_2\)</span>, è uno <strong>stimatore non distorto</strong> della differenza tra le vere proporzioni, <span class="math inline">\(p_1 - p_2\)</span>.</p>
</div>
</div>
</div>
</section><section id="varianza" class="level4" data-number="71.6.3.2"><h4 data-number="71.6.3.2" class="anchored" data-anchor-id="varianza">
<span class="header-section-number">71.6.3.2</span> Varianza</h4>
<p>Assumendo che i campioni siano indipendenti, la varianza della differenza stimata è la somma delle varianze delle due proporzioni:</p>
<p><span class="math display">\[
\operatorname{Var}(\hat{p}_1 - \hat{p}_2) = \frac{p_1(1 - p_1)}{n_1} + \frac{p_2(1 - p_2)}{n_2}.
\]</span></p>
<p>Questa formula ci dice quanto può variare la differenza stimata da un campione all’altro.</p>
<p>Poiché <span class="math inline">\(p_1\)</span> e <span class="math inline">\(p_2\)</span> sono ignoti, nella pratica li sostituiamo con le proporzioni osservate <span class="math inline">\(\hat{p}_1\)</span> e <span class="math inline">\(\hat{p}_2\)</span> per stimare la varianza.</p>
<div class="callout callout-style-simple callout-important no-icon callout-titled" title="Dimostrazione">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Dimostrazione
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Consideriamo due campioni indipendenti:</p>
<ul>
<li><p>Il primo campione è estratto da una popolazione in cui la <strong>proporzione di successi</strong> è <span class="math inline">\(p_1\)</span>. Il numero di successi osservati è una variabile casuale <span class="math inline">\(X_1 \sim \text{Binomiale}(n_1, p_1)\)</span>.</p></li>
<li><p>Il secondo campione proviene da una popolazione con proporzione di successi <span class="math inline">\(p_2\)</span>, e il numero di successi osservati è <span class="math inline">\(X_2 \sim \text{Binomiale}(n_2, p_2)\)</span>.</p></li>
</ul>
<p>Definiamo le <strong>proporzioni campionarie</strong> (ovvero gli stimatori di <span class="math inline">\(p_1\)</span> e <span class="math inline">\(p_2\)</span>) come:</p>
<p><span class="math display">\[
\hat{p}_1 = \frac{X_1}{n_1}, \qquad \hat{p}_2 = \frac{X_2}{n_2}.
\]</span></p>
<p>Vogliamo calcolare la <strong>varianza della differenza tra le proporzioni campionarie</strong>:</p>
<p><span class="math display">\[
\operatorname{Var}(\hat{p}_1 - \hat{p}_2).
\]</span></p>
<p>Se <span class="math inline">\(Y\)</span> e <span class="math inline">\(Z\)</span> sono variabili casuali <strong>indipendenti</strong>, allora:</p>
<p><span class="math display">\[
\operatorname{Var}(Y - Z) = \operatorname{Var}(Y) + \operatorname{Var}(Z).
\]</span></p>
<p>Nel nostro caso, <span class="math inline">\(\hat{p}_1\)</span> e <span class="math inline">\(\hat{p}_2\)</span> derivano da due campioni indipendenti, quindi possiamo applicare questa proprietà:</p>
<p><span class="math display">\[
\operatorname{Var}(\hat{p}_1 - \hat{p}_2) = \operatorname{Var}(\hat{p}_1) + \operatorname{Var}(\hat{p}_2).
\]</span></p>
<p>Per calcolare <span class="math inline">\(\operatorname{Var}(\hat{p})\)</span>, partiamo dalla definizione di <span class="math inline">\(\hat{p} = X/n\)</span>, dove <span class="math inline">\(X \sim \text{Binomiale}(n, p)\)</span>.</p>
<p>È noto che la <strong>varianza di una binomiale</strong> (si veda <a href="../probability/12_discr_rv_distr.html" class="quarto-xref"><span>Capitolo 39</span></a>) è:</p>
<p><span class="math display">\[
\operatorname{Var}(X) = n p (1 - p).
\]</span></p>
<p>Ora applichiamo la <strong>proprietà di omogeneità della varianza</strong>: se <span class="math inline">\(Y = cX\)</span>, allora <span class="math inline">\(\operatorname{Var}(Y) = c^2 \operatorname{Var}(X)\)</span>. Quindi:</p>
<p><span class="math display">\[
\operatorname{Var}(\hat{p}) = \operatorname{Var}\left(\frac{X}{n}\right) = \frac{1}{n^2} \cdot \operatorname{Var}(X) = \frac{1}{n^2} \cdot n p (1 - p) = \frac{p(1 - p)}{n}.
\]</span></p>
<p>Applichiamo questa formula a ciascun campione:</p>
<p><span class="math display">\[
\operatorname{Var}(\hat{p}_1) = \frac{p_1 (1 - p_1)}{n_1}, \qquad \operatorname{Var}(\hat{p}_2) = \frac{p_2 (1 - p_2)}{n_2}.
\]</span></p>
<p>Sostituendo i valori ottenuti:</p>
<p><span class="math display">\[
\operatorname{Var}(\hat{p}_1 - \hat{p}_2) = \frac{p_1 (1 - p_1)}{n_1} + \frac{p_2 (1 - p_2)}{n_2}.
\]</span></p>
<p>Questa espressione rappresenta la <strong>varianza teorica</strong> della differenza tra le proporzioni campionarie, assumendo che i veri valori di <span class="math inline">\(p_1\)</span> e <span class="math inline">\(p_2\)</span> siano noti.</p>
<p>Nella realtà, i parametri <span class="math inline">\(p_1\)</span> e <span class="math inline">\(p_2\)</span> <strong>non sono noti</strong>, e quindi dobbiamo usare le <strong>stime campionarie</strong> al loro posto. Otteniamo così uno <strong>stimatore della varianza</strong>:</p>
<p><span class="math display">\[
\widehat{\operatorname{Var}}(\hat{p}_1 - \hat{p}_2) = \frac{\hat{p}_1 (1 - \hat{p}_1)}{n_1} + \frac{\hat{p}_2 (1 - \hat{p}_2)}{n_2}.
\]</span></p>
</div>
</div>
</div>
</section></section><section id="approssimazione-normale" class="level3" data-number="71.6.4"><h3 data-number="71.6.4" class="anchored" data-anchor-id="approssimazione-normale">
<span class="header-section-number">71.6.4</span> Approssimazione normale</h3>
<p>Quando i campioni sono sufficientemente grandi, possiamo applicare il <strong>Teorema del Limite Centrale</strong>, che ci assicura che la distribuzione della differenza <span class="math inline">\(\hat{p}_1 - \hat{p}_2\)</span> si avvicina a una distribuzione normale:</p>
<p><span id="eq-distr-norm-prop-diff"><span class="math display">\[
\hat{p}_1 - \hat{p}_2 \sim \mathcal{N}\left(p_1 - p_2,\ \sqrt{\frac{p_1(1 - p_1)}{n_1} + \frac{p_2(1 - p_2)}{n_2}}\right).
\tag{71.1}\]</span></span></p>
<p>Nell’approccio frequentista, questa approssimazione è alla base della costruzione di:</p>
<ul>
<li>
<strong>intervalli di confidenza</strong> per <span class="math inline">\(p_1 - p_2\)</span>,</li>
<li>
<strong>test di ipotesi</strong> per verificare se la differenza tra le proporzioni è nulla.</li>
</ul></section><section id="test-dellipotesi-nulla" class="level3" data-number="71.6.5"><h3 data-number="71.6.5" class="anchored" data-anchor-id="test-dellipotesi-nulla">
<span class="header-section-number">71.6.5</span> Test dell’ipotesi nulla</h3>
<p>La formula <a href="#eq-distr-norm-prop-diff" class="quarto-xref">Equazione&nbsp;<span>71.1</span></a> descrive la la <strong>distribuzione asintotica</strong> della differenza tra due proporzioni <strong>senza assumere</strong> che <span class="math inline">\(p_1 = p_2\)</span>. Si usa tipicamente per:</p>
<ul>
<li>costruire <strong>intervalli di confidenza</strong> per <span class="math inline">\(p_1 - p_2\)</span>,</li>
<li>effettuare <strong>test di ipotesi bilaterali</strong>, quando <strong>non</strong> si assume che le due proporzioni siano uguali sotto l’ipotesi nulla.</li>
</ul>
<p>In alternativa, la formula</p>
<p><span id="eq-se-prop-pooled"><span class="math display">\[
\text{SE}_{\text{pooled}} = \sqrt{p_{\text{pool}}(1 - p_{\text{pool}})\left(\frac{1}{n_1} + \frac{1}{n_2}\right)}
\tag{71.2}\]</span></span></p>
<p>si usa <strong>solo per testare l’ipotesi nulla <span class="math inline">\(H_0: p_1 = p_2\)</span></strong>, ovvero sotto l’assunzione che <span class="math inline">\(p_1 = p_2 = p\)</span>, si stima questo valore comune con la proporzione combinata (pooled):</p>
<p><span class="math display">\[
\hat{p}_{\text{pool}} = \frac{x_1 + x_2}{n_1 + n_2}
\]</span></p>
<p>e si calcola il test z usando questa stima comune.</p>
</section><section id="quale-formula-usare-e-quando" class="level3" data-number="71.6.6"><h3 data-number="71.6.6" class="anchored" data-anchor-id="quale-formula-usare-e-quando">
<span class="header-section-number">71.6.6</span> Quale formula usare e quando?</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 43%">
<col style="width: 56%">
</colgroup>
<thead><tr class="header">
<th>Scopo</th>
<th>Formula da usare</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Test dell’ipotesi nulla <span class="math inline">\(H_0: p_1 = p_2\)</span>
</td>
<td>✅ Usa la formula <strong>con pooled proportion</strong>
</td>
</tr>
<tr class="even">
<td>Costruire intervallo di confidenza per <span class="math inline">\(p_1 - p_2\)</span>
</td>
<td>✅ Usa la formula <strong>senza pooling</strong>, con <span class="math inline">\(\hat{p}_1\)</span> e <span class="math inline">\(\hat{p}_2\)</span>
</td>
</tr>
</tbody>
</table></section></section><section id="un-esempio-illustrativo" class="level2" data-number="71.7"><h2 data-number="71.7" class="anchored" data-anchor-id="un-esempio-illustrativo">
<span class="header-section-number">71.7</span> Un esempio Illustrativo</h2>
<p>Per mettere in pratica quanto detto, consideriamo un caso reale tratto dallo studio di <span class="citation" data-cites="banerjee2025children">Banerjee et al. (<a href="#ref-banerjee2025children" role="doc-biblioref">2025</a>)</span>. In questo studio vengono confrontate le abilità matematiche di:</p>
<ul>
<li>
<strong>bambini lavoratori nei mercati</strong> di Kolkata e Delhi;</li>
<li>
<strong>bambini scolarizzati</strong> che non lavorano.</li>
</ul>
<p>L’obiettivo era valutare se le competenze sviluppate nel lavoro quotidiano (come dare il resto, sommare prezzi, ecc.) si trasferiscono al contesto scolastico e viceversa.</p>
<p>I risultati principali mostrano come:</p>
<ul>
<li>i <strong>bambini lavoratori</strong> si sono dimostrati molto abili nel risolvere problemi matematici concreti, ma hanno faticato con problemi presentati in forma astratta (come quelli scolastici);</li>
<li>al contrario, i <strong>bambini scolarizzati</strong> se la sono cavata meglio con problemi astratti, ma sono risultati poco efficaci nei problemi concreti del mercato.</li>
</ul>
<p>Vediamo i dati raccolti per due tipi di problemi:</p>
<p><strong>Problemi astratti.</strong></p>
<table class="caption-top table">
<thead><tr class="header">
<th>Gruppo</th>
<th>Successi</th>
<th>Prove totali</th>
<th>Proporzione</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Bambini lavoratori</td>
<td>670</td>
<td>1488</td>
<td>0.45</td>
</tr>
<tr class="even">
<td>Bambini scolarizzati</td>
<td>320</td>
<td>542</td>
<td>0.59</td>
</tr>
</tbody>
</table>
<p><strong>Problemi di mercato.</strong></p>
<table class="caption-top table">
<thead><tr class="header">
<th>Gruppo</th>
<th>Successi</th>
<th>Prove totali</th>
<th>Proporzione</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Bambini lavoratori</td>
<td>134</td>
<td>373</td>
<td>0.36</td>
</tr>
<tr class="even">
<td>Bambini scolarizzati</td>
<td>3</td>
<td>271</td>
<td>0.01</td>
</tr>
</tbody>
</table>
<section id="confronto-per-i-problemi-astratti" class="level3" data-number="71.7.1"><h3 data-number="71.7.1" class="anchored" data-anchor-id="confronto-per-i-problemi-astratti">
<span class="header-section-number">71.7.1</span> Confronto per i problemi astratti</h3>
<p>Utilizzando l’approccio frequentista, vogliamo verificare se la differenza tra 0.45 (lavoratori) e 0.59 (scolarizzati) è spiegabile dal caso.</p>
<p><strong>Ipotesi.</strong></p>
<ul>
<li>
<span class="math inline">\(H_0\)</span>: <span class="math inline">\(p_1 = p_2\)</span> (nessuna differenza tra i gruppi);</li>
<li>
<span class="math inline">\(H_1\)</span>: <span class="math inline">\(p_1 \ne p_2\)</span> (esiste una differenza).</li>
</ul>
<p><strong>Calcolo.</strong></p>
<ol type="1">
<li>
<p><strong>Proporzione combinata (pooled)</strong>:</p>
<p><span class="math display">\[
\hat{p} = \frac{670 + 320}{1488 + 542} = \frac{990}{2030} \approx 0.487.
\]</span></p>
</li>
<li>
<p><strong>Varianza stimata della differenza</strong>:</p>
<p><span class="math display">\[
\text{Var} = \hat{p}(1 - \hat{p}) \left( \frac{1}{1488} + \frac{1}{542} \right) \approx 0.000629.
\]</span></p>
</li>
<li><p><strong>Deviazione standard</strong>: <span class="math inline">\(\sqrt{0.000629} \approx 0.0251\)</span>.</p></li>
<li>
<p><strong>Statistica z</strong>:</p>
<p><span class="math display">\[
z = \frac{0.45 - 0.59}{0.0251} \approx -5.58.
\]</span></p>
</li>
</ol>
<p>Il valore z è molto lontano da 0: la probabilità di osservare una tale differenza per caso (p-value) è inferiore a 0.0001. Possiamo quindi rifiutare l’ipotesi nulla.</p>
</section><section id="confronto-per-i-problemi-di-mercato" class="level3" data-number="71.7.2"><h3 data-number="71.7.2" class="anchored" data-anchor-id="confronto-per-i-problemi-di-mercato">
<span class="header-section-number">71.7.2</span> Confronto per i problemi di mercato</h3>
<p>Dati:</p>
<ul>
<li>Lavoratori: 134 su 373 (<span class="math inline">\(\hat{p}_1 = 0.36\)</span>)</li>
<li>Scolarizzati: 3 su 271 (<span class="math inline">\(\hat{p}_2 = 0.01\)</span>)</li>
</ul>
<p>Ripetiamo i passaggi:</p>
<ol type="1">
<li><p><span class="math inline">\(\hat{p} = \frac{137}{644} \approx 0.213\)</span></p></li>
<li><p><span class="math inline">\(\text{Var} \approx 0.001067\)</span></p></li>
<li><p>Deviazione standard: <span class="math inline">\(\sqrt{0.001067} \approx 0.0327\)</span></p></li>
<li>
<p>Statistica z:</p>
<p><span class="math display">\[
z = \frac{0.36 - 0.01}{0.0327} \approx 10.70
\]</span></p>
</li>
</ol>
<p>Anche qui, il p-value è praticamente zero: le differenze sono molto più grandi di quanto ci si aspetti per puro caso.</p>
<p>In sintesi, l’approccio frequentista ci consente di:</p>
<ul>
<li>stimare la differenza tra le proporzioni,</li>
<li>quantificare l’incertezza (varianza e intervallo di confidenza),</li>
<li>testare ipotesi sul fatto che la differenza sia zero o meno.</li>
</ul>
<p>In entrambi i confronti (problemi astratti e problemi concreti), abbiamo trovato evidenze chiare di una differenza tra i due gruppi.</p>
</section><section id="svolgimento-con-r" class="level3" data-number="71.7.3"><h3 data-number="71.7.3" class="anchored" data-anchor-id="svolgimento-con-r">
<span class="header-section-number">71.7.3</span> Svolgimento con R</h3>
<p>Di seguito mostriamo due modalità per replicare i calcoli in R: (1) passo passo usando le formule manuali, (2) usando la funzione <code><a href="https://rdrr.io/r/stats/prop.test.html">prop.test()</a></code> di R. Verranno illustrate entrambe le analisi: quella per i <strong>problemi astratti</strong> e quella per i <strong>problemi matematici di mercato</strong>.</p>
<section id="problemi-astratti" class="level4" data-number="71.7.3.1"><h4 data-number="71.7.3.1" class="anchored" data-anchor-id="problemi-astratti">
<span class="header-section-number">71.7.3.1</span> Problemi astratti</h4>
<p><strong>Dati</strong></p>
<ul>
<li>Bambini lavoratori (gruppo 1): 670 successi su 1488 prove.</li>
<li>Bambini scolarizzati (gruppo 2): 320 successi su 542 prove.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">##  Dati</span></span>
<span><span class="va">x_work</span>   <span class="op">&lt;-</span> <span class="fl">670</span>   <span class="co"># successi (risposte corrette) tra i lavoratori</span></span>
<span><span class="va">n_work</span>   <span class="op">&lt;-</span> <span class="fl">1488</span>  <span class="co"># totale lavoratori</span></span>
<span></span>
<span><span class="va">x_school</span> <span class="op">&lt;-</span> <span class="fl">320</span>   <span class="co"># successi tra i non-lavoratori (scolarizzati)</span></span>
<span><span class="va">n_school</span> <span class="op">&lt;-</span> <span class="fl">542</span>   <span class="co"># totale non-lavoratori</span></span>
<span></span>
<span><span class="co">##  Differenza di proporzioni </span></span>
<span><span class="va">p_work</span>   <span class="op">&lt;-</span> <span class="va">x_work</span>   <span class="op">/</span> <span class="va">n_work</span></span>
<span><span class="va">p_school</span> <span class="op">&lt;-</span> <span class="va">x_school</span> <span class="op">/</span> <span class="va">n_school</span></span>
<span><span class="va">rd</span>       <span class="op">&lt;-</span> <span class="va">p_school</span> <span class="op">-</span> <span class="va">p_work</span>          </span>
<span></span>
<span><span class="co">##  Errore standard</span></span>
<span><span class="co">##  - Pooled SE per lo z-test (ipotesi H0: p1 = p2)</span></span>
<span><span class="co">##  - Unpooled SE per l’intervallo di confidenza</span></span>
<span><span class="va">p_pool</span>   <span class="op">&lt;-</span> <span class="op">(</span><span class="va">x_work</span> <span class="op">+</span> <span class="va">x_school</span><span class="op">)</span> <span class="op">/</span> <span class="op">(</span><span class="va">n_work</span> <span class="op">+</span> <span class="va">n_school</span><span class="op">)</span></span>
<span><span class="va">se_test</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">p_pool</span> <span class="op">*</span> <span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="va">p_pool</span><span class="op">)</span> <span class="op">*</span> <span class="op">(</span><span class="fl">1</span><span class="op">/</span><span class="va">n_work</span> <span class="op">+</span> <span class="fl">1</span><span class="op">/</span><span class="va">n_school</span><span class="op">)</span><span class="op">)</span>  <span class="co"># usato solo per lo z-test</span></span>
<span><span class="va">se_ci</span>    <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">p_work</span> <span class="op">*</span> <span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="va">p_work</span><span class="op">)</span> <span class="op">/</span> <span class="va">n_work</span> <span class="op">+</span></span>
<span>                 <span class="va">p_school</span> <span class="op">*</span> <span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="va">p_school</span><span class="op">)</span> <span class="op">/</span> <span class="va">n_school</span><span class="op">)</span>  <span class="co"># migliore per il 95 % CI</span></span>
<span></span>
<span><span class="co">##  Inferenza</span></span>
<span><span class="va">z</span>        <span class="op">&lt;-</span> <span class="va">rd</span> <span class="op">/</span> <span class="va">se_test</span></span>
<span><span class="va">p_value</span>  <span class="op">&lt;-</span> <span class="fl">2</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">z</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">alpha</span>    <span class="op">&lt;-</span> <span class="fl">.05</span></span>
<span><span class="va">z_crit</span>   <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">qnorm</a></span><span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="va">alpha</span><span class="op">/</span><span class="fl">2</span><span class="op">)</span></span>
<span><span class="va">ci_low</span>   <span class="op">&lt;-</span> <span class="va">rd</span> <span class="op">-</span> <span class="va">z_crit</span> <span class="op">*</span> <span class="va">se_ci</span></span>
<span><span class="va">ci_high</span>  <span class="op">&lt;-</span> <span class="va">rd</span> <span class="op">+</span> <span class="va">z_crit</span> <span class="op">*</span> <span class="va">se_ci</span></span>
<span></span>
<span><span class="co">##  Stampa risultati</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/sprintf.html">sprintf</a></span><span class="op">(</span></span>
<span>    <span class="st">"Differenza assoluta:  %0.3f\nErrore standard (CI): %0.3f\nZ-test:            %0.2f\nP-value:           %.3g\n95%% CI:            [%0.2f, %0.2f]\n"</span>,</span>
<span>    <span class="va">rd</span>, <span class="va">se_ci</span>, <span class="va">z</span>, <span class="va">p_value</span>, <span class="va">ci_low</span>, <span class="va">ci_high</span></span>
<span>  <span class="op">)</span></span>
<span><span class="op">)</span></span>
<span><span class="co">#&gt; Differenza assoluta:  0.140</span></span>
<span><span class="co">#&gt; Errore standard (CI): 0.025</span></span>
<span><span class="co">#&gt; Z-test:            5.59</span></span>
<span><span class="co">#&gt; P-value:           2.3e-08</span></span>
<span><span class="co">#&gt; 95% CI:            [0.09, 0.19]</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I valori ottenuti, 95% CI: 0.09 to 0.19, replicano quanto riportato da <span class="citation" data-cites="banerjee2025children">Banerjee et al. (<a href="#ref-banerjee2025children" role="doc-biblioref">2025</a>)</span> (la piccola differenza tra i risultati dipende dal fatto che gli autori hanno usato un metodo basato sulla regressione):</p>
<blockquote class="blockquote">
<p>Overall, 59% of non-working children correctly solved these problems compared with 45% of working children (β = –0.14, s.e.m. = 0.03, 95% CI = –0.20 to –0.08, P &lt; 0.001; Fig. 4, left).</p>
</blockquote>
</section><section id="analisi-con-funzione-prop.test" class="level4" data-number="71.7.3.2"><h4 data-number="71.7.3.2" class="anchored" data-anchor-id="analisi-con-funzione-prop.test">
<span class="header-section-number">71.7.3.2</span> Analisi con funzione <code>prop.test()</code>
</h4>
<p>Per ottenere direttamente il test di confronto di due proporzioni, possiamo usare la funzione <strong>prop.test</strong> di R. Attenzione che, di default, <code>prop.test</code> effettua una correzione per la continuità (Yates), che in questo contesto disattiviamo per confrontare i risultati con i calcoli manuali (impostando <code>correct = FALSE</code>).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Dati</span></span>
<span><span class="va">x</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">670</span>, <span class="fl">320</span><span class="op">)</span>      <span class="co"># successi   (lavoratori, non-lavoratori)</span></span>
<span><span class="va">n</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1488</span>, <span class="fl">542</span><span class="op">)</span>     <span class="co"># denominatori</span></span>
<span></span>
<span><span class="co"># Test χ² / z-test per p1 = p2  ── senza correzione di continuità</span></span>
<span><span class="va">out</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/prop.test.html">prop.test</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">n</span>, correct <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">out</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  2-sample test for equality of proportions without continuity</span></span>
<span><span class="co">#&gt;  correction</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; data:  x out of n</span></span>
<span><span class="co">#&gt; X-squared = 31, df = 1, p-value = 2e-08</span></span>
<span><span class="co">#&gt; alternative hypothesis: two.sided</span></span>
<span><span class="co">#&gt; 95 percent confidence interval:</span></span>
<span><span class="co">#&gt;  -0.18864 -0.09163</span></span>
<span><span class="co">#&gt; sample estimates:</span></span>
<span><span class="co">#&gt; prop 1 prop 2 </span></span>
<span><span class="co">#&gt; 0.4503 0.5904</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Interpretazione dei risultati.</strong></p>
<ul>
<li>Il test dell’ipotesi nulla porta al rifiuto di <span class="math inline">\(H_0\)</span>, suggerendo che le proporzioni di successo nei due gruppi non sono uguali.</li>
<li>L’intervallo di confidenza calcolato <strong>non include lo zero</strong>, indicando che la differenza osservata è incompatibile con l’assenza di effetto.</li>
<li>Possiamo quindi concludere che esiste <strong>una differenza rilevante</strong> tra le proporzioni di successo dei bambini lavoratori e di quelli scolarizzati.</li>
</ul></section></section></section><section id="approccio-bayesiano" class="level2" data-number="71.8"><h2 data-number="71.8" class="anchored" data-anchor-id="approccio-bayesiano">
<span class="header-section-number">71.8</span> Approccio Bayesiano</h2>
<p>È possibile applicare l’approccio bayesiano al problema dell’inferenza sulla differenza tra due proporzioni indipendenti utilizzando un modello di regressione con una variabile indicatrice (dummy) per distinguere i due gruppi. Per fare un esempio, consideriamo qui i problemi astratti. Utilizziamo il pacchetto <code>brms</code> per stimare il modello, con distribuzioni a priori debolmente informative specificate di default.</p>
<section id="dati" class="level3" data-number="71.8.1"><h3 data-number="71.8.1" class="anchored" data-anchor-id="dati">
<span class="header-section-number">71.8.1</span> Dati</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Successi e denominatori</span></span>
<span><span class="va">x_work</span>   <span class="op">&lt;-</span> <span class="fl">670</span> ; <span class="va">n_work</span>   <span class="op">&lt;-</span> <span class="fl">1488</span></span>
<span><span class="va">x_non</span>    <span class="op">&lt;-</span> <span class="fl">320</span> ; <span class="va">n_non</span>    <span class="op">&lt;-</span>  <span class="fl">542</span></span>
<span></span>
<span><span class="va">dat_a</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span></span>
<span>  count <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">x_work</span>, <span class="va">x_non</span><span class="op">)</span>,</span>
<span>  tot   <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">n_work</span>, <span class="va">n_non</span><span class="op">)</span>,</span>
<span>  group <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"working"</span>, <span class="st">"non-working"</span><span class="op">)</span>,</span>
<span>                 levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"non-working"</span>, <span class="st">"working"</span><span class="op">)</span><span class="op">)</span>  <span class="co"># “non-working” livello di riferimento</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">dat_a</span></span>
<span><span class="co">#&gt; # A tibble: 2 × 3</span></span>
<span><span class="co">#&gt;   count   tot group      </span></span>
<span><span class="co">#&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;fct&gt;      </span></span>
<span><span class="co">#&gt; 1   670  1488 working    </span></span>
<span><span class="co">#&gt; 2   320   542 non-working</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="prior-debolmente-informativi" class="level3" data-number="71.8.2"><h3 data-number="71.8.2" class="anchored" data-anchor-id="prior-debolmente-informativi">
<span class="header-section-number">71.8.2</span> <em>Prior</em> debolmente informativi</h3>
<ul>
<li>
<strong>Normal (0, 2.5)</strong> sul logit corrisponde ai suggerimenti di Gelman et al.&nbsp;per logistic regression: – copre probabilità grossolanamente tra 0.004 e 0.996 sull’intercetta; – per il coefficiente di gruppo equivale a un odds-ratio plausibile entro ~ e±5.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">priors</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  <span class="fu">prior</span><span class="op">(</span><span class="fu">normal</span><span class="op">(</span><span class="fl">0</span>, <span class="fl">2.5</span><span class="op">)</span>, class <span class="op">=</span> <span class="st">"Intercept"</span><span class="op">)</span>,</span>
<span>  <span class="fu">prior</span><span class="op">(</span><span class="fu">normal</span><span class="op">(</span><span class="fl">0</span>, <span class="fl">2.5</span><span class="op">)</span>, class <span class="op">=</span> <span class="st">"b"</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="stima-del-modello" class="level3" data-number="71.8.3"><h3 data-number="71.8.3" class="anchored" data-anchor-id="stima-del-modello">
<span class="header-section-number">71.8.3</span> Stima del modello</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_a</span> <span class="op">&lt;-</span> <span class="fu">brm</span><span class="op">(</span></span>
<span>  <span class="va">count</span> <span class="op">|</span> <span class="fu">trials</span><span class="op">(</span><span class="va">tot</span><span class="op">)</span> <span class="op">~</span> <span class="va">group</span>,</span>
<span>  data      <span class="op">=</span> <span class="va">dat_a</span>,</span>
<span>  family    <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>  prior     <span class="op">=</span> <span class="va">priors</span>,</span>
<span>  backend   <span class="op">=</span> <span class="st">"cmdstanr"</span>,</span>
<span>  seed      <span class="op">=</span> <span class="fl">1234</span>,</span>
<span>  iter      <span class="op">=</span> <span class="fl">4000</span>, chains <span class="op">=</span> <span class="fl">4</span>, cores <span class="op">=</span> <span class="fl">4</span>,</span>
<span>  sample_prior <span class="op">=</span> <span class="st">"yes"</span>   <span class="co"># utile per i PPC sui prior</span></span>
<span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Controlla rapidamente la convergenza:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">fit_a</span>, digits <span class="op">=</span> <span class="fl">3</span><span class="op">)</span></span>
<span><span class="co">#&gt;  Family: binomial </span></span>
<span><span class="co">#&gt;   Links: mu = logit </span></span>
<span><span class="co">#&gt; Formula: count | trials(tot) ~ group </span></span>
<span><span class="co">#&gt;    Data: dat_a (Number of observations: 2) </span></span>
<span><span class="co">#&gt;   Draws: 4 chains, each with iter = 4000; warmup = 2000; thin = 1;</span></span>
<span><span class="co">#&gt;          total post-warmup draws = 8000</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Regression Coefficients:</span></span>
<span><span class="co">#&gt;              Estimate Est.Error l-95% CI u-95% CI  Rhat Bulk_ESS Tail_ESS</span></span>
<span><span class="co">#&gt; Intercept       0.369     0.086    0.201    0.539 1.000     3230     3722</span></span>
<span><span class="co">#&gt; groupworking   -0.569     0.100   -0.766   -0.368 1.001     3929     3843</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Draws were sampled using sample(hmc). For each parameter, Bulk_ESS</span></span>
<span><span class="co">#&gt; and Tail_ESS are effective sample size measures, and Rhat is the potential</span></span>
<span><span class="co">#&gt; scale reduction factor on split chains (at convergence, Rhat = 1).</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">pp_check</span><span class="op">(</span><span class="va">fit_a</span>, type <span class="op">=</span> <span class="st">"bars"</span><span class="op">)</span>   </span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><a href="12_two_proportions_files/figure-html/unnamed-chunk-8-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img src="12_two_proportions_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></a></p>
</figure>
</div>
</div>
</div>
</section><section id="dalla-scala-logit-alla-scala-delle-probabilità" class="level3" data-number="71.8.4"><h3 data-number="71.8.4" class="anchored" data-anchor-id="dalla-scala-logit-alla-scala-delle-probabilità">
<span class="header-section-number">71.8.4</span> Dalla scala logit alla scala delle probabilità</h3>
<p>Il modello stima</p>
<p><span class="math display">\[
\operatorname{logit}(p_i)=\beta_0+\beta_1\; \mathbf 1_{\text{working},i},
\]</span></p>
<p>perciò:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 32%">
<col style="width: 67%">
</colgroup>
<thead><tr class="header">
<th>Parametro</th>
<th>Significato</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>β₀ (<code>b_Intercept</code>)</strong></td>
<td>log-odds di successo per <em>non-working</em>
</td>
</tr>
<tr class="even">
<td><strong>β₁ (<code>b_groupworking</code>)</strong></td>
<td>differenza di log-odds fra <em>working</em> e <em>non-working</em>
</td>
</tr>
</tbody>
</table>
<p>Per ottenere <strong>proporzioni</strong> e <strong>differenza assoluta (Δ)</strong> dobbiamo trasformare <em>ogni</em> draw con l’inversa del logit, <code><a href="https://rdrr.io/r/stats/Logistic.html">plogis()</a></code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">post</span> <span class="op">&lt;-</span> <span class="fu">as_draws_df</span><span class="op">(</span><span class="va">fit_a</span>, </span>
<span>                    variables <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"b_Intercept"</span>, <span class="st">"b_groupworking"</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span></span>
<span>    p_non  <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Logistic.html">plogis</a></span><span class="op">(</span><span class="va">b_Intercept</span><span class="op">)</span>,                       <span class="co"># Pr(corretto | non-working)</span></span>
<span>    p_work <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Logistic.html">plogis</a></span><span class="op">(</span><span class="va">b_Intercept</span> <span class="op">+</span> <span class="va">b_groupworking</span><span class="op">)</span>,      <span class="co"># Pr(corretto | working)</span></span>
<span>    diff   <span class="op">=</span> <span class="va">p_non</span> <span class="op">-</span> <span class="va">p_work</span>                             <span class="co"># risk-difference</span></span>
<span>  <span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Perché non basta sottrarre β₁?</strong></p>
<p>Perché β₁ è una differenza di <strong>log-odds</strong>. La quantità di interesse qui è la differenza di <strong>probabilità</strong>. Le due scale sono non lineari e non confrontabili senza trasformazione.</p>
</section><section id="sintesi-della-riskdifference" class="level3" data-number="71.8.5"><h3 data-number="71.8.5" class="anchored" data-anchor-id="sintesi-della-riskdifference">
<span class="header-section-number">71.8.5</span> Sintesi della <em>risk–difference</em>
</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">summary_diff</span> <span class="op">&lt;-</span> <span class="va">post</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">summarise</span><span class="op">(</span></span>
<span>    mean     <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">diff</span><span class="op">)</span>,</span>
<span>    sd       <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">diff</span><span class="op">)</span>,</span>
<span>    `2.5%`   <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">diff</span>, <span class="fl">.025</span><span class="op">)</span>,</span>
<span>    `97.5%`  <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">diff</span>, <span class="fl">.975</span><span class="op">)</span>,</span>
<span>    prob_gt0 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">diff</span> <span class="op">&gt;</span> <span class="fl">0</span><span class="op">)</span>      <span class="co"># P(Δ &gt; 0 | dati, prior)</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">summary_diff</span>, digits <span class="op">=</span> <span class="fl">3</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 5</span></span>
<span><span class="co">#&gt;    mean     sd `2.5%` `97.5%` prob_gt0</span></span>
<span><span class="co">#&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 0.141 0.0244 0.0918   0.188        1</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<table class="caption-top table">
<thead><tr class="header">
<th>Δ (media)</th>
<th>SD</th>
<th>95 % CrI</th>
<th>P(Δ &gt; 0)</th>
</tr></thead>
<tbody><tr class="odd">
<td><strong>0.140</strong></td>
<td>0.025</td>
<td>0.090 – 0.190</td>
<td>1.000</td>
</tr></tbody>
</table>
<p>Il risultato replica quanto ottenuto con <code><a href="https://rdrr.io/r/stats/prop.test.html">prop.test()</a></code> (0.14 ± 0.025, IC 0.09–0.19).</p>
</section><section id="confronto-con-lapproccio-frequentista" class="level3" data-number="71.8.6"><h3 data-number="71.8.6" class="anchored" data-anchor-id="confronto-con-lapproccio-frequentista">
<span class="header-section-number">71.8.6</span> Confronto con l’approccio frequentista</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/prop.test.html">prop.test</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">x_work</span>, <span class="va">x_non</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">n_work</span>, <span class="va">n_non</span><span class="op">)</span>, correct <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  2-sample test for equality of proportions without continuity</span></span>
<span><span class="co">#&gt;  correction</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; data:  c(x_work, x_non) out of c(n_work, n_non)</span></span>
<span><span class="co">#&gt; X-squared = 31, df = 1, p-value = 2e-08</span></span>
<span><span class="co">#&gt; alternative hypothesis: two.sided</span></span>
<span><span class="co">#&gt; 95 percent confidence interval:</span></span>
<span><span class="co">#&gt;  -0.18864 -0.09163</span></span>
<span><span class="co">#&gt; sample estimates:</span></span>
<span><span class="co">#&gt; prop 1 prop 2 </span></span>
<span><span class="co">#&gt; 0.4503 0.5904</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>` Le due analisi coincidono: i bambini <em>non-working</em> hanno ~ 14 punti percentuali in più di probabilità di rispondere correttamente.</p>
</section><section id="perché-preferire-il-bayesiano" class="level3" data-number="71.8.7"><h3 data-number="71.8.7" class="anchored" data-anchor-id="perché-preferire-il-bayesiano">
<span class="header-section-number">71.8.7</span> Perché preferire il Bayesiano?</h3>
<ol type="1">
<li>
<strong>Niente “ipotesi nulla” irreale</strong> – lavoriamo direttamente con la distribuzione di Δ.</li>
<li>
<strong>Interpretazione pronta</strong> – il 95 % CrI dice che, dati e <em>prior</em>, Δ è fra 9 e 19 punti %.</li>
<li>
<strong>Flessibilità</strong> – possiamo integrare conoscenza pregressa, fare previsioni, decision-making, ecc.</li>
</ol>
<p>Con <em>prior</em> debolmente informativi i risultati restano virtualmente identici all’approccio frequentista; in dataset più piccoli o modelli più complessi, la stabilizzazione offerta dai <em>prior</em> diventa però cruciale.</p>
</section><section id="intervallo-di-credibilità-a-densità-più-alta" class="level3" data-number="71.8.8"><h3 data-number="71.8.8" class="anchored" data-anchor-id="intervallo-di-credibilità-a-densità-più-alta">
<span class="header-section-number">71.8.8</span> Intervallo di credibilità a densità più alta</h3>
<p>Per ottenere l’intervallo di credibilità (Highest Density Interval, <strong>HDI</strong>) sulla <strong>scala delle probabilità</strong> (e non su quella logit), è necessario trasformare manualmente i draw a livello di probabilità e poi calcolare l’HDI su quei valori trasformati. In altre parole:</p>
<ol type="1">
<li>
<strong>estraiamo i draw posteriori</strong> di <code>b_Intercept</code> e <code>b_groupworking</code>;<br>
</li>
<li>
<strong>trasformiamo i valori</strong> con la funzione logit-inversa (<span class="math inline">\(\operatorname{logistic}(x) = 1/(1+e^{-x})\)</span>) per ottenere le probabilità;<br>
</li>
<li>
<strong>se ci concentriamo sul solo effetto</strong> sulla scala della probabilità (e.g.&nbsp;differenza fra i due gruppi), calcoliamo la differenza tra la probabilità del gruppo “working” e quella del gruppo “reference” per ciascun draw;<br>
</li>
<li>
<strong>applichiamo <code>hdi()</code></strong> su queste grandezze trasformate.</li>
</ol>
<p>Di seguito è fornito il codice R con il workflow completo.</p>
<ol type="1">
<li>Estrazione draw posteriori.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">post</span> <span class="op">&lt;-</span> <span class="fu">as_draws_df</span><span class="op">(</span><span class="va">fit_a</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li>
<p>Calcolo delle probabilità per ciascun draw. La variabile ‘group’ abbia due livelli:</p>
<ul>
<li>“working” (effetto =&gt; b_groupworking)</li>
<li>“non-working” (riferimento =&gt; b_Intercept)</li>
</ul>
</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">post</span> <span class="op">&lt;-</span> <span class="va">post</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    p_ref      <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Logistic.html">plogis</a></span><span class="op">(</span><span class="va">b_Intercept</span><span class="op">)</span>,                       <span class="co"># probabilità (referenza)</span></span>
<span>    p_working  <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Logistic.html">plogis</a></span><span class="op">(</span><span class="va">b_Intercept</span> <span class="op">+</span> <span class="va">b_groupworking</span><span class="op">)</span>,      <span class="co"># prob. gruppo working</span></span>
<span>    diff_working_ref <span class="op">=</span> <span class="va">p_working</span> <span class="op">-</span> <span class="va">p_ref</span>                    <span class="co"># differenza</span></span>
<span>  <span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="3" type="1">
<li>Calcolo dell’HDI sull’effetto (o sulle probabilità).</li>
</ol>
<ol type="a">
<li>HDI per la probabilità del gruppo “working”.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">hdi_working_prob</span> <span class="op">&lt;-</span> <span class="fu">hdi</span><span class="op">(</span><span class="va">post</span><span class="op">$</span><span class="va">p_working</span>, ci <span class="op">=</span> <span class="fl">0.95</span><span class="op">)</span></span>
<span><span class="va">hdi_working_prob</span></span>
<span><span class="co">#&gt; 95% HDI: [0.43, 0.48]</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="a">
<li>HDI per la probabilità del gruppo “non-working” (riferimento).</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">hdi_ref_prob</span> <span class="op">&lt;-</span> <span class="fu">hdi</span><span class="op">(</span><span class="va">post</span><span class="op">$</span><span class="va">p_ref</span>, ci <span class="op">=</span> <span class="fl">0.95</span><span class="op">)</span></span>
<span><span class="va">hdi_ref_prob</span></span>
<span><span class="co">#&gt; 95% HDI: [0.55, 0.63]</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="3" type="a">
<li>HDI della differenza fra le due probabilità.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">hdi_diff</span> <span class="op">&lt;-</span> <span class="fu">hdi</span><span class="op">(</span><span class="va">post</span><span class="op">$</span><span class="va">diff_working_ref</span>, ci <span class="op">=</span> <span class="fl">0.89</span><span class="op">)</span></span>
<span><span class="va">hdi_diff</span></span>
<span><span class="co">#&gt; 89% HDI: [-0.18, -0.10]</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Interpretazione</strong></p>
<ul>
<li>
<code>hdi_working_prob</code> fornisce l’HDI al 95% (o al livello che specificato) <strong>della probabilità</strong> di “successo” del gruppo “working”.<br>
</li>
<li>
<code>hdi_ref_prob</code> fa lo stesso per il gruppo di riferimento.<br>
</li>
<li>
<code>hdi_diff</code> restituisce l’HDI della <strong>differenza</strong> in probabilità tra “working” e “reference” (<span class="math inline">\(p_{\text{working}} - p_{\text{reference}}\)</span>).</li>
</ul>
<p>In questo modo ottieniamo l’intervallo di credibilità (HDI) <strong>sulla scala delle probabilità</strong>.</p>
</section></section><section id="riflessioni-conclusive" class="level2" data-number="71.9"><h2 data-number="71.9" class="anchored" data-anchor-id="riflessioni-conclusive">
<span class="header-section-number">71.9</span> Riflessioni Conclusive</h2>
<p>In questo capitolo abbiamo esplorato il confronto tra due proporzioni adottando sia l’approccio frequentista sia quello bayesiano. L’obiettivo principale era valutare se la proporzione di successi in un gruppo differisse da quella osservata nell’altro gruppo, e con quale grado di incertezza.</p>
<p>Nella procedura classica frequentista (test per due proporzioni), si calcola una statistica di test (ad esempio, un test z) e il relativo p-value, ossia la probabilità di osservare un risultato così estremo (o più) assumendo che le due proporzioni reali siano uguali (ipotesi nulla).</p>
<ul>
<li>
<strong>Intervallo di confidenza</strong>: È possibile costruire un intervallo di confidenza (IC) per la differenza tra le due proporzioni. L’interpretazione frequentista di tale IC, però, si basa su un’ipotetica ripetizione di campionamenti ed è focalizzata sull’eventuale rifiuto o meno dell’ipotesi che la differenza sia zero.<br>
</li>
<li>
<strong>Limiti interpretativi</strong>: L’approccio frequentista si fonda sul concetto di ipotesi nulla “nessuna differenza” e non fornisce una probabilità diretta di quanto la differenza vera sia maggiore o minore di un certo valore, limitandosi a indicare se i dati sono inusuali qualora la differenza fosse zero.</li>
</ul>
<p>Grazie alla regola di Bayes, combiniamo informazioni a priori (sul probabile valore delle proporzioni) con i dati osservati, per ottenere una distribuzione a posteriori della differenza tra le due proporzioni. Questa distribuzione descrive i valori plausibili della differenza, insieme alle relative credibilità (probabilità).</p>
<ul>
<li>
<strong>Credible Interval o Highest Density Interval (HDI)</strong>: Al posto di un intervallo di confidenza, l’approccio bayesiano fornisce un intervallo di credibilità. Ad esempio, un 95% HDI indica i valori della differenza tra le proporzioni che cumulativamente contengono il 95% della probabilità a posteriori. È un costrutto immediatamente interpretabile: “Abbiamo una probabilità del 95% che la differenza vera cada all’interno di questo intervallo”.<br>
</li>
<li>
<strong>Flessibilità e interpretazione diretta</strong>: L’approccio bayesiano permette di rispondere in modo più naturale a domande come: “Qual è la probabilità che la differenza fra le due proporzioni sia maggiore di 0?” oppure “Qual è la probabilità che la proporzione di un gruppo superi quella dell’altro di almeno una certa soglia rilevante?”.</li>
</ul>
<p>Confronto tra i due approcci:</p>
<ol type="1">
<li>
<strong>Interpretazione dei risultati</strong>: Il p-value frequentista ci dice quanto il dato sia “improbabile” sotto l’ipotesi di uguaglianza delle proporzioni; il Bayesianesimo risponde direttamente a quanto è plausibile ogni possibile valore di differenza.<br>
</li>
<li>
<strong>Centralità dell’ipotesi nulla</strong>: Nel frequentismo, l’ipotesi nulla (differenza = 0) è centrale. Nel modello bayesiano, è invece possibile assegnare direttamente probabilità alla differenza e alla sua distanza da zero, evitando un focus eccessivo sull’uguaglianza perfetta delle due proporzioni.<br>
</li>
<li>
<strong>Ruolo dei priors</strong>: L’uso di priors (non informativi o informativi) può influire sulle stime bayesiane quando i dati sono scarsi, rendendo evidente la necessità di scelte trasparenti e ben motivate. Tuttavia, con campioni ampi, l’influenza dei priors tende a ridursi e la stima a posteriori è dominata dai dati.<br>
</li>
<li>
<strong>Completezza dell’inferenza</strong>: L’approccio bayesiano consente di integrare nuove informazioni e di aggiornare la distribuzione a posteriori man mano che arrivano dati aggiuntivi. Al contrario, l’approccio frequentista non fornisce un meccanismo diretto di “aggiornamento” delle stime alla luce di nuovi dati.</li>
</ol>
<p>In sintesi,</p>
<ul>
<li>
<strong>approccio frequentista</strong>: Si tratta di una metodologia consolidata e standard nella ricerca; fornisce risultati in termini di p-value e IC, ma l’interpretazione del p-value e dell’IC resta legata a procedure di campionamento ipotetico.<br>
</li>
<li>
<strong>approccio bayesiano</strong>: Offre una maniera più intuitiva di quantificare l’incertezza, assegnando probabilità dirette ai possibili valori di differenza fra le due proporzioni. Consente di formulare domande più specifiche (es. la probabilità che la differenza superi un valore definito) e di integrare in modo naturale informazioni a priori.</li>
</ul>
<p>Nella pratica della ricerca, l’approccio frequentista rimane diffuso. Tuttavia, l’inferenza bayesiana fornisce un quadro interpretativo più ricco e flessibile. Utilizzare entrambi i metodi, quando appropriato, può potenziare l’analisi e la comprensione dei dati, permettendo di trarre conclusioni più robuste e trasparenti.</p>
</section><section id="informazioni-sullambiente-di-sviluppo" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="informazioni-sullambiente-di-sviluppo">Informazioni sull’Ambiente di Sviluppo</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; R version 4.5.0 (2025-04-11)</span></span>
<span><span class="co">#&gt; Platform: aarch64-apple-darwin20</span></span>
<span><span class="co">#&gt; Running under: macOS Sequoia 15.5</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Matrix products: default</span></span>
<span><span class="co">#&gt; BLAS:   /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRblas.0.dylib </span></span>
<span><span class="co">#&gt; LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; locale:</span></span>
<span><span class="co">#&gt; [1] C/UTF-8/C/C/C/C</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; time zone: Europe/Rome</span></span>
<span><span class="co">#&gt; tzcode source: internal</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; attached base packages:</span></span>
<span><span class="co">#&gt; [1] stats     graphics  grDevices utils     datasets  methods   base     </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; other attached packages:</span></span>
<span><span class="co">#&gt;  [1] insight_1.2.0     bayestestR_0.15.3 posterior_1.6.1   cmdstanr_0.9.0   </span></span>
<span><span class="co">#&gt;  [5] brms_2.22.0       Rcpp_1.0.14       thematic_0.1.6    MetBrewer_0.2.0  </span></span>
<span><span class="co">#&gt;  [9] ggokabeito_0.1.0  see_0.11.0        gridExtra_2.3     patchwork_1.3.0  </span></span>
<span><span class="co">#&gt; [13] bayesplot_1.12.0  psych_2.5.3       scales_1.4.0      markdown_2.0     </span></span>
<span><span class="co">#&gt; [17] knitr_1.50        lubridate_1.9.4   forcats_1.0.0     stringr_1.5.1    </span></span>
<span><span class="co">#&gt; [21] dplyr_1.1.4       purrr_1.0.4       readr_2.1.5       tidyr_1.3.1      </span></span>
<span><span class="co">#&gt; [25] tibble_3.2.1      ggplot2_3.5.2     tidyverse_2.0.0   rio_1.2.3        </span></span>
<span><span class="co">#&gt; [29] here_1.0.1       </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; loaded via a namespace (and not attached):</span></span>
<span><span class="co">#&gt;  [1] tidyselect_1.2.1     farver_2.1.2         loo_2.8.0           </span></span>
<span><span class="co">#&gt;  [4] fastmap_1.2.0        tensorA_0.36.2.1     pacman_0.5.1        </span></span>
<span><span class="co">#&gt;  [7] digest_0.6.37        timechange_0.3.0     estimability_1.5.1  </span></span>
<span><span class="co">#&gt; [10] lifecycle_1.0.4      StanHeaders_2.32.10  processx_3.8.6      </span></span>
<span><span class="co">#&gt; [13] magrittr_2.0.3       compiler_4.5.0       rlang_1.1.6         </span></span>
<span><span class="co">#&gt; [16] tools_4.5.0          utf8_1.2.5           yaml_2.3.10         </span></span>
<span><span class="co">#&gt; [19] data.table_1.17.2    labeling_0.4.3       bridgesampling_1.1-2</span></span>
<span><span class="co">#&gt; [22] htmlwidgets_1.6.4    curl_6.2.2           pkgbuild_1.4.7      </span></span>
<span><span class="co">#&gt; [25] mnormt_2.1.1         plyr_1.8.9           RColorBrewer_1.1-3  </span></span>
<span><span class="co">#&gt; [28] abind_1.4-8          withr_3.0.2          stats4_4.5.0        </span></span>
<span><span class="co">#&gt; [31] grid_4.5.0           colorspace_2.1-1     inline_0.3.21       </span></span>
<span><span class="co">#&gt; [34] xtable_1.8-4         emmeans_1.11.1       cli_3.6.5           </span></span>
<span><span class="co">#&gt; [37] mvtnorm_1.3-3        rmarkdown_2.29       generics_0.1.4      </span></span>
<span><span class="co">#&gt; [40] RcppParallel_5.1.10  rstudioapi_0.17.1    reshape2_1.4.4      </span></span>
<span><span class="co">#&gt; [43] tzdb_0.5.0           rstan_2.32.7         parallel_4.5.0      </span></span>
<span><span class="co">#&gt; [46] matrixStats_1.5.0    vctrs_0.6.5          V8_6.0.3            </span></span>
<span><span class="co">#&gt; [49] Matrix_1.7-3         jsonlite_2.0.0       hms_1.1.3           </span></span>
<span><span class="co">#&gt; [52] glue_1.8.0           codetools_0.2-20     ps_1.9.1            </span></span>
<span><span class="co">#&gt; [55] distributional_0.5.0 stringi_1.8.7        gtable_0.3.6        </span></span>
<span><span class="co">#&gt; [58] QuickJSR_1.7.0       pillar_1.10.2        htmltools_0.5.8.1   </span></span>
<span><span class="co">#&gt; [61] Brobdingnag_1.2-9    R6_2.6.1             rprojroot_2.0.4     </span></span>
<span><span class="co">#&gt; [64] evaluate_1.0.3       lattice_0.22-7       backports_1.5.0     </span></span>
<span><span class="co">#&gt; [67] rstantools_2.4.0     coda_0.19-4.1        nlme_3.1-168        </span></span>
<span><span class="co">#&gt; [70] checkmate_2.3.2      xfun_0.52            pkgconfig_2.0.3</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="bibliografia" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="bibliografia">Bibliografia</h2>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-banerjee2025children" class="csl-entry" role="listitem">
Banerjee, A. V., Bhattacharjee, S., Chattopadhyay, R., Duflo, E., Ganimian, A. J., Rajah, K., &amp; Spelke, E. S. (2025). Children’s arithmetic skills do not transfer between applied and academic mathematics. <em>Nature</em>, 1–9.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiato!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiato!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ccaudek\.github\.io\/psicometria-r\/intro\.html");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../../chapters/linear_models/11_one_proportion.html" class="pagination-link" aria-label="Inferenza sulle proporzioni">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">70</span>&nbsp; <span class="chapter-title">Inferenza sulle proporzioni</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/linear_models/13_poisson_model.html" class="pagination-link" aria-label="Modello di Poisson">
        <span class="nav-page-text"><span class="chapter-number">72</span>&nbsp; <span class="chapter-title">Modello di Poisson</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>Psicometria</strong> è una risorsa didattica creata per il corso di Scienze e Tecniche Psicologiche dell’Università degli Studi di Firenze.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ccaudek/psicometria-r/blob/main/chapters/linear_models/12_two_proportions.qmd" class="toc-action"><i class="bi bi-github"></i>Mostra il codice</a></li><li><a href="https://github.com/ccaudek/psicometria-r/issues/new" class="toc-action"><i class="bi empty"></i>Segnala un problema</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Realizzato con <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>


</body></html>