---
title: "Syllabus dell'insegnamento di Psicometria -- A.A. 2024-2025"
date: today
date-format: "DD MMMM, YYYY"
author: 
  - Corrado Caudek
monofont: inconsolata
monofontoptions: scaled=.95
parskip: on
spacing: single
engine: jupyter
highlight-style: arrow
pdf-engine: pdflatex
format: 
    pdf:
      toc: true
      toc-depth: 2
      number-sections: true
      geometry: "left=3cm,right=3cm,top=2.5cm,bottom=2.5cm"
      header-includes: |
         \usepackage{fancyhdr}
         \pagestyle{fancy}
         \fancyhead[L]{Syllabus di Psicometria 2024-2025}
      bibliography: ../references.bib
      cls: apa7.cls
editor: 
  render-on-save: false
---

# Obiettivi Formativi

L'insegnamento di Psicometria (B000286) introduce gli studenti alle competenze essenziali della Data Science applicata alla psicologia, fornendo strumenti per progettare, condurre e interpretare ricerche psicologiche. Attraverso l'uso pratico di Python e del linguaggio probabilistico Stan, gli studenti impareranno a gestire dati complessi e costruire modelli statistici avanzati.

Il corso combina teoria e pratica: ogni argomento è affiancato da esercitazioni e laboratori, per favorire l’applicazione immediata dei concetti appresi. L'obiettivo è fornire una formazione operativa, preparando gli studenti a utilizzare software e linguaggi di programmazione per l'analisi statistica, competenze fondamentali per il loro futuro professionale in psicologia.

## Descrizione sintetica

L'insegnamento offre un percorso formativo progressivo, guidando gli studenti dalla comprensione dei concetti fondamentali della statistica all'applicazione di tecniche avanzate di analisi dei dati. Attraverso una serie di moduli strutturati, gli studenti acquisiranno le competenze necessarie per esplorare, modellare e interpretare dati complessi in ambito psicologico.

-   **Introduzione a Python per l'Analisi dei Dati**: Verrà introdotto l'uso di Python, enfatizzando le sue applicazioni nella gestione dei dati, preparando gli studenti all'uso di librerie specifiche per la data science.

-   **Elementi di Teoria della Probabilità**: Il modulo è dedicato allo studio dei fondamenti della teoria della probabilità. Verranno approfonditi concetti quali la probabilità condizionata, le distribuzioni di probabilità (discrete e continue) e le caratteristiche delle variabili aleatorie. Le conoscenze acquisite costituiranno la base per le successive applicazioni statistiche.

-   **Analisi Esplorativa dei Dati (EDA)**: Gli studenti acquisiranno le competenze necessarie per esplorare i dati attraverso l'EDA, utilizzando statistiche descrittive (media, moda, deviazione standard, intervallo interquartile) e visualizzazioni (istogrammi, grafici di dispersione).

-   **Analisi Bayesiana**: Il modulo è dedicato all'introduzione dell'analisi bayesiana e all'utilizzo del linguaggio Stan per la modellazione probabilistica. Gli studenti acquisiranno le competenze necessarie per rappresentare l'incertezza e aggiornare le inferenze alla luce di nuove evidenze.

-   **Tecniche Avanzate di Modellazione Statistica**: Attraverso lo studio di metodi come il campionamento e gli algoritmi MCMC, gli studenti acquisiranno le competenze necessarie per affrontare in modo efficiente problemi inferenziali complessi, tipici dell'analisi bayesiana.

-   **Fondamenti di Inferenza Causale**: Saranno trattati i concetti di inferenza causale, fondamentali per costruire modelli che identificano relazioni di causa-effetto oltre la semplice correlazione.

-   **Limiti dell'Inferenza Frequentista**: Una critica ai limiti dell'inferenza frequentista tradizionale, con particolare attenzione ai test dell'ipotesi nulla e agli intervalli di confidenza.

Il culmine del corso è rappresentato da un progetto di gruppo, dove gli studenti metteranno in pratica le conoscenze acquisite, lavorando in team per analizzare un dataset reale e presentare i risultati in modo chiaro e conciso. Il progetto di gruppo, sviluppato seguendo le linee guida proposte da @strand2023error e @bennett2014collaboration, sarà incentrato sullo sviluppo di competenze trasversali fondamentali come la collaborazione, la comunicazione e la risoluzione dei problemi. Gli studenti saranno chiamati a definire un problema di ricerca, analizzare i dati, e infine presentare i risultati in un report scritto e orale. Verranno valutate sia la qualità del lavoro svolto sia la capacità di lavorare efficacemente in team.

## Filosofia Didattica

In contrasto con gli approcci più tradizionali e teoricamente pesanti comuni nei corsi di analisi dei dati psicologici, il presente insegnamento adotta una filosofia didattica pragmatica e orientata alla pratica. L'obiettivo è superare le convenzioni di focalizzazione esclusiva su teorie e dimostrazioni matematiche per privilegiare l'apprendimento attivo attraverso l'uso di dati reali e strumenti di programmazione avanzati.

Questo approccio permette agli studenti di acquisire competenze pratiche essenziali, enfatizzando l'uso del linguaggio Python anziché l'impiego di formule matematiche complesse. Tale scelta rende il corso più accessibile a studenti con diverse basi di preparazione matematica e promuove una comprensione più profonda dell'interpretazione e dell'applicazione dei risultati statistici.

Python, con la sua crescente popolarità e le sue numerose librerie dedicate all'analisi statistica e alla data science, è stato scelto come strumento principale di questo corso. Utilizzare Python non solo prepara gli studenti all'utilizzo di uno dei linguaggi più richiesti nel campo della ricerca scientifica e dell'analisi dei dati, ma offre anche l'accesso a una vasta gamma di risorse online che possono essere utilizzate per un ulteriore approfondimento.

Inoltre, il corso adotterà un modello didattico di [flipped classroom](https://it.wikipedia.org/wiki/Insegnamento_capovolto), dove gli studenti avranno l'opportunità di esplorare il materiale di studio autonomamente prima delle lezioni in classe. Questo permette di dedicare il tempo in aula a discussioni approfondite, risoluzione di problemi pratici e applicazioni dirette delle tecniche apprese, facilitando un ambiente di apprendimento interattivo e coinvolgente.

# Materiali Didattici

## Testi di base

Per una preparazione ottimale all'esame, è consigliato studiare attentamente i seguenti materiali:

1.  [**Introduction to Probability**](https://www.routledge.com/Introduction-to-Probability-Second-Edition/Blitzstein-Hwang/p/book/9781138369917)
    -   Le sezioni specifiche da approfondire sono indicate nella dispensa.
    -   La seconda edizione del libro è disponibile gratuitamente online su [probabilitybook.net](http://probabilitybook.net).
2.  [**Bayes Rules! An Introduction to Applied Bayesian Modeling**](https://www.bayesrulesbook.com/index.html)
    -   Questo libro fornisce una panoramica completa sulla modellazione bayesiana applicata.
    -   Le sezioni da studiare sono dettagliate nella dispensa.
3.  **Dispensa del corso**
    -   La dispensa, disponibile su questo sito, copre i temi del corso in modo approfondito. Inoltre, un sito di supporto fornisce numerosi esercizi pratici, con istruzioni in Python per eseguire le analisi richieste per l’esame.
4.  [**Statistical Rethinking**](https://xcelab.net/rm/statistical-rethinking/)**, primi due capitoli**
    -   I capitoli 1 e 2 sono accessibili gratuitamente tramite il link sopra indicato.
5.  [**Machine Learning with Python: Theory and Implementation**](https://link.springer.com/book/10.1007/978-3-031-33342-2?source=shoppingads) [@zollanvari2023machine]
    -   Si raccomanda di approfondire unicamente i capitoli 2 (*Getting Started with Python*) e 3 (*Three Fundamental Python Packages*).
    -   Per chi desidera ampliare la conoscenza di Python, sono disponibili numerose risorse online. In particolare, si consiglia [A Beginner's Guide to Python 3 Programming](https://link.springer.com/book/10.1007/978-3-031-35122-8) per un’introduzione strutturata, e [An Introduction to Python for R Users](https://rebeccabarter.com/blog/2023-09-11-from_r_to_python#methods), che esplora Python con un approccio orientato all'analisi dei dati.
6.  **Articoli scientifici selezionati**
    -   Si richiede un’attenta lettura dei seguenti articoli, disponibili nella sezione Moodle del corso:
        -   Loken, E., & Gelman, A. (2017). Measurement error and the replication crisis. *Science*, *355*(6325), 584-585.
        -   Amrhein, V., Greenland, S., & McShane, B. (2019). Comment: Retire statistical significance. *Nature*, *567*, 305-307.
        -   Wasserstein, R. L., Schirm, A. L., & Lazar, N. A. (2019). Moving to a world beyond “p \< 0.05”. *The American Statistician*, *73*(sup1), 1-19.

Questi materiali sono fondamentali per sviluppare una solida comprensione degli argomenti trattati nel corso e per prepararsi efficacemente all’esame finale.

## Materiali supplementari

I seguenti materiali supplementari sono forniti come risorse aggiuntive per coloro che desiderano approfondire gli argomenti trattati nella dispensa o consultare testi che presentano gli stessi contenuti da prospettive diverse.

1.  I [video](https://github.com/rmcelreath/stat_rethinking_2024?tab=readme-ov-file) delle lezioni di Richard McElreath, basati sul suo libro *"Statistical Rethinking: A Bayesian Course Using R and Stan"*, sono altamente consigliati.

2.  Il libro [An Introduction to Bayesian Data Analysis for Cognitive Science](https://vasishth.github.io/bayescogsci/book/) di Bruno Nicenboim, Daniel Schad, e Shravan Vasishth fornisce un'introduzione alla conduzione dell'analisi dei dati bayesiani e alla modellazione cognitiva utilizzando il linguaggio di programmazione probabilistico Stan.

3.  Il libro [Think Bayes 2](https://allendowney.github.io/ThinkBayes2/) di Allen B. Downey fornisce un'introduzione alla statistica bayesiana usando metodi computazionali (in Python).

4.  Il libro [Probability and Bayesian Modeling](https://bayesball.github.io/BOOK/probability-a-measurement-of-uncertainty.html) di Jim Albert e Jingchen Hu fornisce un'ottima introduzione alla statistica bayesiana ed è disponibile online.

5.  Il libro [Bayesian Modeling and Computation in Python](https://bayesiancomputationbook.com/welcome.html) presenta discussioni introduttive e avanzate sulla statistica bayesiana usando PyMC. Alcune parti del testo sono disponibili online.

6.  Il libro [Bayesian Analysis with Python (3rd ed.)](https://www.packtpub.com/product/bayesian-analysis-with-python-third-edition/9781805127161) di Osvaldo Martin è anch'esso un'ottima introduzione all'inferenza bayesiana con PyMC.

7.  Il libro [Bayesian Compendium (2nd ed.)](https://link.springer.com/book/10.1007/978-3-031-66085-6) di @vanOijen2024 presenta un'introduzione all'inferenza bayesiana chiara e accessibile, rendendo i concetti complessi comprensibili anche a lettori non esperti.

8.  Il libro [Data Analysis for Social Science: A Friendly and Practical Introduction](https://press.princeton.edu/books/paperback/9780691199436/data-analysis-for-social-science) scritto da Elena Llaudet e Kosuke Imai (2022) offre un'introduzione accessibile all'analisi dei dati. Pur non trattando la statistica bayesiana, il libro rappresenta un'eccellente introduzione agli argomenti trattati nel contesto del presente corso.

# Guida allo studio

## Metodologia: Flip Teaching

In questo corso utilizzeremo la metodologia del "flip teaching", un approccio didattico innovativo che incoraggia l'apprendimento attivo e collaborativo. Il processo di apprendimento sarà strutturato in due fasi distinte: una fase di studio individuale e una fase di apprendimento collaborativo in aula.

## Studio individuale

Prima di ogni lezione, è richiesto di:

-   studiare attentamente il materiale didattico assegnato;
-   replicare sul proprio computer le analisi dei dati presentate nella dispensa;
-   collegare le teorie discusse con le loro applicazioni pratiche;
-   svolgere esercizi sugli stessi argomenti trattati nella dispensa, utilizzando la metodologia di analisi dei dati proposta; gli esercizi possono essere svolti sia in Python che in R (il risultato sarà equivalente). La dispensa fornisce esempi con soluzioni. Ulteriori esercizi possono essere creati dagli studenti stessi, ponendo domande generali a strumenti come ChatGPT o Claude e chiedendo la soluzione nel linguaggio preferito (Python o R). Altri esercizi utili sono facilmente reperibili online;
-   preparare domande o dubbi per la discussione in aula.

Questa fase richiede un impegno individuale significativo per permettervi di acquisire una solida comprensione dei concetti chiave, che saranno poi approfonditi in aula.

Gli esercizi presenti nella dispensa sono pensati per preparare al meglio all'esame; servono come strumento di autovalutazione per verificare se la comprensione dei concetti trattati è adeguata.

## Collaborazione e partecipazione attiva

Il corso si propone di promuovere una cultura di apprendimento collaborativo tramite:

-   Partecipazione attiva in classe, che include la discussione di argomenti, esempi e quesiti che potrebbero presentarsi negli esami e nei compiti, anche se non sono trattati direttamente nel manuale di riferimento o nelle dispense;
-   Progetti realistici che incoraggiano la collaborazione e richiedono l'applicazione pratica delle conoscenze acquisite;
-   Tecniche collaborative, come il pair programming, che vengono incoraggiate.

Durante le lezioni in aula, avrete la possibilità di:

-   discutere e chiarire eventuali dubbi emersi dallo studio individuale;
-   partecipare attivamente a discussioni e lavori di gruppo;
-   collaborare alla risoluzione di problemi pratici utilizzando il linguaggio Python.

Seguendo queste linee guida, vi preparerete in modo adeguato per affrontare l'esame con competenza e sicurezza. È importante ricordare che non è richiesta alcuna conoscenza pregressa di software specifici o di programmazione informatica — basta avere pazienza e desiderio di imparare.

## Metodo di studio

Per un apprendimento efficace, è fondamentale combinare una partecipazione attiva alle lezioni con uno studio personale strutturato. Seguendo questa sequenza, sarà possibile massimizzare l'assimilazione dei contenuti e affrontare l'esame finale con successo:

-   Iniziate leggendo la dispensa per ottenere una panoramica generale ma dettagliata degli argomenti trattati.
-   Successivamente, approfondite con *Bayes Rules!* per una spiegazione più articolata dei concetti.
-   Applicate ciò che avete appreso studiando il codice Python presentato nelle dimostrazioni pratiche, integrando così la teoria con esempi concreti.
-   Completate gli esercizi associati a ciascun capitolo per verificare la vostra competenza tecnica e la comprensione concettuale.
-   Partecipare attivamente alle lezioni, proponendo chiarimenti su punti critici, approfondimenti tematici ed esempi applicativi.
-   Consultate i testi opzionali indicati nel Syllabus per approfondire ulteriormente o esplorare da una prospettiva diversa gli stessi argomenti, avendo così l'opportunità di analizzare ogni tema in modo più dettagliato.

Seguendo questa strategia, sarete in grado di orientarvi efficacemente nel complesso corpus del materiale didattico e di prepararvi al meglio per l'esame finale.

# Programmazione

La programmazione riveste un ruolo cruciale nell'analisi dei dati psicologici. Durante il corso, imparerete le basi dei linguaggi di programmazione fondamentali, con un particolare focus su Python. Per affrontare le esercitazioni pratiche sarà necessario disporre di un computer.

Vi invito a sperimentare il [pair programming](https://it.wikipedia.org/wiki/Programmazione_in_coppia) e altre modalità di collaborazione, che si sono dimostrate estremamente efficaci per superare le difficoltà legate alla programmazione e per facilitare l'apprendimento.

Un valido supporto durante il corso sarà l'uso di tutor virtuali come ChatGPT o Claude. Potreste considerare l'acquisto di una licenza per la versione a pagamento di uno di questi strumenti per i tre mesi del corso, poiché queste versioni offrono un supporto più preciso e generano codice con meno errori. L'intelligenza artificiale (IA) può ridurre il carico cognitivo legato ai dettagli sintattici, in quanto è in grado di generare automaticamente codice corretto. Tuttavia, questo non esime l'utente dal partecipare attivamente al processo di apprendimento.

È fondamentale sviluppare una solida conoscenza delle regole del linguaggio di programmazione per interagire efficacemente con l'IA. Senza questa comprensione, risulterebbe difficile formulare le domande corrette o interpretare in modo appropriato le risposte dell'IA. Perciò, acquisire una chiara padronanza delle regole e pensare in termini algoritmici resta un passaggio essenziale, che non può essere delegato all'IA. Il vero valore dell'IA risiede nel sollevarvi dall'onere di memorizzare tutte le regole sintattiche, fornendo risposte algoritmiche e suggerimenti, specialmente quando ci si trova di fronte a problemi computazionali complessi.

## Sviluppo delle abilità

L'apprendimento della programmazione richiede precisione e attenzione, poiché i linguaggi seguono regole rigorose. Sebbene questo possa sembrare inizialmente frustrante, sviluppa la capacità di pensare in modo algoritmico e consente di condurre analisi dei dati in maniera sistematica e riproducibile.

Gli strumenti di intelligenza artificiale rappresentano un valido supporto nell'apprendimento e nella pratica di Python. Questi strumenti fungono da tutor virtuali, sempre disponibili, in grado di assistervi nella risoluzione dei problemi e nella comprensione dei processi. Se in passato Google era il punto di riferimento per i programmatori, oggi ChatGPT e Claude offrono soluzioni e spiegazioni immediate.

## IA

L'intelligenza artificiale ha trasformato l'approccio alla programmazione, rivoluzionando l'apprendimento e la pratica di questa disciplina. Strumenti come ChatGPT, Claude, Gemini e altri hanno reso l'IA un "tutor" costante e accessibile, capace di assistere gli studenti anche su questioni tecniche avanzate. In questo contesto, incoraggio l'utilizzo degli LLM (modelli di linguaggio di grandi dimensioni) sia per apprendere Python e R che per comprendere meglio i concetti teorici più complessi [@brouillette2024guide].

L'IA offre un supporto efficace per le attività creative come la scrittura e la programmazione, permettendovi di focalizzarvi sulle idee piuttosto che sui dettagli tecnici. Questo approccio consente di liberare risorse cognitive, accelerando il processo creativo e migliorando la qualità del lavoro.

Ecco alcuni esempi di come l'IA può supportare l'apprendimento e lo sviluppo:

-   **Tutor personalizzato**: L'IA può personalizzare il vostro percorso di apprendimento, chiarendo dubbi su concetti complessi e guidandovi nell'acquisizione di nuove competenze.
-   **Supporto per problemi complessi**: L'IA può risolvere problemi ben definiti e supportarvi nell'analisi e scomposizione di problemi più complessi.
-   **Ottimizzazione del codice**: Analizza e suggerisce miglioramenti al codice.
-   **Correzione di errori**: Rileva e corregge errori.
-   **Automatizzazione di compiti noiosi**: L'IA automatizza compiti ripetitivi, come la formattazione del codice, la generazione di documentazione e l'aggiunta di commenti.
-   **Motore di ricerca personalizzato**: L'IA funge da motore di ricerca istantaneo per ottenere guide dettagliate e complete su funzioni di Python e R.
-   **Miglioramento della struttura dei testi**: L'IA aiuta a rendere i testi più chiari e coerenti.
-   **Sintesi di testi e interazioni via chat**: Strumenti come `https://notebooklm.google.com/` generano riassunti di articoli o testi caricati, offrendo la possibilità di approfondire i contenuti attraverso interazioni via chat.

Tuttavia, è importante ricordare che:

-   Gli strumenti di IA non sono infallibili e potrebbero richiedere interventi correttivi in situazioni meno comuni.
-   Durante le verifiche non sarà consentito l'uso di questi strumenti per garantire una valutazione equa delle competenze. Invece, fate affidamento sulle vostre note personali, che sono strumenti essenziali per lo studio e la preparazione agli esami. Vi consiglio di utilizzare software come [Obsidian](https://obsidian.md) per organizzare al meglio il vostro materiale di studio.

Per progredire nell'ambito della programmazione, delegare all'intelligenza artificiale la risoluzione completa di un problema non è sufficiente. Un approccio più proficuo consiste nel porre all'IA domande mirate che stimolino la riflessione e la crescita professionale.

Invece di chiedere semplicemente di risolvere un problema, è consigliabile formulare quesiti come:

-   "Quali alternative di implementazione potremmo considerare per questo codice? Quali sono i vantaggi e gli svantaggi di ciascuna soluzione?" Questa domanda incoraggia l'esplorazione di diverse strategie e favorisce una comprensione più profonda dei principi alla base della programmazione.
-   "Puoi spiegarmi questo codice come se stessi parlando a un collega meno esperto? Quali aspetti ritieni più intuitivi e quali potrebbero creare maggiori difficoltà?" Questa richiesta stimola la capacità di comunicare efficacemente concetti tecnici e di individuare potenziali aree di miglioramento.
-   "Esistono modi per ristrutturare questo codice al fine di renderlo più modulare, leggibile e manutenibile?" Questa domanda promuove l'adozione di buone pratiche di programmazione e la scrittura di codice di alta qualità.
-   "Quali sono gli errori più comuni che i programmatori commettono quando affrontano problemi simili? Potresti fornire degli esempi concreti?" Questa domanda aiuta a prevenire errori comuni e a sviluppare una mentalità orientata alla risoluzione dei problemi.

Utilizzare l'IA in modo passivo, limitandosi a richiedere soluzioni preconfezionate, inibisce la crescita professionale. Al contrario, impiegare l'IA come un tutor attivo, ponendo domande mirate e approfondendo i concetti, massimizza le potenzialità di questo strumento. Questo approccio non è limitato alla programmazione, ma può essere applicato a qualsiasi ambito di apprendimento.

In sintesi, l'IA può essere un prezioso alleato nel percorso di crescita personale, a condizione di utilizzarla come uno strumento per stimolare la curiosità, approfondire le conoscenze e sviluppare un pensiero critico.

## Presentare i risultati

Durante il corso, impareremo come utilizzare il linguaggio di markup Markdown/HTML e alcuni elementi di LaTeX per presentare in modo chiaro ed efficace i risultati delle analisi statistiche.

## Forum

Una risorsa importante, ma spesso sotto-utilizzata, per prepararsi all'esame è il forum dedicato al corso su Moodle. Gli studenti che hanno dubbi dopo aver studiato il materiale assegnato possono porre domande e chiedere chiarimenti utilizzando questo forum.

Partecipare al forum offre vantaggi sia per coloro che chiedono aiuto, sia per coloro che rispondono, poiché spiegare gli argomenti aiuta a consolidare l'apprendimento. È incoraggiato che siano gli stessi studenti a rispondere alle domande degli altri, contribuendo così alla creazione di una comunità di apprendimento collaborativa.

# Valutazione dell'Apprendimento

L'esame sarà a libri aperti, consentendo agli studenti di sfruttare qualsiasi risorsa disponibile, sia cartacea che elettronica, sul proprio computer o online. Tuttavia, **sarà strettamente proibito l'utilizzo di strumenti di intelligenza artificiale**. Inoltre, durante la prima e la seconda prova intermedia, sarà richiesto agli studenti di lavorare in modo indipendente, e qualsiasi forma di collaborazione durante l'esame non sarà tollerata.

Le prestazioni degli studenti saranno valutate in modo relativo, in base alla distribuzione delle prestazioni degli studenti che frequentano regolarmente il corso.

## Studenti frequentanti

Per essere considerati "frequentanti", gli studenti devono soddisfare i seguenti requisiti:

-   **Consegna dei report in itinere**: Devono essere consegnati tutti i report in itinere entro le scadenze stabilite, ricevendo un giudizio positivo per ciascuno di essi.
-   **Prove parziali**: È necessario sostenere le due prove parziali programmate durante il semestre.
-   **Progetto di gruppo**: Attraverso un'analisi approfondita di una pubblicazione psicologica, gli studenti metteranno in pratica le conoscenze acquisite, realizzando un report scritto e una presentazione orale. L'utilizzo di strumenti di intelligenza artificiale è consentito per ottimizzare il lavoro e ottenere risultati di alta qualità.

### Dettagli sulle attività

1.  **Prove parziali**

    Gli studenti frequentanti saranno tenuti a completare due prove parziali che si svolgeranno tramite *quiz Moodle*.

    -   Ogni quiz consisterà in domande a scelta multipla, con cinque opzioni di risposta, di cui solo una corretta. Le risposte corrette verranno valutate con un punto, mentre quelle errate comporteranno una penalità di -0,25 punti; le risposte non date avranno punteggio nullo.
    -   Gli studenti dovranno rispondere alle domande in ordine sequenziale, senza possibilità di tornare indietro o saltare domande.
    -   Le domande saranno assegnate in modo casuale da un database, quindi i quiz varieranno tra gli studenti.
    -   I quiz saranno temporizzati, richiedendo risposte in un tempo limitato.
    -   Gli studenti dovranno usare il proprio computer per partecipare.
    -   I quiz sull'inferenza bayesiana richiederanno l’uso di Stan, installato sul computer dello studente o disponibile tramite Colab.

2.  **Progetti di gruppo**

    Gli studenti frequentanti saranno organizzati in piccoli gruppi con due responsabilità principali: (a) redigere un report finale per descrivere il progetto e (b) completare report in itinere per monitorare l’avanzamento.

    -   **Project Report**: Il report, con una lunghezza massima di 20 pagine, dovrà includere i seguenti elementi:

        -   **Introduzione**: descrizione del problema analizzato, motivazione dell’analisi e strategia modellistica principale (includere, se possibile, una figura illustrativa).
        -   **Descrizione dei dati e del problema di analisi**: spiegare come l’analisi differisca da quelle già esistenti.
        -   **Modelli utilizzati**: descrivere almeno due modelli (es., gerarchico/non gerarchico, lineare/non lineare).
        -   **Scelta dei priors**: giustificare l’uso di priors informativi o debolmente informativi.
        -   **Codice**: fornire il codice in Stan, Bambi o brms.
        -   **Esecuzione del modello in Stan**: descrivere le opzioni utilizzate, con spiegazioni accompagnate dal codice.
        -   **Diagnostica della convergenza**: indicare le strategie adottate per risolvere eventuali problemi di convergenza.
        -   **Posterior predictive checks**: documentare i risultati delle verifiche di validità predittiva e gli interventi per migliorare il modello.
        -   **Valutazione delle performance predittive**: includere i risultati per ogni modello.
        -   **Analisi di sensibilità sui priors**: documentare come variano i risultati cambiando i priors.
        -   **Confronto tra modelli**: es., tramite LOO-CV.
        -   **Confronto con l’approccio frequentista**: eseguire l’analisi con un approccio frequentista e confrontare i risultati con quelli bayesiani, evidenziando le differenze nelle conclusioni.
        -   **Discussione e conclusioni**: analizzare criticità, possibili miglioramenti e confrontare i risultati con quanto riportato nella letteratura di riferimento.
        -   **Riflessione finale**: descrivere cosa il gruppo ha appreso durante il progetto.

    -   **Esempi.**\
        I seguenti esempi di casi studio mostrano come testo, equazioni, figure, codice e risultati inferenziali possano essere integrati in un unico report. Questi esempi non includono necessariamente tutti i passaggi richiesti per il vostro report e trattano problemi di analisi dei dati più complessi rispetto a quelli affrontati in questo corso. Tuttavia, ogni caso studio illustra passaggi diversi del workflow, offrendo ottimi spunti per la stesura del report richiesto.

        -   [Bayesian workflow for disease transmission modeling in Stan](https://mc-stan.org/users/documentation/case-studies/boarding_school_case_study.html)
        -   [Predator-Prey Population Dynamics: the Lotka-Volterra model in Stan](https://mc-stan.org/users/documentation/case-studies/lotka-volterra-predator-prey.html)
        -   [A first look at multilevel regression; or Everybody’s got something to hide except me and my macaques](https://dansblog.netlify.app/posts/2022-09-04-everybodys-got-something-to-hide-except-me-and-my-monkey/everybodys-got-something-to-hide-except-me-and-my-monkey.html)

    -   **Presentazioni asincrone**: Ogni gruppo registrerà una presentazione di 15 minuti e caricherà il video su una piattaforma online [@bourne2007ten]. Gli studenti guarderanno le presentazioni degli altri gruppi prima dell’incontro in presenza.

    -   **Peer review strutturata**: Tramite Moodle Workshop, gli studenti valuteranno i progetti degli altri gruppi, basandosi su una rubrica standardizzata che consideri la qualità del feedback fornito, la chiarezza e la pertinenza delle argomentazioni.

    -   **Sintesi delle discussioni**: Ogni gruppo nominerà un "relatore" per sintetizzare i punti chiave emersi dalla peer review, utilizzando queste sintesi come base per la discussione in aula.

    -   **Discussione in presenza**: Le quattro ore di lezione in presenza saranno dedicate a discussioni approfondite. Ogni gruppo avrà 20-25 minuti per rispondere alle domande e discutere i punti chiave del proprio progetto.

3.  **Report in itinere**

    Per monitorare l’avanzamento dei progetti di gruppo, saranno assegnati report periodici da caricare su Moodle. La compilazione dei report in itinere è obbligatoria per tutti gli studenti frequentanti.

### Valutazione Finale

Gli studenti che avranno completato con successo tutti i report intermedi e partecipato alle attività richieste riceveranno una valutazione finale basata sui seguenti criteri:

-   **Primo esame parziale**: Il primo quiz parziale su Moodle, che si svolgerà a metà corso, contribuirà con 30 punti al voto finale.

-   **Secondo esame parziale**: Il secondo quiz parziale, sempre su Moodle e programmato per la fine del corso, sarà valutato fino a 30 punti.

-   **Progetto di gruppo**: La valutazione del progetto di gruppo contribuirà con 30 punti al voto finale. Questa valutazione si baserà sul report scritto e sulla presentazione orale che documentano l'analisi dati condotta su una recente pubblicazione psicologica. La valutazione del report includerà aspetti come la chiarezza dell'introduzione, la descrizione dei dati e dei modelli, la giustificazione dei priors, l'accuratezza dell'esecuzione del modello, la diagnosi di convergenza e le verifiche posterior predictive.

-   **Peer review strutturata**: L'attività di peer review, svolta tramite Moodle Workshop, rappresenterà 10 punti del voto finale. Gli studenti saranno valutati per la qualità, la chiarezza e la pertinenza del feedback fornito ai colleghi. Questa attività non solo contribuisce alla valutazione, ma promuove lo sviluppo di capacità critiche e argomentative.

-   **Voto finale**: Il voto finale sarà calcolato su un totale di 100 punti, che verranno poi convertiti in una valutazione in trentesimi.

### Esperienza di laboratorio

-   **Bonus**: Gli studenti hanno l'opzione di guadagnare 2 punti bonus partecipando a un'esperienza di laboratorio (impegno di circa 5 ore). Questi punti saranno sommati al voto finale in trentesimi.

-   **Codice**: Per iscriversi all'esperienza di laboratorio, usare il seguente codice (da aggiungere al modulo di iscrizione ai gruppi):

    -   Prime due lettere del nome,
    -   Prime due lettere del cognome,
    -   Data di nascita: anno, mese, giorno, es, 1999_03_06 (6 marzo 1999),
    -   Ultime 3 cifre del cellulare,
    -   Genere.
    -   Separatore: trattino basso.

Per esempio: Mario Rossi, nato il 6 marzo 1999, telefono 320 2294312.

Codice: ma_ro_1999_03_06_312_m

-   Nonostante non sia obbligatoria, l'esperienza di laboratorio offre l'opportunità di aumentare il punteggio e acquisire una visione pratica dei progetti di ricerca in psicologia.
    -   Si noti che, durante questo laboratorio, si adotteranno tecniche di analisi statistica per identificare comportamenti inappropriati come il "careless responding". In caso di comportamenti scorretti, gli studenti perderanno l'opportunità di guadagnare punti bonus e saranno sottoposti a un'integrazione orale obbligatoria per superare l'esame.

### Considerazioni aggiuntive

-   **Storico**: Negli anni accademici passati, la maggior parte degli studenti ha optato per il percorso "frequentanti", conseguendo risultati positivi.
-   Gli studenti sono incoraggiati a sfruttare questo percorso per ottenere una formazione pratica approfondita e un voto finale soddisfacente.
-   Gli studenti frequentanti che supereranno l'esame **dovranno** iscriversi al primo appello utile d'esame. Una volta iscritti, non dovranno compiere ulteriori azioni poiché mi occuperò personalmente della verbalizzazione e dell'inserimento del voto.

## Studenti non frequentanti

L'esame per le sessioni degli esami sarà condotto tramite un quiz Moodle, simile agli esercizi presenti nella dispensa.

Affinché gli studenti possano partecipare all'esame, è necessario che portino con sé un computer portatile alla Torretta il giorno previsto per l'esame, come è richiesto anche per gli studenti che frequentano regolarmente le lezioni.

Desidero sottolineare che il programma d'esame rimarrà invariato e sarà applicato uniformemente sia agli studenti frequentanti che a quelli non frequentanti.

# Ulteriori informazioni

## Ricevimento

Avendo diversi insegnamenti la stessa giornata, lascerò l'aula immediatamente dopo la fine della lezione. Resto comunque a vostra disposizione e sono facilmente raggiungibile tramite Moodle. Essendo un docente con un alto numero di studenti, vi chiedo cortesemente di evitare di contattarmi via e-mail e di utilizzare invece Moodle per organizzare eventuali incontri di gruppo. Durante queste occasioni, potremo interagire in modo tranquillo e produttivo attraverso Google Meet. Questo ci consentirà di rispondere alle vostre domande e fornire ulteriori chiarimenti in modo efficace e organizzato.

## Comportamento in aula

Nel contesto di questo corso, attribuiamo un'importanza cruciale alla considerazione reciproca. Invito calorosamente tutti gli studenti a partecipare attivamente alle discussioni in aula, poiché ciascuno di voi potrebbe avere opinioni diverse sugli argomenti trattati. L'apporto di prospettive differenti non solo è gradito, ma anche estremamente apprezzato, poiché arricchisce il dibattito e favorisce una comprensione più completa e diversificata delle tematiche in esame.

Inoltre, è altrettanto importante mettere in discussione le idee degli altri, comprese le mie. Tuttavia, per garantire che le discussioni siano proficue, mi impegno a svolgere il ruolo di moderatore, assicurando che le idee vengano esaminate in modo tranquillo e rispettoso, e che gli argomenti vengano esposti in modo chiaro e logico.

La partecipazione attiva e il rispetto reciproco durante le discussioni contribuiranno a creare un ambiente accademico stimolante e arricchente, che favorirà il vostro apprendimento e la crescita intellettuale. Pertanto, vi incoraggio vivamente a prendere parte attiva alle lezioni e a condividere il vostro punto di vista, contribuendo così a arricchire l'esperienza di tutti i partecipanti.

## Norme relative all'uso della posta elettronica

Desidero sottolineare l'importanza di un utilizzo diligente della posta elettronica nel contesto del nostro corso. Di solito, mi impegno a rispondere prontamente alle e-mail degli studenti, ma vorrei porre l'accento su alcune considerazioni per ottimizzare questa forma di comunicazione.

Innanzitutto, vorrei gentilmente richiamare la vostra attenzione sul fatto che molte delle informazioni che potreste cercare sono già disponibili sul sito web del corso. Prima di inviarmi una richiesta, vi prego di *consultare attentamente il materiale fornito sul sito web*. Questo eviterà duplicazioni e permetterà una gestione più efficiente delle comunicazioni.

Per agevolare ulteriormente la vostra interazione con me, desidero ribadire alcuni punti cruciali:

-   Il programma d'esame, le modalità di svolgimento dell'esame e i testi consigliati per la preparazione degli studenti non frequentanti sono disponibili sul sito web del corso.
-   Per organizzare un incontro tramite Google Meet, vi invito a inviarmi un messaggio personale attraverso Moodle, che sarà uno strumento di gestione organizzativa delle riunioni. Preferisco, ove possibile, pianificare incontri di gruppo, ma qualora fosse necessario un colloquio individuale, potremo concordare un appuntamento "privato".

Adottando queste pratiche, renderemo la nostra comunicazione più fluida ed efficiente, consentendoci di concentrarci maggiormente sul vostro apprendimento e sulla massimizzazione dei risultati durante le attività didattiche.

## Politica sulla disonestà accademica

L'integrità accademica rappresenta un principio fondamentale per garantire un corretto svolgimento del percorso formativo. Pertanto, desidero enfatizzare la disapprovazione di qualsiasi forma di comportamento disonesto. Vi esorto dunque ad astenervi dal:

-   Utilizzare aiuti non autorizzati durante test in classe o nell'esame finale;
-   Copiare, sia intenzionalmente che involontariamente, testo, struttura o idee da fonti esterne senza attribuire correttamente la fonte.

La disonestà accademica non solo viola principi etici fondamentali, ma mina anche la credibilità e l'equità del processo di valutazione e dell'apprendimento stesso. Per questo motivo, mi impegno a far rispettare rigorosamente la politica accademica in vigore, che prevede misure adeguate in caso di violazioni.

Nel perseguire la formazione accademica, è essenziale instaurare una cultura di onestà e rispetto delle regole, al fine di garantire un ambiente di apprendimento etico e proficuo per tutti i partecipanti. Sono fiducioso nel vostro impegno a mantenere un comportamento corretto e rispettoso degli standard di integrità accademica richiesti.

## Politica sulle disabilità

Nel caso in cui uno studente presenti bisogni educativi speciali, lo invito a comunicarmelo *in modo confidenziale* quanto prima. Assicuro il pieno rispetto del diritto alla privacy in materia, senza alcuna eccezione.

## Considerazioni finali

Come avviene in ogni corso, il successo degli studenti è principalmente determinato dal loro impegno durante il semestre. È essenziale chiedere aiuto ai compagni di classe e a me: non esitate a porre domande su ciò che non avete compreso o a verificare la vostra comprensione di un argomento.

\pagebreak

# Bibliografia